// src/main/webapp/app/entities/organisation/organisation.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="OrganisationHeading">
      <span v-text="$t('teamDojoApp.organisation.home.title')" id="organisation-heading">Organisations</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('teamDojoApp.organisation.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'OrganisationCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-organisation"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('teamDojoApp.organisation.home.createLabel')"> Create a new Organisation </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && organisations && organisations.length === 0">
      <span v-text="$t('teamDojoApp.organisation.home.notFound')">No organisations found</span>
    </div>
    <div class="table-responsive" v-if="organisations && organisations.length > 0">
      <table class="table table-striped" aria-describedby="organisations">
        <thead>
          <tr>
            <th scope="row"><span v-text="$t('global.field.id')">ID</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.organisation.title')">Title</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.organisation.description')">Description</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.organisation.levelUpScore')">Level Up Score</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.organisation.applicationMode')">Application Mode</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.organisation.countOfConfirmations')">Count Of Confirmations</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.organisation.createdAt')">Created At</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.organisation.updatedAt')">Updated At</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.organisation.parent')">Parent</span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="organisation in organisations" :key="organisation.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'OrganisationView', params: { organisationId: organisation.id } }">{{
                organisation.id
              }}</router-link>
            </td>
            <td>{{ organisation.title }}</td>
            <td>{{ organisation.description }}</td>
            <td>{{ organisation.levelUpScore }}</td>
            <td v-text="$t('teamDojoApp.ApplicationMode.' + organisation.applicationMode)">{{ organisation.applicationMode }}</td>
            <td>{{ organisation.countOfConfirmations }}</td>
            <td>{{ organisation.createdAt ? $d(Date.parse(organisation.createdAt), 'short') : '' }}</td>
            <td>{{ organisation.updatedAt ? $d(Date.parse(organisation.updatedAt), 'short') : '' }}</td>
            <td>
              <div v-if="organisation.parent">
                <router-link :to="{ name: 'OrganisationView', params: { organisationId: organisation.parent.id } }">{{
                  organisation.parent.id
                }}</router-link>
              </div>
            </td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'OrganisationView', params: { organisationId: organisation.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'OrganisationEdit', params: { organisationId: organisation.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(organisation)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="teamDojoApp.organisation.delete.question" data-cy="organisationDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-organisation-heading" v-text="$t('teamDojoApp.organisation.delete.question', { id: removeId })">
          Are you sure you want to delete this Organisation?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-organisation"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeOrganisation()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./organisation.component.ts"></script>

// src/main/webapp/app/entities/organisation/list/organisation.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IOrganisation } from '../organisation.model';
import { OrganisationService } from '../service/organisation.service';
import { OrganisationDeleteDialogComponent } from '../delete/organisation-delete-dialog.component';

@Component({
  selector: 'jhi-organisation',
  templateUrl: './organisation.component.html',
})
export class OrganisationComponent implements OnInit {
  organisations?: IOrganisation[];
  isLoading = false;

  constructor(protected organisationService: OrganisationService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.organisationService.query().subscribe({
      next: (res: HttpResponse<IOrganisation[]>) => {
        this.isLoading = false;
        this.organisations = res.body ?? [];
      },
      error: () => {
        this.isLoading = false;
      },
    });
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IOrganisation): number {
    return item.id!;
  }

  delete(organisation: IOrganisation): void {
    const modalRef = this.modalService.open(OrganisationDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.organisation = organisation;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="OrganisationHeading">
    <span jhiTranslate="teamDojoApp.organisation.home.title">Organisations</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="teamDojoApp.organisation.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-organisation"
        [routerLink]="['/organisation/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="teamDojoApp.organisation.home.createLabel"> Create a new Organisation </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="organisations?.length === 0">
    <span jhiTranslate="teamDojoApp.organisation.home.notFound">No organisations found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="organisations && organisations.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="teamDojoApp.organisation.title">Title</span></th>
          <th scope="col"><span jhiTranslate="teamDojoApp.organisation.description">Description</span></th>
          <th scope="col"><span jhiTranslate="teamDojoApp.organisation.levelUpScore">Level Up Score</span></th>
          <th scope="col"><span jhiTranslate="teamDojoApp.organisation.applicationMode">Application Mode</span></th>
          <th scope="col"><span jhiTranslate="teamDojoApp.organisation.countOfConfirmations">Count Of Confirmations</span></th>
          <th scope="col"><span jhiTranslate="teamDojoApp.organisation.createdAt">Created At</span></th>
          <th scope="col"><span jhiTranslate="teamDojoApp.organisation.updatedAt">Updated At</span></th>
          <th scope="col"><span jhiTranslate="teamDojoApp.organisation.parent">Parent</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let organisation of organisations; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/organisation', organisation.id, 'view']">{{ organisation.id }}</a>
          </td>
          <td>{{ organisation.title }}</td>
          <td>{{ organisation.description }}</td>
          <td>{{ organisation.levelUpScore }}</td>
          <td jhiTranslate="{{ 'teamDojoApp.ApplicationMode.' + organisation.applicationMode }}">{{ organisation.applicationMode }}</td>
          <td>{{ organisation.countOfConfirmations }}</td>
          <td>{{ organisation.createdAt | formatMediumDatetime }}</td>
          <td>{{ organisation.updatedAt | formatMediumDatetime }}</td>
          <td>
            <div *ngIf="organisation.parent">
              <a [routerLink]="['/organisation', organisation.parent?.id, 'view']">{{ organisation.parent?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/organisation', organisation.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/organisation', organisation.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(organisation)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
