// src/main/webapp/app/entities/comment/comment-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.comment.home.createOrEditLabel"
          data-cy="CommentCreateUpdateHeading"
          v-text="$t('teamDojoApp.comment.home.createOrEditLabel')"
        >
          Create or edit a Comment
        </h2>
        <div>
          <div class="form-group" v-if="comment.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="comment.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.comment.text')" for="comment-text">Text</label>
            <input
              type="text"
              class="form-control"
              name="text"
              id="comment-text"
              data-cy="text"
              :class="{ valid: !$v.comment.text.$invalid, invalid: $v.comment.text.$invalid }"
              v-model="$v.comment.text.$model"
              required
            />
            <div v-if="$v.comment.text.$anyDirty && $v.comment.text.$invalid">
              <small class="form-text text-danger" v-if="!$v.comment.text.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.comment.createdAt')" for="comment-createdAt">Created At</label>
            <div class="d-flex">
              <input
                id="comment-createdAt"
                data-cy="createdAt"
                type="datetime-local"
                class="form-control"
                name="createdAt"
                :class="{ valid: !$v.comment.createdAt.$invalid, invalid: $v.comment.createdAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.comment.createdAt.$model)"
                @change="updateInstantField('createdAt', $event)"
              />
            </div>
            <div v-if="$v.comment.createdAt.$anyDirty && $v.comment.createdAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.comment.createdAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.comment.createdAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.comment.updatedAt')" for="comment-updatedAt">Updated At</label>
            <div class="d-flex">
              <input
                id="comment-updatedAt"
                data-cy="updatedAt"
                type="datetime-local"
                class="form-control"
                name="updatedAt"
                :class="{ valid: !$v.comment.updatedAt.$invalid, invalid: $v.comment.updatedAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.comment.updatedAt.$model)"
                @change="updateInstantField('updatedAt', $event)"
              />
            </div>
            <div v-if="$v.comment.updatedAt.$anyDirty && $v.comment.updatedAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.comment.updatedAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.comment.updatedAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.comment.team')" for="comment-team">Team</label>
            <select class="form-control" id="comment-team" data-cy="team" name="team" v-model="comment.team" required>
              <option v-if="!comment.team" v-bind:value="null" selected></option>
              <option
                v-bind:value="comment.team && teamOption.id === comment.team.id ? comment.team : teamOption"
                v-for="teamOption in teams"
                :key="teamOption.id"
              >
                {{ teamOption.shortTitle }}
              </option>
            </select>
          </div>
          <div v-if="$v.comment.team.$anyDirty && $v.comment.team.$invalid">
            <small class="form-text text-danger" v-if="!$v.comment.team.required" v-text="$t('entity.validation.required')">
              This field is required.
            </small>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.comment.skill')" for="comment-skill">Skill</label>
            <select class="form-control" id="comment-skill" data-cy="skill" name="skill" v-model="comment.skill" required>
              <option v-if="!comment.skill" v-bind:value="null" selected></option>
              <option
                v-bind:value="comment.skill && skillOption.id === comment.skill.id ? comment.skill : skillOption"
                v-for="skillOption in skills"
                :key="skillOption.id"
              >
                {{ skillOption.title }}
              </option>
            </select>
          </div>
          <div v-if="$v.comment.skill.$anyDirty && $v.comment.skill.$invalid">
            <small class="form-text text-danger" v-if="!$v.comment.skill.required" v-text="$t('entity.validation.required')">
              This field is required.
            </small>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.comment.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./comment-update.component.ts"></script>

// src/main/webapp/app/entities/comment/update/comment-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { CommentFormService, CommentFormGroup } from './comment-form.service';
import { IComment } from '../comment.model';
import { CommentService } from '../service/comment.service';
import { ITeam } from 'app/entities/team/team.model';
import { TeamService } from 'app/entities/team/service/team.service';
import { ISkill } from 'app/entities/skill/skill.model';
import { SkillService } from 'app/entities/skill/service/skill.service';

@Component({
  selector: 'jhi-comment-update',
  templateUrl: './comment-update.component.html',
})
export class CommentUpdateComponent implements OnInit {
  isSaving = false;
  comment: IComment | null = null;

  teamsSharedCollection: ITeam[] = [];
  skillsSharedCollection: ISkill[] = [];

  editForm: CommentFormGroup = this.commentFormService.createCommentFormGroup();

  constructor(
    protected commentService: CommentService,
    protected commentFormService: CommentFormService,
    protected teamService: TeamService,
    protected skillService: SkillService,
    protected activatedRoute: ActivatedRoute
  ) {}

  compareTeam = (o1: ITeam | null, o2: ITeam | null): boolean => this.teamService.compareTeam(o1, o2);

  compareSkill = (o1: ISkill | null, o2: ISkill | null): boolean => this.skillService.compareSkill(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ comment }) => {
      this.comment = comment;
      if (comment) {
        this.updateForm(comment);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const comment = this.commentFormService.getComment(this.editForm);
    if (comment.id !== null) {
      this.subscribeToSaveResponse(this.commentService.update(comment));
    } else {
      this.subscribeToSaveResponse(this.commentService.create(comment));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IComment>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(comment: IComment): void {
    this.comment = comment;
    this.commentFormService.resetForm(this.editForm, comment);

    this.teamsSharedCollection = this.teamService.addTeamToCollectionIfMissing<ITeam>(this.teamsSharedCollection, comment.team);
    this.skillsSharedCollection = this.skillService.addSkillToCollectionIfMissing<ISkill>(this.skillsSharedCollection, comment.skill);
  }

  protected loadRelationshipsOptions(): void {
    this.teamService
      .query()
      .pipe(map((res: HttpResponse<ITeam[]>) => res.body ?? []))
      .pipe(map((teams: ITeam[]) => this.teamService.addTeamToCollectionIfMissing<ITeam>(teams, this.comment?.team)))
      .subscribe((teams: ITeam[]) => (this.teamsSharedCollection = teams));

    this.skillService
      .query()
      .pipe(map((res: HttpResponse<ISkill[]>) => res.body ?? []))
      .pipe(map((skills: ISkill[]) => this.skillService.addSkillToCollectionIfMissing<ISkill>(skills, this.comment?.skill)))
      .subscribe((skills: ISkill[]) => (this.skillsSharedCollection = skills));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-comment-heading" data-cy="CommentCreateUpdateHeading" jhiTranslate="teamDojoApp.comment.home.createOrEditLabel">
        Create or edit a Comment
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="row mb-3" [hidden]="editForm.get('id')!.value == null">
          <label class="form-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.comment.text" for="field_text">Text</label>
          <input type="text" class="form-control" name="text" id="field_text" data-cy="text" formControlName="text" />
          <div *ngIf="editForm.get('text')!.invalid && (editForm.get('text')!.dirty || editForm.get('text')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('text')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('text')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 4096 }"
            >
              This field cannot be longer than 4096 characters.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.comment.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('createdAt')!.invalid && (editForm.get('createdAt')!.dirty || editForm.get('createdAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('createdAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('createdAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.comment.updatedAt" for="field_updatedAt">Updated At</label>
          <div class="d-flex">
            <input
              id="field_updatedAt"
              data-cy="updatedAt"
              type="datetime-local"
              class="form-control"
              name="updatedAt"
              formControlName="updatedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('updatedAt')!.invalid && (editForm.get('updatedAt')!.dirty || editForm.get('updatedAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('updatedAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('updatedAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.comment.team" for="field_team">Team</label>
          <select class="form-control" id="field_team" data-cy="team" name="team" formControlName="team">
            <option *ngIf="!editForm.get('team')!.value" [ngValue]="null" selected></option>
            <option
              [ngValue]="teamOption.id === editForm.get('team')!.value?.id ? editForm.get('team')!.value : teamOption"
              *ngFor="let teamOption of teamsSharedCollection; trackBy: trackTeamById"
            >
              {{ teamOption.shortTitle }}
            </option>
          </select>
        </div>
        <div *ngIf="editForm.get(['team'])!.invalid && (editForm.get(['team'])!.dirty || editForm.get(['team'])!.touched)">
          <small class="form-text text-danger" *ngIf="editForm.get(['team'])?.errors?.required" jhiTranslate="entity.validation.required">
            This field is required.
          </small>
        </div>

        <!-- ### Modification-Start ### -->
        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.comment.skill" for="field_skill">Skill</label>
          <select class="form-control" id="field_skill" data-cy="skill" name="skill" formControlName="skill">
            <option *ngIf="!editForm.get('skill')!.value" [ngValue]="null" selected></option>
            <option
              [ngValue]="skillOption.id === editForm.get('skill')!.value?.id ? editForm.get('skill')!.value : skillOption"
              *ngFor="let skillOption of skillsSharedCollection; trackBy: trackSkillById"
            >
              <!-- ### MODIFICATION-START ### -->
              {{ skillOption | translateModel: 'title' }}
              <!-- ### MODIFICATION-END ### -->
            </option>
          </select>
          <!-- ### Modification-End ### -->
        </div>
        <div *ngIf="editForm.get(['skill'])!.invalid && (editForm.get(['skill'])!.dirty || editForm.get(['skill'])!.touched)">
          <small class="form-text text-danger" *ngIf="editForm.get(['skill'])?.errors?.required" jhiTranslate="entity.validation.required">
            This field is required.
          </small>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
