// src/main/webapp/app/entities/badge-skill/list/badge-skill.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IBadgeSkill } from '../badge-skill.model';

import { ITEMS_PER_PAGE } from 'app/config/pagination.constants';
import { BadgeSkillService } from '../service/badge-skill.service';
import { BadgeSkillDeleteDialogComponent } from '../delete/badge-skill-delete-dialog.component';
import { ParseLinks } from 'app/core/util/parse-links.service';

@Component({
  selector: 'jhi-badge-skill',
  templateUrl: './badge-skill.component.html',
})
export class BadgeSkillComponent implements OnInit {
  badgeSkills: IBadgeSkill[];
  isLoading = false;
  itemsPerPage: number;
  links: { [key: string]: number };
  page: number;
  predicate: string;
  ascending: boolean;

  constructor(protected badgeSkillService: BadgeSkillService, protected modalService: NgbModal, protected parseLinks: ParseLinks) {
    this.badgeSkills = [];
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.page = 0;
    this.links = {
      last: 0,
    };
    this.predicate = 'id';
    this.ascending = true;
  }

  loadAll(): void {
    this.isLoading = true;

    this.badgeSkillService
      .query({
        page: this.page,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<IBadgeSkill[]>) => {
          this.isLoading = false;
          this.paginateBadgeSkills(res.body, res.headers);
        },
        () => {
          this.isLoading = false;
        }
      );
  }

  reset(): void {
    this.page = 0;
    this.badgeSkills = [];
    this.loadAll();
  }

  loadPage(page: number): void {
    this.page = page;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IBadgeSkill): number {
    return item.id!;
  }

  delete(badgeSkill: IBadgeSkill): void {
    const modalRef = this.modalService.open(BadgeSkillDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.badgeSkill = badgeSkill;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.reset();
      }
    });
  }

  protected sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateBadgeSkills(data: IBadgeSkill[] | null, headers: HttpHeaders): void {
    this.links = this.parseLinks.parse(headers.get('link') ?? '');
    if (data) {
      for (const d of data) {
        this.badgeSkills.push(d);
      }
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="BadgeSkillHeading">
    <span jhiTranslate="teamDojoApp.badgeSkill.home.title">Badge Skills</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="reset()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="teamDojoApp.badgeSkill.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-badge-skill"
        [routerLink]="['/badge-skill/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="teamDojoApp.badgeSkill.home.createLabel"> Create a new Badge Skill </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="badgeSkills?.length === 0">
    <span jhiTranslate="teamDojoApp.badgeSkill.home.notFound">No badgeSkills found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="badgeSkills && badgeSkills.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="reset.bind(this)">
          <th scope="col" jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="badge.title">
            <span jhiTranslate="teamDojoApp.badgeSkill.badge">Badge</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="skill.title">
            <span jhiTranslate="teamDojoApp.badgeSkill.skill">Skill</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
        <tr *ngFor="let badgeSkill of badgeSkills; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/badge-skill', badgeSkill.id, 'view']">{{ badgeSkill.id }}</a>
          </td>
          <td>
            <div *ngIf="badgeSkill.badge">
              <a [routerLink]="['/badge', badgeSkill.badge?.id, 'view']">{{ badgeSkill.badge?.title }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="badgeSkill.skill">
              <a [routerLink]="['/skill', badgeSkill.skill?.id, 'view']">{{ badgeSkill.skill?.title }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/badge-skill', badgeSkill.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/badge-skill', badgeSkill.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(badgeSkill)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/badge-skill/badge-skill.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="BadgeSkillHeading">
      <span v-text="$t('teamDojoApp.badgeSkill.home.title')" id="badge-skill-heading">Badge Skills</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('teamDojoApp.badgeSkill.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'BadgeSkillCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-badge-skill"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('teamDojoApp.badgeSkill.home.createLabel')"> Create a new Badge Skill </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && badgeSkills && badgeSkills.length === 0">
      <span v-text="$t('teamDojoApp.badgeSkill.home.notFound')">No badgeSkills found</span>
    </div>
    <div class="table-responsive" v-if="badgeSkills && badgeSkills.length > 0">
      <table class="table table-striped" aria-describedby="badgeSkills">
        <thead>
          <tr>
            <th scope="row" v-on:click="changeOrder('id')">
              <span v-text="$t('global.field.id')">ID</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('badge.title')">
              <span v-text="$t('teamDojoApp.badgeSkill.badge')">Badge</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'badge.title'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('skill.title')">
              <span v-text="$t('teamDojoApp.badgeSkill.skill')">Skill</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'skill.title'"></jhi-sort-indicator>
            </th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="badgeSkill in badgeSkills" :key="badgeSkill.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'BadgeSkillView', params: { badgeSkillId: badgeSkill.id } }">{{ badgeSkill.id }}</router-link>
            </td>
            <td>
              <div v-if="badgeSkill.badge">
                <router-link :to="{ name: 'BadgeView', params: { badgeId: badgeSkill.badge.id } }">{{
                  badgeSkill.badge.title
                }}</router-link>
              </div>
            </td>
            <td>
              <div v-if="badgeSkill.skill">
                <router-link :to="{ name: 'SkillView', params: { skillId: badgeSkill.skill.id } }">{{
                  badgeSkill.skill.title
                }}</router-link>
              </div>
            </td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'BadgeSkillView', params: { badgeSkillId: badgeSkill.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'BadgeSkillEdit', params: { badgeSkillId: badgeSkill.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(badgeSkill)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
        <infinite-loading
          ref="infiniteLoading"
          v-if="totalItems > itemsPerPage"
          :identifier="infiniteId"
          slot="append"
          @infinite="loadMore"
          force-use-infinite-wrapper=".el-table__body-wrapper"
          :distance="20"
        >
        </infinite-loading>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="teamDojoApp.badgeSkill.delete.question" data-cy="badgeSkillDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-badgeSkill-heading" v-text="$t('teamDojoApp.badgeSkill.delete.question', { id: removeId })">
          Are you sure you want to delete this Badge Skill?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-badgeSkill"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeBadgeSkill()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./badge-skill.component.ts"></script>
