// src/main/webapp/app/entities/team-skill/team-skill-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.teamSkill.home.createOrEditLabel"
          data-cy="TeamSkillCreateUpdateHeading"
          v-text="$t('teamDojoApp.teamSkill.home.createOrEditLabel')"
        >
          Create or edit a TeamSkill
        </h2>
        <div>
          <div class="form-group" v-if="teamSkill.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="teamSkill.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.teamSkill.completedAt')" for="team-skill-completedAt"
              >Completed At</label
            >
            <div class="d-flex">
              <input
                id="team-skill-completedAt"
                data-cy="completedAt"
                type="datetime-local"
                class="form-control"
                name="completedAt"
                :class="{ valid: !$v.teamSkill.completedAt.$invalid, invalid: $v.teamSkill.completedAt.$invalid }"
                :value="convertDateTimeFromServer($v.teamSkill.completedAt.$model)"
                @change="updateInstantField('completedAt', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.teamSkill.verifiedAt')" for="team-skill-verifiedAt"
              >Verified At</label
            >
            <div class="d-flex">
              <input
                id="team-skill-verifiedAt"
                data-cy="verifiedAt"
                type="datetime-local"
                class="form-control"
                name="verifiedAt"
                :class="{ valid: !$v.teamSkill.verifiedAt.$invalid, invalid: $v.teamSkill.verifiedAt.$invalid }"
                :value="convertDateTimeFromServer($v.teamSkill.verifiedAt.$model)"
                @change="updateInstantField('verifiedAt', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.teamSkill.irrelevant')" for="team-skill-irrelevant">Irrelevant</label>
            <input
              type="checkbox"
              class="form-check"
              name="irrelevant"
              id="team-skill-irrelevant"
              data-cy="irrelevant"
              :class="{ valid: !$v.teamSkill.irrelevant.$invalid, invalid: $v.teamSkill.irrelevant.$invalid }"
              v-model="$v.teamSkill.irrelevant.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.teamSkill.note')" for="team-skill-note">Note</label>
            <input
              type="text"
              class="form-control"
              name="note"
              id="team-skill-note"
              data-cy="note"
              :class="{ valid: !$v.teamSkill.note.$invalid, invalid: $v.teamSkill.note.$invalid }"
              v-model="$v.teamSkill.note.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.teamSkill.vote')" for="team-skill-vote">Vote</label>
            <input
              type="number"
              class="form-control"
              name="vote"
              id="team-skill-vote"
              data-cy="vote"
              :class="{ valid: !$v.teamSkill.vote.$invalid, invalid: $v.teamSkill.vote.$invalid }"
              v-model.number="$v.teamSkill.vote.$model"
              required
            />
            <div v-if="$v.teamSkill.vote.$anyDirty && $v.teamSkill.vote.$invalid">
              <small class="form-text text-danger" v-if="!$v.teamSkill.vote.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.teamSkill.vote.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.teamSkill.voters')" for="team-skill-voters">Voters</label>
            <input
              type="text"
              class="form-control"
              name="voters"
              id="team-skill-voters"
              data-cy="voters"
              :class="{ valid: !$v.teamSkill.voters.$invalid, invalid: $v.teamSkill.voters.$invalid }"
              v-model="$v.teamSkill.voters.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.teamSkill.createdAt')" for="team-skill-createdAt">Created At</label>
            <div class="d-flex">
              <input
                id="team-skill-createdAt"
                data-cy="createdAt"
                type="datetime-local"
                class="form-control"
                name="createdAt"
                :class="{ valid: !$v.teamSkill.createdAt.$invalid, invalid: $v.teamSkill.createdAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.teamSkill.createdAt.$model)"
                @change="updateInstantField('createdAt', $event)"
              />
            </div>
            <div v-if="$v.teamSkill.createdAt.$anyDirty && $v.teamSkill.createdAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.teamSkill.createdAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.teamSkill.createdAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.teamSkill.updatedAt')" for="team-skill-updatedAt">Updated At</label>
            <div class="d-flex">
              <input
                id="team-skill-updatedAt"
                data-cy="updatedAt"
                type="datetime-local"
                class="form-control"
                name="updatedAt"
                :class="{ valid: !$v.teamSkill.updatedAt.$invalid, invalid: $v.teamSkill.updatedAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.teamSkill.updatedAt.$model)"
                @change="updateInstantField('updatedAt', $event)"
              />
            </div>
            <div v-if="$v.teamSkill.updatedAt.$anyDirty && $v.teamSkill.updatedAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.teamSkill.updatedAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.teamSkill.updatedAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.teamSkill.skill')" for="team-skill-skill">Skill</label>
            <select class="form-control" id="team-skill-skill" data-cy="skill" name="skill" v-model="teamSkill.skill" required>
              <option v-if="!teamSkill.skill" v-bind:value="null" selected></option>
              <option
                v-bind:value="teamSkill.skill && skillOption.id === teamSkill.skill.id ? teamSkill.skill : skillOption"
                v-for="skillOption in skills"
                :key="skillOption.id"
              >
                {{ skillOption.title }}
              </option>
            </select>
          </div>
          <div v-if="$v.teamSkill.skill.$anyDirty && $v.teamSkill.skill.$invalid">
            <small class="form-text text-danger" v-if="!$v.teamSkill.skill.required" v-text="$t('entity.validation.required')">
              This field is required.
            </small>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.teamSkill.team')" for="team-skill-team">Team</label>
            <select class="form-control" id="team-skill-team" data-cy="team" name="team" v-model="teamSkill.team" required>
              <option v-if="!teamSkill.team" v-bind:value="null" selected></option>
              <option
                v-bind:value="teamSkill.team && teamOption.id === teamSkill.team.id ? teamSkill.team : teamOption"
                v-for="teamOption in teams"
                :key="teamOption.id"
              >
                {{ teamOption.title }}
              </option>
            </select>
          </div>
          <div v-if="$v.teamSkill.team.$anyDirty && $v.teamSkill.team.$invalid">
            <small class="form-text text-danger" v-if="!$v.teamSkill.team.required" v-text="$t('entity.validation.required')">
              This field is required.
            </small>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.teamSkill.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./team-skill-update.component.ts"></script>

// src/main/webapp/app/entities/team-skill/update/team-skill-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import * as dayjs from 'dayjs';
import { DATE_TIME_FORMAT } from 'app/config/input.constants';

import { ITeamSkill, TeamSkill } from '../team-skill.model';
import { TeamSkillService } from '../service/team-skill.service';
import { ISkill } from 'app/entities/skill/skill.model';
import { SkillService } from 'app/entities/skill/service/skill.service';
import { ITeam } from 'app/entities/team/team.model';
import { TeamService } from 'app/entities/team/service/team.service';

@Component({
  selector: 'jhi-team-skill-update',
  templateUrl: './team-skill-update.component.html',
})
export class TeamSkillUpdateComponent implements OnInit {
  isSaving = false;

  skillsSharedCollection: ISkill[] = [];
  teamsSharedCollection: ITeam[] = [];

  editForm = this.fb.group({
    id: [],
    completedAt: [],
    verifiedAt: [],
    irrelevant: [],
    skillStatus: [],
    note: [null, [Validators.maxLength(4096)]],
    vote: [null, [Validators.required]],
    voters: [null, [Validators.maxLength(255)]],
    createdAt: [null, [Validators.required]],
    updatedAt: [null, [Validators.required]],
    skill: [null, Validators.required],
    team: [null, Validators.required],
  });

  constructor(
    protected teamSkillService: TeamSkillService,
    protected skillService: SkillService,
    protected teamService: TeamService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ teamSkill }) => {
      if (teamSkill.id === undefined) {
        const today = dayjs().startOf('day');
        teamSkill.completedAt = today;
        teamSkill.verifiedAt = today;
        teamSkill.createdAt = today;
        teamSkill.updatedAt = today;
      }

      this.updateForm(teamSkill);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const teamSkill = this.createFromForm();
    if (teamSkill.id !== undefined) {
      this.subscribeToSaveResponse(this.teamSkillService.update(teamSkill));
    } else {
      this.subscribeToSaveResponse(this.teamSkillService.create(teamSkill));
    }
  }

  trackSkillById(index: number, item: ISkill): number {
    return item.id!;
  }

  trackTeamById(index: number, item: ITeam): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ITeamSkill>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(teamSkill: ITeamSkill): void {
    this.editForm.patchValue({
      id: teamSkill.id,
      completedAt: teamSkill.completedAt ? teamSkill.completedAt.format(DATE_TIME_FORMAT) : null,
      verifiedAt: teamSkill.verifiedAt ? teamSkill.verifiedAt.format(DATE_TIME_FORMAT) : null,
      irrelevant: teamSkill.irrelevant,
      skillStatus: teamSkill.skillStatus,
      note: teamSkill.note,
      vote: teamSkill.vote,
      voters: teamSkill.voters,
      createdAt: teamSkill.createdAt ? teamSkill.createdAt.format(DATE_TIME_FORMAT) : null,
      updatedAt: teamSkill.updatedAt ? teamSkill.updatedAt.format(DATE_TIME_FORMAT) : null,
      skill: teamSkill.skill,
      team: teamSkill.team,
    });

    this.skillsSharedCollection = this.skillService.addSkillToCollectionIfMissing(this.skillsSharedCollection, teamSkill.skill);
    this.teamsSharedCollection = this.teamService.addTeamToCollectionIfMissing(this.teamsSharedCollection, teamSkill.team);
  }

  protected loadRelationshipsOptions(): void {
    this.skillService
      .query()
      .pipe(map((res: HttpResponse<ISkill[]>) => res.body ?? []))
      .pipe(map((skills: ISkill[]) => this.skillService.addSkillToCollectionIfMissing(skills, this.editForm.get('skill')!.value)))
      .subscribe((skills: ISkill[]) => (this.skillsSharedCollection = skills));

    this.teamService
      .query()
      .pipe(map((res: HttpResponse<ITeam[]>) => res.body ?? []))
      .pipe(map((teams: ITeam[]) => this.teamService.addTeamToCollectionIfMissing(teams, this.editForm.get('team')!.value)))
      .subscribe((teams: ITeam[]) => (this.teamsSharedCollection = teams));
  }

  protected createFromForm(): ITeamSkill {
    return {
      ...new TeamSkill(),
      id: this.editForm.get(['id'])!.value,
      completedAt: this.editForm.get(['completedAt'])!.value
        ? dayjs(this.editForm.get(['completedAt'])!.value, DATE_TIME_FORMAT)
        : undefined,
      verifiedAt: this.editForm.get(['verifiedAt'])!.value ? dayjs(this.editForm.get(['verifiedAt'])!.value, DATE_TIME_FORMAT) : undefined,
      irrelevant: this.editForm.get(['irrelevant'])!.value,
      skillStatus: this.editForm.get(['skillStatus'])!.value,
      note: this.editForm.get(['note'])!.value,
      vote: this.editForm.get(['vote'])!.value,
      voters: this.editForm.get(['voters'])!.value,
      createdAt: this.editForm.get(['createdAt'])!.value ? dayjs(this.editForm.get(['createdAt'])!.value, DATE_TIME_FORMAT) : undefined,
      updatedAt: this.editForm.get(['updatedAt'])!.value ? dayjs(this.editForm.get(['updatedAt'])!.value, DATE_TIME_FORMAT) : undefined,
      skill: this.editForm.get(['skill'])!.value,
      team: this.editForm.get(['team'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-team-skill-heading" data-cy="TeamSkillCreateUpdateHeading" jhiTranslate="teamDojoApp.teamSkill.home.createOrEditLabel">
        Create or edit a Team Skill
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.teamSkill.completedAt" for="field_completedAt">Completed At</label>
          <div class="d-flex">
            <input
              id="field_completedAt"
              data-cy="completedAt"
              type="datetime-local"
              class="form-control"
              name="completedAt"
              formControlName="completedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.teamSkill.verifiedAt" for="field_verifiedAt">Verified At</label>
          <div class="d-flex">
            <input
              id="field_verifiedAt"
              data-cy="verifiedAt"
              type="datetime-local"
              class="form-control"
              name="verifiedAt"
              formControlName="verifiedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.teamSkill.irrelevant" for="field_irrelevant">Irrelevant</label>
          <input
            type="checkbox"
            class="form-check"
            name="irrelevant"
            id="field_irrelevant"
            data-cy="irrelevant"
            formControlName="irrelevant"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.teamSkill.skillStatus" for="field_skillStatus">Skill Status</label>
          <select class="form-control" name="skillStatus" formControlName="skillStatus" id="field_skillStatus" data-cy="skillStatus">
            <option [ngValue]="null">{{ 'teamDojoApp.SkillStatus.null' | translate }}</option>
            <option value="OPEN">{{ 'teamDojoApp.SkillStatus.OPEN' | translate }}</option>
            <option value="ACHIEVED">{{ 'teamDojoApp.SkillStatus.ACHIEVED' | translate }}</option>
            <option value="EXPIRING">{{ 'teamDojoApp.SkillStatus.EXPIRING' | translate }}</option>
            <option value="EXPIRED">{{ 'teamDojoApp.SkillStatus.EXPIRED' | translate }}</option>
            <option value="IRRELEVANT">{{ 'teamDojoApp.SkillStatus.IRRELEVANT' | translate }}</option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.teamSkill.note" for="field_note">Note</label>
          <input type="text" class="form-control" name="note" id="field_note" data-cy="note" formControlName="note" />
          <div *ngIf="editForm.get('note')!.invalid && (editForm.get('note')!.dirty || editForm.get('note')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('note')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 4096 }"
            >
              This field cannot be longer than 4096 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.teamSkill.vote" for="field_vote">Vote</label>
          <input type="number" class="form-control" name="vote" id="field_vote" data-cy="vote" formControlName="vote" />
          <div *ngIf="editForm.get('vote')!.invalid && (editForm.get('vote')!.dirty || editForm.get('vote')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('vote')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small class="form-text text-danger" [hidden]="!editForm.get('vote')?.errors?.number" jhiTranslate="entity.validation.number">
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.teamSkill.voters" for="field_voters">Voters</label>
          <input type="text" class="form-control" name="voters" id="field_voters" data-cy="voters" formControlName="voters" />
          <div *ngIf="editForm.get('voters')!.invalid && (editForm.get('voters')!.dirty || editForm.get('voters')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('voters')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 255 }"
            >
              This field cannot be longer than 255 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.teamSkill.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('createdAt')!.invalid && (editForm.get('createdAt')!.dirty || editForm.get('createdAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('createdAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('createdAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.teamSkill.updatedAt" for="field_updatedAt">Updated At</label>
          <div class="d-flex">
            <input
              id="field_updatedAt"
              data-cy="updatedAt"
              type="datetime-local"
              class="form-control"
              name="updatedAt"
              formControlName="updatedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('updatedAt')!.invalid && (editForm.get('updatedAt')!.dirty || editForm.get('updatedAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('updatedAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('updatedAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.teamSkill.skill" for="field_skill">Skill</label>
          <select class="form-control" id="field_skill" data-cy="skill" name="skill" formControlName="skill">
            <option *ngIf="!editForm.get('skill')!.value" [ngValue]="null" selected></option>
            <option
              [ngValue]="skillOption.id === editForm.get('skill')!.value?.id ? editForm.get('skill')!.value : skillOption"
              *ngFor="let skillOption of skillsSharedCollection; trackBy: trackSkillById"
            >
              {{ skillOption.title }}
            </option>
          </select>
        </div>
        <div *ngIf="editForm.get(['skill'])!.invalid && (editForm.get(['skill'])!.dirty || editForm.get(['skill'])!.touched)">
          <small class="form-text text-danger" *ngIf="editForm.get(['skill'])?.errors?.required" jhiTranslate="entity.validation.required">
            This field is required.
          </small>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.teamSkill.team" for="field_team">Team</label>
          <select class="form-control" id="field_team" data-cy="team" name="team" formControlName="team">
            <option *ngIf="!editForm.get('team')!.value" [ngValue]="null" selected></option>
            <option
              [ngValue]="teamOption.id === editForm.get('team')!.value?.id ? editForm.get('team')!.value : teamOption"
              *ngFor="let teamOption of teamsSharedCollection; trackBy: trackTeamById"
            >
              {{ teamOption.title }}
            </option>
          </select>
        </div>
        <div *ngIf="editForm.get(['team'])!.invalid && (editForm.get(['team'])!.dirty || editForm.get(['team'])!.touched)">
          <small class="form-text text-danger" *ngIf="editForm.get(['team'])?.errors?.required" jhiTranslate="entity.validation.required">
            This field is required.
          </small>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
