// src/main/webapp/app/entities/level-skill/list/level-skill.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ILevelSkill } from '../level-skill.model';

import { ITEMS_PER_PAGE } from 'app/config/pagination.constants';
import { LevelSkillService } from '../service/level-skill.service';
import { LevelSkillDeleteDialogComponent } from '../delete/level-skill-delete-dialog.component';
import { ParseLinks } from 'app/core/util/parse-links.service';

@Component({
  selector: 'jhi-level-skill',
  templateUrl: './level-skill.component.html',
})
export class LevelSkillComponent implements OnInit {
  levelSkills: ILevelSkill[];
  isLoading = false;
  itemsPerPage: number;
  links: { [key: string]: number };
  page: number;
  predicate: string;
  ascending: boolean;

  constructor(protected levelSkillService: LevelSkillService, protected modalService: NgbModal, protected parseLinks: ParseLinks) {
    this.levelSkills = [];
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.page = 0;
    this.links = {
      last: 0,
    };
    this.predicate = 'id';
    this.ascending = true;
  }

  loadAll(): void {
    this.isLoading = true;

    this.levelSkillService
      .query({
        page: this.page,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<ILevelSkill[]>) => {
          this.isLoading = false;
          this.paginateLevelSkills(res.body, res.headers);
        },
        () => {
          this.isLoading = false;
        }
      );
  }

  reset(): void {
    this.page = 0;
    this.levelSkills = [];
    this.loadAll();
  }

  loadPage(page: number): void {
    this.page = page;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: ILevelSkill): number {
    return item.id!;
  }

  delete(levelSkill: ILevelSkill): void {
    const modalRef = this.modalService.open(LevelSkillDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.levelSkill = levelSkill;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.reset();
      }
    });
  }

  protected sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateLevelSkills(data: ILevelSkill[] | null, headers: HttpHeaders): void {
    this.links = this.parseLinks.parse(headers.get('link') ?? '');
    if (data) {
      for (const d of data) {
        this.levelSkills.push(d);
      }
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="LevelSkillHeading">
    <span jhiTranslate="teamDojoApp.levelSkill.home.title">Level Skills</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="reset()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="teamDojoApp.levelSkill.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-level-skill"
        [routerLink]="['/level-skill/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="teamDojoApp.levelSkill.home.createLabel"> Create a new Level Skill </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="levelSkills?.length === 0">
    <span jhiTranslate="teamDojoApp.levelSkill.home.notFound">No levelSkills found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="levelSkills && levelSkills.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="reset.bind(this)">
          <th scope="col" jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="skill.title">
            <span jhiTranslate="teamDojoApp.levelSkill.skill">Skill</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="level.title">
            <span jhiTranslate="teamDojoApp.levelSkill.level">Level</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
        <tr *ngFor="let levelSkill of levelSkills; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/level-skill', levelSkill.id, 'view']">{{ levelSkill.id }}</a>
          </td>
          <td>
            <div *ngIf="levelSkill.skill">
              <a [routerLink]="['/skill', levelSkill.skill?.id, 'view']">{{ levelSkill.skill?.title }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="levelSkill.level">
              <a [routerLink]="['/level', levelSkill.level?.id, 'view']">{{ levelSkill.level?.title }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/level-skill', levelSkill.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/level-skill', levelSkill.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(levelSkill)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/level-skill/level-skill.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="LevelSkillHeading">
      <span v-text="$t('teamDojoApp.levelSkill.home.title')" id="level-skill-heading">Level Skills</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('teamDojoApp.levelSkill.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'LevelSkillCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-level-skill"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('teamDojoApp.levelSkill.home.createLabel')"> Create a new Level Skill </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && levelSkills && levelSkills.length === 0">
      <span v-text="$t('teamDojoApp.levelSkill.home.notFound')">No levelSkills found</span>
    </div>
    <div class="table-responsive" v-if="levelSkills && levelSkills.length > 0">
      <table class="table table-striped" aria-describedby="levelSkills">
        <thead>
          <tr>
            <th scope="row" v-on:click="changeOrder('id')">
              <span v-text="$t('global.field.id')">ID</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('skill.title')">
              <span v-text="$t('teamDojoApp.levelSkill.skill')">Skill</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'skill.title'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('level.title')">
              <span v-text="$t('teamDojoApp.levelSkill.level')">Level</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'level.title'"></jhi-sort-indicator>
            </th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="levelSkill in levelSkills" :key="levelSkill.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'LevelSkillView', params: { levelSkillId: levelSkill.id } }">{{ levelSkill.id }}</router-link>
            </td>
            <td>
              <div v-if="levelSkill.skill">
                <router-link :to="{ name: 'SkillView', params: { skillId: levelSkill.skill.id } }">{{
                  levelSkill.skill.title
                }}</router-link>
              </div>
            </td>
            <td>
              <div v-if="levelSkill.level">
                <router-link :to="{ name: 'LevelView', params: { levelId: levelSkill.level.id } }">{{
                  levelSkill.level.title
                }}</router-link>
              </div>
            </td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'LevelSkillView', params: { levelSkillId: levelSkill.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'LevelSkillEdit', params: { levelSkillId: levelSkill.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(levelSkill)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
        <infinite-loading
          ref="infiniteLoading"
          v-if="totalItems > itemsPerPage"
          :identifier="infiniteId"
          slot="append"
          @infinite="loadMore"
          force-use-infinite-wrapper=".el-table__body-wrapper"
          :distance="20"
        >
        </infinite-loading>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="teamDojoApp.levelSkill.delete.question" data-cy="levelSkillDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-levelSkill-heading" v-text="$t('teamDojoApp.levelSkill.delete.question', { id: removeId })">
          Are you sure you want to delete this Level Skill?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-levelSkill"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeLevelSkill()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./level-skill.component.ts"></script>
