// src/main/webapp/app/entities/level-skill/update/level-skill-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { ILevelSkill, LevelSkill } from '../level-skill.model';
import { LevelSkillService } from '../service/level-skill.service';
import { ISkill } from 'app/entities/skill/skill.model';
import { SkillService } from 'app/entities/skill/service/skill.service';
import { ILevel } from 'app/entities/level/level.model';
import { LevelService } from 'app/entities/level/service/level.service';

@Component({
  selector: 'jhi-level-skill-update',
  templateUrl: './level-skill-update.component.html',
})
export class LevelSkillUpdateComponent implements OnInit {
  isSaving = false;

  skillsSharedCollection: ISkill[] = [];
  levelsSharedCollection: ILevel[] = [];

  editForm = this.fb.group({
    id: [],
    skill: [null, Validators.required],
    level: [null, Validators.required],
  });

  constructor(
    protected levelSkillService: LevelSkillService,
    protected skillService: SkillService,
    protected levelService: LevelService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ levelSkill }) => {
      this.updateForm(levelSkill);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const levelSkill = this.createFromForm();
    if (levelSkill.id !== undefined) {
      this.subscribeToSaveResponse(this.levelSkillService.update(levelSkill));
    } else {
      this.subscribeToSaveResponse(this.levelSkillService.create(levelSkill));
    }
  }

  trackSkillById(index: number, item: ISkill): number {
    return item.id!;
  }

  trackLevelById(index: number, item: ILevel): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ILevelSkill>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(levelSkill: ILevelSkill): void {
    this.editForm.patchValue({
      id: levelSkill.id,
      skill: levelSkill.skill,
      level: levelSkill.level,
    });

    this.skillsSharedCollection = this.skillService.addSkillToCollectionIfMissing(this.skillsSharedCollection, levelSkill.skill);
    this.levelsSharedCollection = this.levelService.addLevelToCollectionIfMissing(this.levelsSharedCollection, levelSkill.level);
  }

  protected loadRelationshipsOptions(): void {
    this.skillService
      .query()
      .pipe(map((res: HttpResponse<ISkill[]>) => res.body ?? []))
      .pipe(map((skills: ISkill[]) => this.skillService.addSkillToCollectionIfMissing(skills, this.editForm.get('skill')!.value)))
      .subscribe((skills: ISkill[]) => (this.skillsSharedCollection = skills));

    this.levelService
      .query()
      .pipe(map((res: HttpResponse<ILevel[]>) => res.body ?? []))
      .pipe(map((levels: ILevel[]) => this.levelService.addLevelToCollectionIfMissing(levels, this.editForm.get('level')!.value)))
      .subscribe((levels: ILevel[]) => (this.levelsSharedCollection = levels));
  }

  protected createFromForm(): ILevelSkill {
    return {
      ...new LevelSkill(),
      id: this.editForm.get(['id'])!.value,
      skill: this.editForm.get(['skill'])!.value,
      level: this.editForm.get(['level'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-level-skill-heading" data-cy="LevelSkillCreateUpdateHeading" jhiTranslate="teamDojoApp.levelSkill.home.createOrEditLabel">
        Create or edit a Level Skill
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.levelSkill.skill" for="field_skill">Skill</label>
          <select class="form-control" id="field_skill" data-cy="skill" name="skill" formControlName="skill">
            <option *ngIf="!editForm.get('skill')!.value" [ngValue]="null" selected></option>
            <option
              [ngValue]="skillOption.id === editForm.get('skill')!.value?.id ? editForm.get('skill')!.value : skillOption"
              *ngFor="let skillOption of skillsSharedCollection; trackBy: trackSkillById"
            >
              {{ skillOption.title }}
            </option>
          </select>
        </div>
        <div *ngIf="editForm.get(['skill'])!.invalid && (editForm.get(['skill'])!.dirty || editForm.get(['skill'])!.touched)">
          <small class="form-text text-danger" *ngIf="editForm.get(['skill'])?.errors?.required" jhiTranslate="entity.validation.required">
            This field is required.
          </small>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.levelSkill.level" for="field_level">Level</label>
          <select class="form-control" id="field_level" data-cy="level" name="level" formControlName="level">
            <option *ngIf="!editForm.get('level')!.value" [ngValue]="null" selected></option>
            <option
              [ngValue]="levelOption.id === editForm.get('level')!.value?.id ? editForm.get('level')!.value : levelOption"
              *ngFor="let levelOption of levelsSharedCollection; trackBy: trackLevelById"
            >
              {{ levelOption.title }}
            </option>
          </select>
        </div>
        <div *ngIf="editForm.get(['level'])!.invalid && (editForm.get(['level'])!.dirty || editForm.get(['level'])!.touched)">
          <small class="form-text text-danger" *ngIf="editForm.get(['level'])?.errors?.required" jhiTranslate="entity.validation.required">
            This field is required.
          </small>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/level-skill/level-skill-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.levelSkill.home.createOrEditLabel"
          data-cy="LevelSkillCreateUpdateHeading"
          v-text="$t('teamDojoApp.levelSkill.home.createOrEditLabel')"
        >
          Create or edit a LevelSkill
        </h2>
        <div>
          <div class="form-group" v-if="levelSkill.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="levelSkill.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.levelSkill.skill')" for="level-skill-skill">Skill</label>
            <select class="form-control" id="level-skill-skill" data-cy="skill" name="skill" v-model="levelSkill.skill" required>
              <option v-if="!levelSkill.skill" v-bind:value="null" selected></option>
              <option
                v-bind:value="levelSkill.skill && skillOption.id === levelSkill.skill.id ? levelSkill.skill : skillOption"
                v-for="skillOption in skills"
                :key="skillOption.id"
              >
                {{ skillOption.title }}
              </option>
            </select>
          </div>
          <div v-if="$v.levelSkill.skill.$anyDirty && $v.levelSkill.skill.$invalid">
            <small class="form-text text-danger" v-if="!$v.levelSkill.skill.required" v-text="$t('entity.validation.required')">
              This field is required.
            </small>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.levelSkill.level')" for="level-skill-level">Level</label>
            <select class="form-control" id="level-skill-level" data-cy="level" name="level" v-model="levelSkill.level" required>
              <option v-if="!levelSkill.level" v-bind:value="null" selected></option>
              <option
                v-bind:value="levelSkill.level && levelOption.id === levelSkill.level.id ? levelSkill.level : levelOption"
                v-for="levelOption in levels"
                :key="levelOption.id"
              >
                {{ levelOption.title }}
              </option>
            </select>
          </div>
          <div v-if="$v.levelSkill.level.$anyDirty && $v.levelSkill.level.$invalid">
            <small class="form-text text-danger" v-if="!$v.levelSkill.level.required" v-text="$t('entity.validation.required')">
              This field is required.
            </small>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.levelSkill.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./level-skill-update.component.ts"></script>
