// src/main/webapp/app/entities/skill/update/skill-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import dayjs from 'dayjs/esm';
import { DATE_TIME_FORMAT } from 'app/config/input.constants';

import { ISkill, Skill } from '../skill.model';
import { SkillService } from '../service/skill.service';

@Component({
  selector: 'jhi-skill-update',
  templateUrl: './skill-update.component.html',
})
export class SkillUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    title: [null, [Validators.required, Validators.minLength(5), Validators.maxLength(80)]],
    description: [null, [Validators.maxLength(4096)]],
    implementation: [null, [Validators.maxLength(4096)]],
    validation: [null, [Validators.maxLength(4096)]],
    expiryPeriod: [null, [Validators.min(1)]],
    contact: [null, [Validators.maxLength(255)]],
    score: [null, [Validators.required, Validators.min(0)]],
    rateScore: [null, [Validators.min(0), Validators.max(5)]],
    rateCount: [null, [Validators.required, Validators.min(0)]],
    createdAt: [null, [Validators.required]],
    updatedAt: [null, [Validators.required]],
  });

  constructor(protected skillService: SkillService, protected activatedRoute: ActivatedRoute, protected fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ skill }) => {
      if (skill.id === undefined) {
        const today = dayjs().startOf('day');
        skill.createdAt = today;
        skill.updatedAt = today;
      }

      this.updateForm(skill);
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const skill = this.createFromForm();
    if (skill.id !== undefined) {
      this.subscribeToSaveResponse(this.skillService.update(skill));
    } else {
      this.subscribeToSaveResponse(this.skillService.create(skill));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ISkill>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(skill: ISkill): void {
    this.editForm.patchValue({
      id: skill.id,
      title: skill.title,
      description: skill.description,
      implementation: skill.implementation,
      validation: skill.validation,
      expiryPeriod: skill.expiryPeriod,
      contact: skill.contact,
      score: skill.score,
      rateScore: skill.rateScore,
      rateCount: skill.rateCount,
      createdAt: skill.createdAt ? skill.createdAt.format(DATE_TIME_FORMAT) : null,
      updatedAt: skill.updatedAt ? skill.updatedAt.format(DATE_TIME_FORMAT) : null,
    });
  }

  protected createFromForm(): ISkill {
    return {
      ...new Skill(),
      id: this.editForm.get(['id'])!.value,
      title: this.editForm.get(['title'])!.value,
      description: this.editForm.get(['description'])!.value,
      implementation: this.editForm.get(['implementation'])!.value,
      validation: this.editForm.get(['validation'])!.value,
      expiryPeriod: this.editForm.get(['expiryPeriod'])!.value,
      contact: this.editForm.get(['contact'])!.value,
      score: this.editForm.get(['score'])!.value,
      rateScore: this.editForm.get(['rateScore'])!.value,
      rateCount: this.editForm.get(['rateCount'])!.value,
      createdAt: this.editForm.get(['createdAt'])!.value ? dayjs(this.editForm.get(['createdAt'])!.value, DATE_TIME_FORMAT) : undefined,
      updatedAt: this.editForm.get(['updatedAt'])!.value ? dayjs(this.editForm.get(['updatedAt'])!.value, DATE_TIME_FORMAT) : undefined,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-skill-heading" data-cy="SkillCreateUpdateHeading" jhiTranslate="teamDojoApp.skill.home.createOrEditLabel">
        Create or edit a Skill
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.skill.title" for="field_title">Title</label>
          <input type="text" class="form-control" name="title" id="field_title" data-cy="title" formControlName="title" />
          <div *ngIf="editForm.get('title')!.invalid && (editForm.get('title')!.dirty || editForm.get('title')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('title')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 5 }"
            >
              This field is required to be at least 5 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 80 }"
            >
              This field cannot be longer than 80 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.skill.description" for="field_description">Description</label>
          <input
            type="text"
            class="form-control"
            name="description"
            id="field_description"
            data-cy="description"
            formControlName="description"
          />
          <div *ngIf="editForm.get('description')!.invalid && (editForm.get('description')!.dirty || editForm.get('description')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('description')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 4096 }"
            >
              This field cannot be longer than 4096 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.skill.implementation" for="field_implementation"
            >Implementation</label
          >
          <input
            type="text"
            class="form-control"
            name="implementation"
            id="field_implementation"
            data-cy="implementation"
            formControlName="implementation"
          />
          <div
            *ngIf="
              editForm.get('implementation')!.invalid && (editForm.get('implementation')!.dirty || editForm.get('implementation')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('implementation')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 4096 }"
            >
              This field cannot be longer than 4096 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.skill.validation" for="field_validation">Validation</label>
          <input
            type="text"
            class="form-control"
            name="validation"
            id="field_validation"
            data-cy="validation"
            formControlName="validation"
          />
          <div *ngIf="editForm.get('validation')!.invalid && (editForm.get('validation')!.dirty || editForm.get('validation')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('validation')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 4096 }"
            >
              This field cannot be longer than 4096 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.skill.expiryPeriod" for="field_expiryPeriod">Expiry Period</label>
          <input
            type="number"
            class="form-control"
            name="expiryPeriod"
            id="field_expiryPeriod"
            data-cy="expiryPeriod"
            formControlName="expiryPeriod"
          />
          <div
            *ngIf="editForm.get('expiryPeriod')!.invalid && (editForm.get('expiryPeriod')!.dirty || editForm.get('expiryPeriod')!.touched)"
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('expiryPeriod')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 1 }"
            >
              This field should be at least 1.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('expiryPeriod')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.skill.contact" for="field_contact">Contact</label>
          <input type="text" class="form-control" name="contact" id="field_contact" data-cy="contact" formControlName="contact" />
          <div *ngIf="editForm.get('contact')!.invalid && (editForm.get('contact')!.dirty || editForm.get('contact')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('contact')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 255 }"
            >
              This field cannot be longer than 255 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.skill.score" for="field_score">Score</label>
          <input type="number" class="form-control" name="score" id="field_score" data-cy="score" formControlName="score" />
          <div *ngIf="editForm.get('score')!.invalid && (editForm.get('score')!.dirty || editForm.get('score')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('score')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('score')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 0 }"
            >
              This field should be at least 0.
            </small>
            <small class="form-text text-danger" [hidden]="!editForm.get('score')?.errors?.number" jhiTranslate="entity.validation.number">
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.skill.rateScore" for="field_rateScore">Rate Score</label>
          <input type="number" class="form-control" name="rateScore" id="field_rateScore" data-cy="rateScore" formControlName="rateScore" />
          <div *ngIf="editForm.get('rateScore')!.invalid && (editForm.get('rateScore')!.dirty || editForm.get('rateScore')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('rateScore')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 0 }"
            >
              This field should be at least 0.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('rateScore')?.errors?.max"
              jhiTranslate="entity.validation.max"
              [translateValues]="{ max: 5 }"
            >
              This field cannot be more than 5.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('rateScore')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.skill.rateCount" for="field_rateCount">Rate Count</label>
          <input type="number" class="form-control" name="rateCount" id="field_rateCount" data-cy="rateCount" formControlName="rateCount" />
          <div *ngIf="editForm.get('rateCount')!.invalid && (editForm.get('rateCount')!.dirty || editForm.get('rateCount')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('rateCount')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('rateCount')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 0 }"
            >
              This field should be at least 0.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('rateCount')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.skill.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('createdAt')!.invalid && (editForm.get('createdAt')!.dirty || editForm.get('createdAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('createdAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('createdAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.skill.updatedAt" for="field_updatedAt">Updated At</label>
          <div class="d-flex">
            <input
              id="field_updatedAt"
              data-cy="updatedAt"
              type="datetime-local"
              class="form-control"
              name="updatedAt"
              formControlName="updatedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('updatedAt')!.invalid && (editForm.get('updatedAt')!.dirty || editForm.get('updatedAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('updatedAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('updatedAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/skill/skill-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.skill.home.createOrEditLabel"
          data-cy="SkillCreateUpdateHeading"
          v-text="$t('teamDojoApp.skill.home.createOrEditLabel')"
        >
          Create or edit a Skill
        </h2>
        <div>
          <div class="form-group" v-if="skill.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="skill.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.skill.title')" for="skill-title">Title</label>
            <input
              type="text"
              class="form-control"
              name="title"
              id="skill-title"
              data-cy="title"
              :class="{ valid: !$v.skill.title.$invalid, invalid: $v.skill.title.$invalid }"
              v-model="$v.skill.title.$model"
              required
            />
            <div v-if="$v.skill.title.$anyDirty && $v.skill.title.$invalid">
              <small class="form-text text-danger" v-if="!$v.skill.title.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.skill.title.minLength" v-text="$t('entity.validation.minlength', { min: 5 })">
                This field is required to be at least 5 characters.
              </small>
              <small class="form-text text-danger" v-if="!$v.skill.title.maxLength" v-text="$t('entity.validation.maxlength', { max: 80 })">
                This field cannot be longer than 80 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.skill.description')" for="skill-description">Description</label>
            <input
              type="text"
              class="form-control"
              name="description"
              id="skill-description"
              data-cy="description"
              :class="{ valid: !$v.skill.description.$invalid, invalid: $v.skill.description.$invalid }"
              v-model="$v.skill.description.$model"
            />
            <div v-if="$v.skill.description.$anyDirty && $v.skill.description.$invalid">
              <small
                class="form-text text-danger"
                v-if="!$v.skill.description.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 4096 })"
              >
                This field cannot be longer than 4096 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.skill.implementation')" for="skill-implementation"
              >Implementation</label
            >
            <input
              type="text"
              class="form-control"
              name="implementation"
              id="skill-implementation"
              data-cy="implementation"
              :class="{ valid: !$v.skill.implementation.$invalid, invalid: $v.skill.implementation.$invalid }"
              v-model="$v.skill.implementation.$model"
            />
            <div v-if="$v.skill.implementation.$anyDirty && $v.skill.implementation.$invalid">
              <small
                class="form-text text-danger"
                v-if="!$v.skill.implementation.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 4096 })"
              >
                This field cannot be longer than 4096 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.skill.validation')" for="skill-validation">Validation</label>
            <input
              type="text"
              class="form-control"
              name="validation"
              id="skill-validation"
              data-cy="validation"
              :class="{ valid: !$v.skill.validation.$invalid, invalid: $v.skill.validation.$invalid }"
              v-model="$v.skill.validation.$model"
            />
            <div v-if="$v.skill.validation.$anyDirty && $v.skill.validation.$invalid">
              <small
                class="form-text text-danger"
                v-if="!$v.skill.validation.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 4096 })"
              >
                This field cannot be longer than 4096 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.skill.expiryPeriod')" for="skill-expiryPeriod">Expiry Period</label>
            <input
              type="number"
              class="form-control"
              name="expiryPeriod"
              id="skill-expiryPeriod"
              data-cy="expiryPeriod"
              :class="{ valid: !$v.skill.expiryPeriod.$invalid, invalid: $v.skill.expiryPeriod.$invalid }"
              v-model.number="$v.skill.expiryPeriod.$model"
            />
            <div v-if="$v.skill.expiryPeriod.$anyDirty && $v.skill.expiryPeriod.$invalid">
              <small class="form-text text-danger" v-if="!$v.skill.expiryPeriod.min" v-text="$t('entity.validation.min', { min: 1 })">
                This field should be at least 1.
              </small>
              <small class="form-text text-danger" v-if="!$v.skill.expiryPeriod.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.skill.contact')" for="skill-contact">Contact</label>
            <input
              type="text"
              class="form-control"
              name="contact"
              id="skill-contact"
              data-cy="contact"
              :class="{ valid: !$v.skill.contact.$invalid, invalid: $v.skill.contact.$invalid }"
              v-model="$v.skill.contact.$model"
            />
            <div v-if="$v.skill.contact.$anyDirty && $v.skill.contact.$invalid">
              <small
                class="form-text text-danger"
                v-if="!$v.skill.contact.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 255 })"
              >
                This field cannot be longer than 255 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.skill.score')" for="skill-score">Score</label>
            <input
              type="number"
              class="form-control"
              name="score"
              id="skill-score"
              data-cy="score"
              :class="{ valid: !$v.skill.score.$invalid, invalid: $v.skill.score.$invalid }"
              v-model.number="$v.skill.score.$model"
              required
            />
            <div v-if="$v.skill.score.$anyDirty && $v.skill.score.$invalid">
              <small class="form-text text-danger" v-if="!$v.skill.score.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.skill.score.min" v-text="$t('entity.validation.min', { min: 0 })">
                This field should be at least 0.
              </small>
              <small class="form-text text-danger" v-if="!$v.skill.score.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.skill.rateScore')" for="skill-rateScore">Rate Score</label>
            <input
              type="number"
              class="form-control"
              name="rateScore"
              id="skill-rateScore"
              data-cy="rateScore"
              :class="{ valid: !$v.skill.rateScore.$invalid, invalid: $v.skill.rateScore.$invalid }"
              v-model.number="$v.skill.rateScore.$model"
            />
            <div v-if="$v.skill.rateScore.$anyDirty && $v.skill.rateScore.$invalid">
              <small class="form-text text-danger" v-if="!$v.skill.rateScore.min" v-text="$t('entity.validation.min', { min: 0 })">
                This field should be at least 0.
              </small>
              <small class="form-text text-danger" v-if="!$v.skill.rateScore.max" v-text="$t('entity.validation.max', { max: 5 })">
                This field cannot be longer than 5 characters.
              </small>
              <small class="form-text text-danger" v-if="!$v.skill.rateScore.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.skill.rateCount')" for="skill-rateCount">Rate Count</label>
            <input
              type="number"
              class="form-control"
              name="rateCount"
              id="skill-rateCount"
              data-cy="rateCount"
              :class="{ valid: !$v.skill.rateCount.$invalid, invalid: $v.skill.rateCount.$invalid }"
              v-model.number="$v.skill.rateCount.$model"
              required
            />
            <div v-if="$v.skill.rateCount.$anyDirty && $v.skill.rateCount.$invalid">
              <small class="form-text text-danger" v-if="!$v.skill.rateCount.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.skill.rateCount.min" v-text="$t('entity.validation.min', { min: 0 })">
                This field should be at least 0.
              </small>
              <small class="form-text text-danger" v-if="!$v.skill.rateCount.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.skill.createdAt')" for="skill-createdAt">Created At</label>
            <div class="d-flex">
              <input
                id="skill-createdAt"
                data-cy="createdAt"
                type="datetime-local"
                class="form-control"
                name="createdAt"
                :class="{ valid: !$v.skill.createdAt.$invalid, invalid: $v.skill.createdAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.skill.createdAt.$model)"
                @change="updateInstantField('createdAt', $event)"
              />
            </div>
            <div v-if="$v.skill.createdAt.$anyDirty && $v.skill.createdAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.skill.createdAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.skill.createdAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.skill.updatedAt')" for="skill-updatedAt">Updated At</label>
            <div class="d-flex">
              <input
                id="skill-updatedAt"
                data-cy="updatedAt"
                type="datetime-local"
                class="form-control"
                name="updatedAt"
                :class="{ valid: !$v.skill.updatedAt.$invalid, invalid: $v.skill.updatedAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.skill.updatedAt.$model)"
                @change="updateInstantField('updatedAt', $event)"
              />
            </div>
            <div v-if="$v.skill.updatedAt.$anyDirty && $v.skill.updatedAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.skill.updatedAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.skill.updatedAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.skill.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./skill-update.component.ts"></script>
