// src/main/webapp/app/entities/skill/list/skill.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ISkill } from '../skill.model';

import { ASC, DESC, ITEMS_PER_PAGE } from 'app/config/pagination.constants';
import { SkillService } from '../service/skill.service';
import { SkillDeleteDialogComponent } from '../delete/skill-delete-dialog.component';
import { ParseLinks } from 'app/core/util/parse-links.service';

@Component({
  selector: 'jhi-skill',
  templateUrl: './skill.component.html',
})
export class SkillComponent implements OnInit {
  skills: ISkill[];
  isLoading = false;
  itemsPerPage: number;
  links: { [key: string]: number };
  page: number;
  predicate: string;
  ascending: boolean;

  constructor(protected skillService: SkillService, protected modalService: NgbModal, protected parseLinks: ParseLinks) {
    this.skills = [];
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.page = 0;
    this.links = {
      last: 0,
    };
    this.predicate = 'id';
    this.ascending = true;
  }

  loadAll(): void {
    this.isLoading = true;

    this.skillService
      .query({
        page: this.page,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe({
        next: (res: HttpResponse<ISkill[]>) => {
          this.isLoading = false;
          this.paginateSkills(res.body, res.headers);
        },
        error: () => {
          this.isLoading = false;
        },
      });
  }

  reset(): void {
    this.page = 0;
    this.skills = [];
    this.loadAll();
  }

  loadPage(page: number): void {
    this.page = page;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: ISkill): number {
    return item.id!;
  }

  delete(skill: ISkill): void {
    const modalRef = this.modalService.open(SkillDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.skill = skill;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.reset();
      }
    });
  }

  protected sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? ASC : DESC)];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateSkills(data: ISkill[] | null, headers: HttpHeaders): void {
    const linkHeader = headers.get('link');
    if (linkHeader) {
      this.links = this.parseLinks.parse(linkHeader);
    } else {
      this.links = {
        last: 0,
      };
    }
    if (data) {
      for (const d of data) {
        this.skills.push(d);
      }
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="SkillHeading">
    <span jhiTranslate="teamDojoApp.skill.home.title">Skills</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="reset()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="teamDojoApp.skill.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-skill"
        [routerLink]="['/skill/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="teamDojoApp.skill.home.createLabel"> Create a new Skill </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="skills?.length === 0">
    <span jhiTranslate="teamDojoApp.skill.home.notFound">No skills found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="skills && skills.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="reset()">
          <th scope="col" jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="title"><span jhiTranslate="teamDojoApp.skill.title">Title</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="description">
            <span jhiTranslate="teamDojoApp.skill.description">Description</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="implementation">
            <span jhiTranslate="teamDojoApp.skill.implementation">Implementation</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="validation">
            <span jhiTranslate="teamDojoApp.skill.validation">Validation</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="expiryPeriod">
            <span jhiTranslate="teamDojoApp.skill.expiryPeriod">Expiry Period</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="contact">
            <span jhiTranslate="teamDojoApp.skill.contact">Contact</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="score"><span jhiTranslate="teamDojoApp.skill.score">Score</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="rateScore">
            <span jhiTranslate="teamDojoApp.skill.rateScore">Rate Score</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="rateCount">
            <span jhiTranslate="teamDojoApp.skill.rateCount">Rate Count</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="createdAt">
            <span jhiTranslate="teamDojoApp.skill.createdAt">Created At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="updatedAt">
            <span jhiTranslate="teamDojoApp.skill.updatedAt">Updated At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
        <tr *ngFor="let skill of skills; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/skill', skill.id, 'view']">{{ skill.id }}</a>
          </td>
          <td>{{ skill.title }}</td>
          <td>{{ skill.description }}</td>
          <td>{{ skill.implementation }}</td>
          <td>{{ skill.validation }}</td>
          <td>{{ skill.expiryPeriod }}</td>
          <td>{{ skill.contact }}</td>
          <td>{{ skill.score }}</td>
          <td>{{ skill.rateScore }}</td>
          <td>{{ skill.rateCount }}</td>
          <td>{{ skill.createdAt | formatMediumDatetime }}</td>
          <td>{{ skill.updatedAt | formatMediumDatetime }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/skill', skill.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/skill', skill.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(skill)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/skill/skill.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="SkillHeading">
      <span v-text="$t('teamDojoApp.skill.home.title')" id="skill-heading">Skills</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('teamDojoApp.skill.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'SkillCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-skill"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('teamDojoApp.skill.home.createLabel')"> Create a new Skill </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && skills && skills.length === 0">
      <span v-text="$t('teamDojoApp.skill.home.notFound')">No skills found</span>
    </div>
    <div class="table-responsive" v-if="skills && skills.length > 0">
      <table class="table table-striped" aria-describedby="skills">
        <thead>
          <tr>
            <th scope="row" v-on:click="changeOrder('id')">
              <span v-text="$t('global.field.id')">ID</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('title')">
              <span v-text="$t('teamDojoApp.skill.title')">Title</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'title'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('description')">
              <span v-text="$t('teamDojoApp.skill.description')">Description</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'description'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('implementation')">
              <span v-text="$t('teamDojoApp.skill.implementation')">Implementation</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'implementation'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('validation')">
              <span v-text="$t('teamDojoApp.skill.validation')">Validation</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'validation'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('expiryPeriod')">
              <span v-text="$t('teamDojoApp.skill.expiryPeriod')">Expiry Period</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'expiryPeriod'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('contact')">
              <span v-text="$t('teamDojoApp.skill.contact')">Contact</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'contact'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('score')">
              <span v-text="$t('teamDojoApp.skill.score')">Score</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'score'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('rateScore')">
              <span v-text="$t('teamDojoApp.skill.rateScore')">Rate Score</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'rateScore'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('rateCount')">
              <span v-text="$t('teamDojoApp.skill.rateCount')">Rate Count</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'rateCount'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('createdAt')">
              <span v-text="$t('teamDojoApp.skill.createdAt')">Created At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'createdAt'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('updatedAt')">
              <span v-text="$t('teamDojoApp.skill.updatedAt')">Updated At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'updatedAt'"></jhi-sort-indicator>
            </th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="skill in skills" :key="skill.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'SkillView', params: { skillId: skill.id } }">{{ skill.id }}</router-link>
            </td>
            <td>{{ skill.title }}</td>
            <td>{{ skill.description }}</td>
            <td>{{ skill.implementation }}</td>
            <td>{{ skill.validation }}</td>
            <td>{{ skill.expiryPeriod }}</td>
            <td>{{ skill.contact }}</td>
            <td>{{ skill.score }}</td>
            <td>{{ skill.rateScore }}</td>
            <td>{{ skill.rateCount }}</td>
            <td>{{ skill.createdAt ? $d(Date.parse(skill.createdAt), 'short') : '' }}</td>
            <td>{{ skill.updatedAt ? $d(Date.parse(skill.updatedAt), 'short') : '' }}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'SkillView', params: { skillId: skill.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'SkillEdit', params: { skillId: skill.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(skill)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
        <infinite-loading
          ref="infiniteLoading"
          v-if="totalItems > itemsPerPage"
          :identifier="infiniteId"
          slot="append"
          @infinite="loadMore"
          force-use-infinite-wrapper=".el-table__body-wrapper"
          :distance="20"
        >
        </infinite-loading>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="teamDojoApp.skill.delete.question" data-cy="skillDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-skill-heading" v-text="$t('teamDojoApp.skill.delete.question', { id: removeId })">
          Are you sure you want to delete this Skill?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-skill"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeSkill()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./skill.component.ts"></script>
