// src/main/webapp/app/entities/organisation/organisation-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.organisation.home.createOrEditLabel"
          data-cy="OrganisationCreateUpdateHeading"
          v-text="$t('teamDojoApp.organisation.home.createOrEditLabel')"
        >
          Create or edit a Organisation
        </h2>
        <div>
          <div class="form-group" v-if="organisation.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="organisation.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.organisation.title')" for="organisation-title">Title</label>
            <input
              type="text"
              class="form-control"
              name="title"
              id="organisation-title"
              data-cy="title"
              :class="{ valid: !$v.organisation.title.$invalid, invalid: $v.organisation.title.$invalid }"
              v-model="$v.organisation.title.$model"
              required
            />
            <div v-if="$v.organisation.title.$anyDirty && $v.organisation.title.$invalid">
              <small class="form-text text-danger" v-if="!$v.organisation.title.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.organisation.title.minLength"
                v-text="$t('entity.validation.minlength', { min: 1 })"
              >
                This field is required to be at least 1 characters.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.organisation.title.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 50 })"
              >
                This field cannot be longer than 50 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.organisation.description')" for="organisation-description"
              >Description</label
            >
            <input
              type="text"
              class="form-control"
              name="description"
              id="organisation-description"
              data-cy="description"
              :class="{ valid: !$v.organisation.description.$invalid, invalid: $v.organisation.description.$invalid }"
              v-model="$v.organisation.description.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.organisation.levelUpScore')" for="organisation-levelUpScore"
              >Level Up Score</label
            >
            <input
              type="number"
              class="form-control"
              name="levelUpScore"
              id="organisation-levelUpScore"
              data-cy="levelUpScore"
              :class="{ valid: !$v.organisation.levelUpScore.$invalid, invalid: $v.organisation.levelUpScore.$invalid }"
              v-model.number="$v.organisation.levelUpScore.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.organisation.applicationMode')" for="organisation-applicationMode"
              >Application Mode</label
            >
            <select
              class="form-control"
              name="applicationMode"
              :class="{ valid: !$v.organisation.applicationMode.$invalid, invalid: $v.organisation.applicationMode.$invalid }"
              v-model="$v.organisation.applicationMode.$model"
              id="organisation-applicationMode"
              data-cy="applicationMode"
              required
            >
              <option value="PERSON" v-bind:label="$t('teamDojoApp.ApplicationMode.PERSON')">PERSON</option>
              <option value="TEAM" v-bind:label="$t('teamDojoApp.ApplicationMode.TEAM')">TEAM</option>
            </select>
            <div v-if="$v.organisation.applicationMode.$anyDirty && $v.organisation.applicationMode.$invalid">
              <small
                class="form-text text-danger"
                v-if="!$v.organisation.applicationMode.required"
                v-text="$t('entity.validation.required')"
              >
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="$t('teamDojoApp.organisation.countOfConfirmations')"
              for="organisation-countOfConfirmations"
              >Count Of Confirmations</label
            >
            <input
              type="number"
              class="form-control"
              name="countOfConfirmations"
              id="organisation-countOfConfirmations"
              data-cy="countOfConfirmations"
              :class="{ valid: !$v.organisation.countOfConfirmations.$invalid, invalid: $v.organisation.countOfConfirmations.$invalid }"
              v-model.number="$v.organisation.countOfConfirmations.$model"
            />
            <div v-if="$v.organisation.countOfConfirmations.$anyDirty && $v.organisation.countOfConfirmations.$invalid">
              <small
                class="form-text text-danger"
                v-if="!$v.organisation.countOfConfirmations.min"
                v-text="$t('entity.validation.min', { min: 0 })"
              >
                This field should be at least 0.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.organisation.countOfConfirmations.numeric"
                v-text="$t('entity.validation.number')"
              >
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.organisation.createdAt')" for="organisation-createdAt"
              >Created At</label
            >
            <div class="d-flex">
              <input
                id="organisation-createdAt"
                data-cy="createdAt"
                type="datetime-local"
                class="form-control"
                name="createdAt"
                :class="{ valid: !$v.organisation.createdAt.$invalid, invalid: $v.organisation.createdAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.organisation.createdAt.$model)"
                @change="updateInstantField('createdAt', $event)"
              />
            </div>
            <div v-if="$v.organisation.createdAt.$anyDirty && $v.organisation.createdAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.organisation.createdAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.organisation.createdAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.organisation.updatedAt')" for="organisation-updatedAt"
              >Updated At</label
            >
            <div class="d-flex">
              <input
                id="organisation-updatedAt"
                data-cy="updatedAt"
                type="datetime-local"
                class="form-control"
                name="updatedAt"
                :class="{ valid: !$v.organisation.updatedAt.$invalid, invalid: $v.organisation.updatedAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.organisation.updatedAt.$model)"
                @change="updateInstantField('updatedAt', $event)"
              />
            </div>
            <div v-if="$v.organisation.updatedAt.$anyDirty && $v.organisation.updatedAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.organisation.updatedAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.organisation.updatedAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.organisation.parent')" for="organisation-parent">Parent</label>
            <select class="form-control" id="organisation-parent" data-cy="parent" name="parent" v-model="organisation.parent">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="
                  organisation.parent && organisationOption.id === organisation.parent.id ? organisation.parent : organisationOption
                "
                v-for="organisationOption in organisations"
                :key="organisationOption.id"
              >
                {{ organisationOption.id }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.organisation.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./organisation-update.component.ts"></script>

// src/main/webapp/app/entities/organisation/update/organisation-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import * as dayjs from 'dayjs';
import { DATE_TIME_FORMAT } from 'app/config/input.constants';

import { IOrganisation, Organisation } from '../organisation.model';
import { OrganisationService } from '../service/organisation.service';

@Component({
  selector: 'jhi-organisation-update',
  templateUrl: './organisation-update.component.html',
})
export class OrganisationUpdateComponent implements OnInit {
  isSaving = false;

  organisationsSharedCollection: IOrganisation[] = [];

  editForm = this.fb.group({
    id: [],
    title: [null, [Validators.required, Validators.minLength(1), Validators.maxLength(50)]],
    description: [],
    levelUpScore: [],
    applicationMode: [null, [Validators.required]],
    countOfConfirmations: [null, [Validators.min(0)]],
    createdAt: [null, [Validators.required]],
    updatedAt: [null, [Validators.required]],
    parent: [],
  });

  constructor(protected organisationService: OrganisationService, protected activatedRoute: ActivatedRoute, protected fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ organisation }) => {
      if (organisation.id === undefined) {
        const today = dayjs().startOf('day');
        organisation.createdAt = today;
        organisation.updatedAt = today;
      }

      this.updateForm(organisation);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const organisation = this.createFromForm();
    if (organisation.id !== undefined) {
      this.subscribeToSaveResponse(this.organisationService.update(organisation));
    } else {
      this.subscribeToSaveResponse(this.organisationService.create(organisation));
    }
  }

  trackOrganisationById(index: number, item: IOrganisation): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IOrganisation>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(organisation: IOrganisation): void {
    this.editForm.patchValue({
      id: organisation.id,
      title: organisation.title,
      description: organisation.description,
      levelUpScore: organisation.levelUpScore,
      applicationMode: organisation.applicationMode,
      countOfConfirmations: organisation.countOfConfirmations,
      createdAt: organisation.createdAt ? organisation.createdAt.format(DATE_TIME_FORMAT) : null,
      updatedAt: organisation.updatedAt ? organisation.updatedAt.format(DATE_TIME_FORMAT) : null,
      parent: organisation.parent,
    });

    this.organisationsSharedCollection = this.organisationService.addOrganisationToCollectionIfMissing(
      this.organisationsSharedCollection,
      organisation.parent
    );
  }

  protected loadRelationshipsOptions(): void {
    this.organisationService
      .query()
      .pipe(map((res: HttpResponse<IOrganisation[]>) => res.body ?? []))
      .pipe(
        map((organisations: IOrganisation[]) =>
          this.organisationService.addOrganisationToCollectionIfMissing(organisations, this.editForm.get('parent')!.value)
        )
      )
      .subscribe((organisations: IOrganisation[]) => (this.organisationsSharedCollection = organisations));
  }

  protected createFromForm(): IOrganisation {
    return {
      ...new Organisation(),
      id: this.editForm.get(['id'])!.value,
      title: this.editForm.get(['title'])!.value,
      description: this.editForm.get(['description'])!.value,
      levelUpScore: this.editForm.get(['levelUpScore'])!.value,
      applicationMode: this.editForm.get(['applicationMode'])!.value,
      countOfConfirmations: this.editForm.get(['countOfConfirmations'])!.value,
      createdAt: this.editForm.get(['createdAt'])!.value ? dayjs(this.editForm.get(['createdAt'])!.value, DATE_TIME_FORMAT) : undefined,
      updatedAt: this.editForm.get(['updatedAt'])!.value ? dayjs(this.editForm.get(['updatedAt'])!.value, DATE_TIME_FORMAT) : undefined,
      parent: this.editForm.get(['parent'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-organisation-heading"
        data-cy="OrganisationCreateUpdateHeading"
        jhiTranslate="teamDojoApp.organisation.home.createOrEditLabel"
      >
        Create or edit a Organisation
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.organisation.title" for="field_title">Title</label>
          <input type="text" class="form-control" name="title" id="field_title" data-cy="title" formControlName="title" />
          <div *ngIf="editForm.get('title')!.invalid && (editForm.get('title')!.dirty || editForm.get('title')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('title')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 1 }"
            >
              This field is required to be at least 1 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 50 }"
            >
              This field cannot be longer than 50 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.organisation.description" for="field_description">Description</label>
          <input
            type="text"
            class="form-control"
            name="description"
            id="field_description"
            data-cy="description"
            formControlName="description"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.organisation.levelUpScore" for="field_levelUpScore"
            >Level Up Score</label
          >
          <input
            type="number"
            class="form-control"
            name="levelUpScore"
            id="field_levelUpScore"
            data-cy="levelUpScore"
            formControlName="levelUpScore"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.organisation.applicationMode" for="field_applicationMode"
            >Application Mode</label
          >
          <select
            class="form-control"
            name="applicationMode"
            formControlName="applicationMode"
            id="field_applicationMode"
            data-cy="applicationMode"
          >
            <option [ngValue]="null">{{ 'teamDojoApp.ApplicationMode.null' | translate }}</option>
            <option value="PERSON">{{ 'teamDojoApp.ApplicationMode.PERSON' | translate }}</option>
            <option value="TEAM">{{ 'teamDojoApp.ApplicationMode.TEAM' | translate }}</option>
          </select>
          <div
            *ngIf="
              editForm.get('applicationMode')!.invalid &&
              (editForm.get('applicationMode')!.dirty || editForm.get('applicationMode')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('applicationMode')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.organisation.countOfConfirmations" for="field_countOfConfirmations"
            >Count Of Confirmations</label
          >
          <input
            type="number"
            class="form-control"
            name="countOfConfirmations"
            id="field_countOfConfirmations"
            data-cy="countOfConfirmations"
            formControlName="countOfConfirmations"
          />
          <div
            *ngIf="
              editForm.get('countOfConfirmations')!.invalid &&
              (editForm.get('countOfConfirmations')!.dirty || editForm.get('countOfConfirmations')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('countOfConfirmations')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 0 }"
            >
              This field should be at least 0.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('countOfConfirmations')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.organisation.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('createdAt')!.invalid && (editForm.get('createdAt')!.dirty || editForm.get('createdAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('createdAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('createdAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.organisation.updatedAt" for="field_updatedAt">Updated At</label>
          <div class="d-flex">
            <input
              id="field_updatedAt"
              data-cy="updatedAt"
              type="datetime-local"
              class="form-control"
              name="updatedAt"
              formControlName="updatedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('updatedAt')!.invalid && (editForm.get('updatedAt')!.dirty || editForm.get('updatedAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('updatedAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('updatedAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.organisation.parent" for="field_parent">Parent</label>
          <select class="form-control" id="field_parent" data-cy="parent" name="parent" formControlName="parent">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="organisationOption.id === editForm.get('parent')!.value?.id ? editForm.get('parent')!.value : organisationOption"
              *ngFor="let organisationOption of organisationsSharedCollection; trackBy: trackOrganisationById"
            >
              {{ organisationOption.id }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
