// src/main/webapp/app/entities/image/list/image.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IImage } from '../image.model';

import { ASC, DESC, ITEMS_PER_PAGE } from 'app/config/pagination.constants';
import { ImageService } from '../service/image.service';
import { ImageDeleteDialogComponent } from '../delete/image-delete-dialog.component';
import { DataUtils } from 'app/core/util/data-util.service';
import { ParseLinks } from 'app/core/util/parse-links.service';

@Component({
  selector: 'jhi-image',
  templateUrl: './image.component.html',
})
export class ImageComponent implements OnInit {
  images: IImage[];
  isLoading = false;
  itemsPerPage: number;
  links: { [key: string]: number };
  page: number;
  predicate: string;
  ascending: boolean;

  constructor(
    protected imageService: ImageService,
    protected dataUtils: DataUtils,
    protected modalService: NgbModal,
    protected parseLinks: ParseLinks
  ) {
    this.images = [];
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.page = 0;
    this.links = {
      last: 0,
    };
    this.predicate = 'id';
    this.ascending = true;
  }

  loadAll(): void {
    this.isLoading = true;

    this.imageService
      .query({
        page: this.page,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe({
        next: (res: HttpResponse<IImage[]>) => {
          this.isLoading = false;
          this.paginateImages(res.body, res.headers);
        },
        error: () => {
          this.isLoading = false;
        },
      });
  }

  reset(): void {
    this.page = 0;
    this.images = [];
    this.loadAll();
  }

  loadPage(page: number): void {
    this.page = page;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IImage): number {
    return item.id!;
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    return this.dataUtils.openFile(base64String, contentType);
  }

  delete(image: IImage): void {
    const modalRef = this.modalService.open(ImageDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.image = image;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.reset();
      }
    });
  }

  protected sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? ASC : DESC)];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateImages(data: IImage[] | null, headers: HttpHeaders): void {
    const linkHeader = headers.get('link');
    if (linkHeader) {
      this.links = this.parseLinks.parse(linkHeader);
    } else {
      this.links = {
        last: 0,
      };
    }
    if (data) {
      for (const d of data) {
        this.images.push(d);
      }
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="ImageHeading">
    <span jhiTranslate="teamDojoApp.image.home.title">Images</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="reset()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="teamDojoApp.image.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-image"
        [routerLink]="['/image/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="teamDojoApp.image.home.createLabel"> Create a new Image </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="images?.length === 0">
    <span jhiTranslate="teamDojoApp.image.home.notFound">No images found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="images && images.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="reset()">
          <th scope="col" jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="title"><span jhiTranslate="teamDojoApp.image.title">Title</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="small"><span jhiTranslate="teamDojoApp.image.small">Small</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="medium">
            <span jhiTranslate="teamDojoApp.image.medium">Medium</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="large"><span jhiTranslate="teamDojoApp.image.large">Large</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="hash"><span jhiTranslate="teamDojoApp.image.hash">Hash</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="createdAt">
            <span jhiTranslate="teamDojoApp.image.createdAt">Created At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="updatedAt">
            <span jhiTranslate="teamDojoApp.image.updatedAt">Updated At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
        <tr *ngFor="let image of images; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/image', image.id, 'view']">{{ image.id }}</a>
          </td>
          <td>{{ image.title }}</td>
          <td>
            <a *ngIf="image.small" (click)="openFile(image.small, image.smallContentType)">
              <img [src]="'data:' + image.smallContentType + ';base64,' + image.small" style="max-height: 30px" alt="image image" />
            </a>
            <span *ngIf="image.small">{{ image.smallContentType }}, {{ byteSize(image.small) }}</span>
          </td>
          <td>
            <a *ngIf="image.medium" (click)="openFile(image.medium, image.mediumContentType)">
              <img [src]="'data:' + image.mediumContentType + ';base64,' + image.medium" style="max-height: 30px" alt="image image" />
            </a>
            <span *ngIf="image.medium">{{ image.mediumContentType }}, {{ byteSize(image.medium) }}</span>
          </td>
          <td>
            <a *ngIf="image.large" (click)="openFile(image.large, image.largeContentType)">
              <img [src]="'data:' + image.largeContentType + ';base64,' + image.large" style="max-height: 30px" alt="image image" />
            </a>
            <span *ngIf="image.large">{{ image.largeContentType }}, {{ byteSize(image.large) }}</span>
          </td>
          <td>{{ image.hash }}</td>
          <td>{{ image.createdAt | formatMediumDatetime }}</td>
          <td>{{ image.updatedAt | formatMediumDatetime }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/image', image.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/image', image.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(image)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/image/image.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="ImageHeading">
      <span v-text="$t('teamDojoApp.image.home.title')" id="image-heading">Images</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('teamDojoApp.image.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'ImageCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-image"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('teamDojoApp.image.home.createLabel')"> Create a new Image </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && images && images.length === 0">
      <span v-text="$t('teamDojoApp.image.home.notFound')">No images found</span>
    </div>
    <div class="table-responsive" v-if="images && images.length > 0">
      <table class="table table-striped" aria-describedby="images">
        <thead>
          <tr>
            <th scope="row" v-on:click="changeOrder('id')">
              <span v-text="$t('global.field.id')">ID</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('title')">
              <span v-text="$t('teamDojoApp.image.title')">Title</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'title'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('small')">
              <span v-text="$t('teamDojoApp.image.small')">Small</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'small'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('medium')">
              <span v-text="$t('teamDojoApp.image.medium')">Medium</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'medium'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('large')">
              <span v-text="$t('teamDojoApp.image.large')">Large</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'large'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('hash')">
              <span v-text="$t('teamDojoApp.image.hash')">Hash</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'hash'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('createdAt')">
              <span v-text="$t('teamDojoApp.image.createdAt')">Created At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'createdAt'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('updatedAt')">
              <span v-text="$t('teamDojoApp.image.updatedAt')">Updated At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'updatedAt'"></jhi-sort-indicator>
            </th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="image in images" :key="image.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'ImageView', params: { imageId: image.id } }">{{ image.id }}</router-link>
            </td>
            <td>{{ image.title }}</td>
            <td>
              <a v-if="image.small" v-on:click="openFile(image.smallContentType, image.small)">
                <img v-bind:src="'data:' + image.smallContentType + ';base64,' + image.small" style="max-height: 30px" alt="image image" />
              </a>
              <span v-if="image.small">{{ image.smallContentType }}, {{ byteSize(image.small) }}</span>
            </td>
            <td>
              <a v-if="image.medium" v-on:click="openFile(image.mediumContentType, image.medium)">
                <img
                  v-bind:src="'data:' + image.mediumContentType + ';base64,' + image.medium"
                  style="max-height: 30px"
                  alt="image image"
                />
              </a>
              <span v-if="image.medium">{{ image.mediumContentType }}, {{ byteSize(image.medium) }}</span>
            </td>
            <td>
              <a v-if="image.large" v-on:click="openFile(image.largeContentType, image.large)">
                <img v-bind:src="'data:' + image.largeContentType + ';base64,' + image.large" style="max-height: 30px" alt="image image" />
              </a>
              <span v-if="image.large">{{ image.largeContentType }}, {{ byteSize(image.large) }}</span>
            </td>
            <td>{{ image.hash }}</td>
            <td>{{ image.createdAt ? $d(Date.parse(image.createdAt), 'short') : '' }}</td>
            <td>{{ image.updatedAt ? $d(Date.parse(image.updatedAt), 'short') : '' }}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'ImageView', params: { imageId: image.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'ImageEdit', params: { imageId: image.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(image)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
        <infinite-loading
          ref="infiniteLoading"
          v-if="totalItems > itemsPerPage"
          :identifier="infiniteId"
          slot="append"
          @infinite="loadMore"
          force-use-infinite-wrapper=".el-table__body-wrapper"
          :distance="20"
        >
        </infinite-loading>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="teamDojoApp.image.delete.question" data-cy="imageDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-image-heading" v-text="$t('teamDojoApp.image.delete.question', { id: removeId })">
          Are you sure you want to delete this Image?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-image"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeImage()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./image.component.ts"></script>
