// src/main/webapp/app/entities/image/update/image-update.component.ts
import { Component, OnInit, ElementRef } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { ImageFormService, ImageFormGroup } from './image-form.service';
import { IImage } from '../image.model';
import { ImageService } from '../service/image.service';
import { AlertError } from 'app/shared/alert/alert-error.model';
import { EventManager, EventWithContent } from 'app/core/util/event-manager.service';
import { DataUtils, FileLoadError } from 'app/core/util/data-util.service';

@Component({
  selector: 'jhi-image-update',
  templateUrl: './image-update.component.html',
})
export class ImageUpdateComponent implements OnInit {
  isSaving = false;
  image: IImage | null = null;

  editForm: ImageFormGroup = this.imageFormService.createImageFormGroup();

  constructor(
    protected dataUtils: DataUtils,
    protected eventManager: EventManager,
    protected imageService: ImageService,
    protected imageFormService: ImageFormService,
    protected elementRef: ElementRef,
    protected activatedRoute: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ image }) => {
      this.image = image;
      if (image) {
        this.updateForm(image);
      }
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  setFileData(event: Event, field: string, isImage: boolean): void {
    this.dataUtils.loadFileToForm(event, this.editForm, field, isImage).subscribe({
      error: (err: FileLoadError) =>
        this.eventManager.broadcast(new EventWithContent<AlertError>('teamDojoApp.error', { ...err, key: 'error.file.' + err.key })),
    });
  }

  clearInputImage(field: string, fieldContentType: string, idInput: string): void {
    this.editForm.patchValue({
      [field]: null,
      [fieldContentType]: null,
    });
    if (idInput && this.elementRef.nativeElement.querySelector('#' + idInput)) {
      this.elementRef.nativeElement.querySelector('#' + idInput).value = null;
    }
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const image = this.imageFormService.getImage(this.editForm);
    if (image.id !== null) {
      this.subscribeToSaveResponse(this.imageService.update(image));
    } else {
      this.subscribeToSaveResponse(this.imageService.create(image));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IImage>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(image: IImage): void {
    this.image = image;
    this.imageFormService.resetForm(this.editForm, image);
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-image-heading" data-cy="ImageCreateUpdateHeading" jhiTranslate="teamDojoApp.image.home.createOrEditLabel">
        Create or edit a Image
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.image.title" for="field_title">Title</label>
          <input type="text" class="form-control" name="title" id="field_title" data-cy="title" formControlName="title" />
          <div *ngIf="editForm.get('title')!.invalid && (editForm.get('title')!.dirty || editForm.get('title')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('title')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 1 }"
            >
              This field is required to be at least 1 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 50 }"
            >
              This field cannot be longer than 50 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.image.small" for="field_small">Small</label>
          <div>
            <img
              [src]="'data:' + editForm.get('smallContentType')!.value + ';base64,' + editForm.get('small')!.value"
              style="max-height: 100px"
              *ngIf="editForm.get('small')!.value"
              alt="image image"
            />
            <div *ngIf="editForm.get('small')!.value" class="form-text text-danger clearfix">
              <span class="pull-left">{{ editForm.get('smallContentType')!.value }}, {{ byteSize(editForm.get('small')!.value) }}</span>
              <button
                type="button"
                (click)="clearInputImage('small', 'smallContentType', 'file_small')"
                class="btn btn-secondary btn-xs pull-right"
              >
                <fa-icon icon="times"></fa-icon>
              </button>
            </div>
            <input
              type="file"
              id="file_small"
              data-cy="small"
              (change)="setFileData($event, 'small', true)"
              accept="image/*"
              jhiTranslate="entity.action.addimage"
            />
          </div>
          <input type="hidden" class="form-control" name="small" id="field_small" data-cy="small" formControlName="small" />
          <input
            type="hidden"
            class="form-control"
            name="smallContentType"
            id="field_smallContentType"
            formControlName="smallContentType"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.image.medium" for="field_medium">Medium</label>
          <div>
            <img
              [src]="'data:' + editForm.get('mediumContentType')!.value + ';base64,' + editForm.get('medium')!.value"
              style="max-height: 100px"
              *ngIf="editForm.get('medium')!.value"
              alt="image image"
            />
            <div *ngIf="editForm.get('medium')!.value" class="form-text text-danger clearfix">
              <span class="pull-left">{{ editForm.get('mediumContentType')!.value }}, {{ byteSize(editForm.get('medium')!.value) }}</span>
              <button
                type="button"
                (click)="clearInputImage('medium', 'mediumContentType', 'file_medium')"
                class="btn btn-secondary btn-xs pull-right"
              >
                <fa-icon icon="times"></fa-icon>
              </button>
            </div>
            <input
              type="file"
              id="file_medium"
              data-cy="medium"
              (change)="setFileData($event, 'medium', true)"
              accept="image/*"
              jhiTranslate="entity.action.addimage"
            />
          </div>
          <input type="hidden" class="form-control" name="medium" id="field_medium" data-cy="medium" formControlName="medium" />
          <input
            type="hidden"
            class="form-control"
            name="mediumContentType"
            id="field_mediumContentType"
            formControlName="mediumContentType"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.image.large" for="field_large">Large</label>
          <div>
            <img
              [src]="'data:' + editForm.get('largeContentType')!.value + ';base64,' + editForm.get('large')!.value"
              style="max-height: 100px"
              *ngIf="editForm.get('large')!.value"
              alt="image image"
            />
            <div *ngIf="editForm.get('large')!.value" class="form-text text-danger clearfix">
              <span class="pull-left">{{ editForm.get('largeContentType')!.value }}, {{ byteSize(editForm.get('large')!.value) }}</span>
              <button
                type="button"
                (click)="clearInputImage('large', 'largeContentType', 'file_large')"
                class="btn btn-secondary btn-xs pull-right"
              >
                <fa-icon icon="times"></fa-icon>
              </button>
            </div>
            <input
              type="file"
              id="file_large"
              data-cy="large"
              (change)="setFileData($event, 'large', true)"
              accept="image/*"
              jhiTranslate="entity.action.addimage"
            />
          </div>
          <input type="hidden" class="form-control" name="large" id="field_large" data-cy="large" formControlName="large" />
          <input
            type="hidden"
            class="form-control"
            name="largeContentType"
            id="field_largeContentType"
            formControlName="largeContentType"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.image.hash" for="field_hash">Hash</label>
          <input type="text" class="form-control" name="hash" id="field_hash" data-cy="hash" formControlName="hash" />
          <div *ngIf="editForm.get('hash')!.invalid && (editForm.get('hash')!.dirty || editForm.get('hash')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('hash')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 32 }"
            >
              This field cannot be longer than 32 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.image.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('createdAt')!.invalid && (editForm.get('createdAt')!.dirty || editForm.get('createdAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('createdAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('createdAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.image.updatedAt" for="field_updatedAt">Updated At</label>
          <div class="d-flex">
            <input
              id="field_updatedAt"
              data-cy="updatedAt"
              type="datetime-local"
              class="form-control"
              name="updatedAt"
              formControlName="updatedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('updatedAt')!.invalid && (editForm.get('updatedAt')!.dirty || editForm.get('updatedAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('updatedAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('updatedAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/image/image-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.image.home.createOrEditLabel"
          data-cy="ImageCreateUpdateHeading"
          v-text="$t('teamDojoApp.image.home.createOrEditLabel')"
        >
          Create or edit a Image
        </h2>
        <div>
          <div class="form-group" v-if="image.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="image.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.image.title')" for="image-title">Title</label>
            <input
              type="text"
              class="form-control"
              name="title"
              id="image-title"
              data-cy="title"
              :class="{ valid: !$v.image.title.$invalid, invalid: $v.image.title.$invalid }"
              v-model="$v.image.title.$model"
              required
            />
            <div v-if="$v.image.title.$anyDirty && $v.image.title.$invalid">
              <small class="form-text text-danger" v-if="!$v.image.title.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.image.title.minLength" v-text="$t('entity.validation.minlength', { min: 1 })">
                This field is required to be at least 1 characters.
              </small>
              <small class="form-text text-danger" v-if="!$v.image.title.maxLength" v-text="$t('entity.validation.maxlength', { max: 50 })">
                This field cannot be longer than 50 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.image.small')" for="image-small">Small</label>
            <div>
              <img
                v-bind:src="'data:' + image.smallContentType + ';base64,' + image.small"
                style="max-height: 100px"
                v-if="image.small"
                alt="image image"
              />
              <div v-if="image.small" class="form-text text-danger clearfix">
                <span class="pull-left">{{ image.smallContentType }}, {{ byteSize(image.small) }}</span>
                <button
                  type="button"
                  v-on:click="clearInputImage('small', 'smallContentType', 'file_small')"
                  class="btn btn-secondary btn-xs pull-right"
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                </button>
              </div>
              <input
                type="file"
                ref="file_small"
                id="file_small"
                data-cy="small"
                v-on:change="setFileData($event, image, 'small', true)"
                accept="image/*"
                v-text="$t('entity.action.addimage')"
              />
            </div>
            <input
              type="hidden"
              class="form-control"
              name="small"
              id="image-small"
              data-cy="small"
              :class="{ valid: !$v.image.small.$invalid, invalid: $v.image.small.$invalid }"
              v-model="$v.image.small.$model"
            />
            <input
              type="hidden"
              class="form-control"
              name="smallContentType"
              id="image-smallContentType"
              v-model="image.smallContentType"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.image.medium')" for="image-medium">Medium</label>
            <div>
              <img
                v-bind:src="'data:' + image.mediumContentType + ';base64,' + image.medium"
                style="max-height: 100px"
                v-if="image.medium"
                alt="image image"
              />
              <div v-if="image.medium" class="form-text text-danger clearfix">
                <span class="pull-left">{{ image.mediumContentType }}, {{ byteSize(image.medium) }}</span>
                <button
                  type="button"
                  v-on:click="clearInputImage('medium', 'mediumContentType', 'file_medium')"
                  class="btn btn-secondary btn-xs pull-right"
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                </button>
              </div>
              <input
                type="file"
                ref="file_medium"
                id="file_medium"
                data-cy="medium"
                v-on:change="setFileData($event, image, 'medium', true)"
                accept="image/*"
                v-text="$t('entity.action.addimage')"
              />
            </div>
            <input
              type="hidden"
              class="form-control"
              name="medium"
              id="image-medium"
              data-cy="medium"
              :class="{ valid: !$v.image.medium.$invalid, invalid: $v.image.medium.$invalid }"
              v-model="$v.image.medium.$model"
            />
            <input
              type="hidden"
              class="form-control"
              name="mediumContentType"
              id="image-mediumContentType"
              v-model="image.mediumContentType"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.image.large')" for="image-large">Large</label>
            <div>
              <img
                v-bind:src="'data:' + image.largeContentType + ';base64,' + image.large"
                style="max-height: 100px"
                v-if="image.large"
                alt="image image"
              />
              <div v-if="image.large" class="form-text text-danger clearfix">
                <span class="pull-left">{{ image.largeContentType }}, {{ byteSize(image.large) }}</span>
                <button
                  type="button"
                  v-on:click="clearInputImage('large', 'largeContentType', 'file_large')"
                  class="btn btn-secondary btn-xs pull-right"
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                </button>
              </div>
              <input
                type="file"
                ref="file_large"
                id="file_large"
                data-cy="large"
                v-on:change="setFileData($event, image, 'large', true)"
                accept="image/*"
                v-text="$t('entity.action.addimage')"
              />
            </div>
            <input
              type="hidden"
              class="form-control"
              name="large"
              id="image-large"
              data-cy="large"
              :class="{ valid: !$v.image.large.$invalid, invalid: $v.image.large.$invalid }"
              v-model="$v.image.large.$model"
            />
            <input
              type="hidden"
              class="form-control"
              name="largeContentType"
              id="image-largeContentType"
              v-model="image.largeContentType"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.image.hash')" for="image-hash">Hash</label>
            <input
              type="text"
              class="form-control"
              name="hash"
              id="image-hash"
              data-cy="hash"
              :class="{ valid: !$v.image.hash.$invalid, invalid: $v.image.hash.$invalid }"
              v-model="$v.image.hash.$model"
            />
            <div v-if="$v.image.hash.$anyDirty && $v.image.hash.$invalid">
              <small class="form-text text-danger" v-if="!$v.image.hash.maxLength" v-text="$t('entity.validation.maxlength', { max: 32 })">
                This field cannot be longer than 32 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.image.createdAt')" for="image-createdAt">Created At</label>
            <div class="d-flex">
              <input
                id="image-createdAt"
                data-cy="createdAt"
                type="datetime-local"
                class="form-control"
                name="createdAt"
                :class="{ valid: !$v.image.createdAt.$invalid, invalid: $v.image.createdAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.image.createdAt.$model)"
                @change="updateInstantField('createdAt', $event)"
              />
            </div>
            <div v-if="$v.image.createdAt.$anyDirty && $v.image.createdAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.image.createdAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.image.createdAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.image.updatedAt')" for="image-updatedAt">Updated At</label>
            <div class="d-flex">
              <input
                id="image-updatedAt"
                data-cy="updatedAt"
                type="datetime-local"
                class="form-control"
                name="updatedAt"
                :class="{ valid: !$v.image.updatedAt.$invalid, invalid: $v.image.updatedAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.image.updatedAt.$model)"
                @change="updateInstantField('updatedAt', $event)"
              />
            </div>
            <div v-if="$v.image.updatedAt.$anyDirty && $v.image.updatedAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.image.updatedAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.image.updatedAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.image.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./image-update.component.ts"></script>
