// src/main/webapp/app/entities/level/list/level.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ILevel } from '../level.model';

import { ITEMS_PER_PAGE } from 'app/config/pagination.constants';
import { LevelService } from '../service/level.service';
import { LevelDeleteDialogComponent } from '../delete/level-delete-dialog.component';
import { ParseLinks } from 'app/core/util/parse-links.service';

@Component({
  selector: 'jhi-level',
  templateUrl: './level.component.html',
})
export class LevelComponent implements OnInit {
  levels: ILevel[];
  isLoading = false;
  itemsPerPage: number;
  links: { [key: string]: number };
  page: number;
  predicate: string;
  ascending: boolean;

  constructor(protected levelService: LevelService, protected modalService: NgbModal, protected parseLinks: ParseLinks) {
    this.levels = [];
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.page = 0;
    this.links = {
      last: 0,
    };
    this.predicate = 'id';
    this.ascending = true;
  }

  loadAll(): void {
    this.isLoading = true;

    this.levelService
      .query({
        page: this.page,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<ILevel[]>) => {
          this.isLoading = false;
          this.paginateLevels(res.body, res.headers);
        },
        () => {
          this.isLoading = false;
        }
      );
  }

  reset(): void {
    this.page = 0;
    this.levels = [];
    this.loadAll();
  }

  loadPage(page: number): void {
    this.page = page;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: ILevel): number {
    return item.id!;
  }

  delete(level: ILevel): void {
    const modalRef = this.modalService.open(LevelDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.level = level;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.reset();
      }
    });
  }

  protected sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateLevels(data: ILevel[] | null, headers: HttpHeaders): void {
    this.links = this.parseLinks.parse(headers.get('link') ?? '');
    if (data) {
      for (const d of data) {
        this.levels.push(d);
      }
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="LevelHeading">
    <span jhiTranslate="teamDojoApp.level.home.title">Levels</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="reset()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="teamDojoApp.level.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-level"
        [routerLink]="['/level/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="teamDojoApp.level.home.createLabel"> Create a new Level </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="levels?.length === 0">
    <span jhiTranslate="teamDojoApp.level.home.notFound">No levels found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="levels && levels.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="reset.bind(this)">
          <th scope="col" jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="title"><span jhiTranslate="teamDojoApp.level.title">Title</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="description">
            <span jhiTranslate="teamDojoApp.level.description">Description</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="requiredScore">
            <span jhiTranslate="teamDojoApp.level.requiredScore">Required Score</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="instantMultiplier">
            <span jhiTranslate="teamDojoApp.level.instantMultiplier">Instant Multiplier</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="completionBonus">
            <span jhiTranslate="teamDojoApp.level.completionBonus">Completion Bonus</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="createdAt">
            <span jhiTranslate="teamDojoApp.level.createdAt">Created At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="updatedAt">
            <span jhiTranslate="teamDojoApp.level.updatedAt">Updated At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="dependsOn.title">
            <span jhiTranslate="teamDojoApp.level.dependsOn">Depends On</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="image.title">
            <span jhiTranslate="teamDojoApp.level.image">Image</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="dimension.title">
            <span jhiTranslate="teamDojoApp.level.dimension">Dimension</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
        <tr *ngFor="let level of levels; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/level', level.id, 'view']">{{ level.id }}</a>
          </td>
          <td>{{ level.title }}</td>
          <td>{{ level.description }}</td>
          <td>{{ level.requiredScore }}</td>
          <td>{{ level.instantMultiplier }}</td>
          <td>{{ level.completionBonus }}</td>
          <td>{{ level.createdAt | formatMediumDatetime }}</td>
          <td>{{ level.updatedAt | formatMediumDatetime }}</td>
          <td>
            <div *ngIf="level.dependsOn">
              <a [routerLink]="['/level', level.dependsOn?.id, 'view']">{{ level.dependsOn?.title }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="level.image">
              <a [routerLink]="['/image', level.image?.id, 'view']">{{ level.image?.title }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="level.dimension">
              <a [routerLink]="['/dimension', level.dimension?.id, 'view']">{{ level.dimension?.title }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/level', level.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/level', level.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(level)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/level/level.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="LevelHeading">
      <span v-text="$t('teamDojoApp.level.home.title')" id="level-heading">Levels</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('teamDojoApp.level.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'LevelCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-level"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('teamDojoApp.level.home.createLabel')"> Create a new Level </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && levels && levels.length === 0">
      <span v-text="$t('teamDojoApp.level.home.notFound')">No levels found</span>
    </div>
    <div class="table-responsive" v-if="levels && levels.length > 0">
      <table class="table table-striped" aria-describedby="levels">
        <thead>
          <tr>
            <th scope="row" v-on:click="changeOrder('id')">
              <span v-text="$t('global.field.id')">ID</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('title')">
              <span v-text="$t('teamDojoApp.level.title')">Title</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'title'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('description')">
              <span v-text="$t('teamDojoApp.level.description')">Description</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'description'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('requiredScore')">
              <span v-text="$t('teamDojoApp.level.requiredScore')">Required Score</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'requiredScore'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('instantMultiplier')">
              <span v-text="$t('teamDojoApp.level.instantMultiplier')">Instant Multiplier</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'instantMultiplier'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('completionBonus')">
              <span v-text="$t('teamDojoApp.level.completionBonus')">Completion Bonus</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'completionBonus'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('createdAt')">
              <span v-text="$t('teamDojoApp.level.createdAt')">Created At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'createdAt'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('updatedAt')">
              <span v-text="$t('teamDojoApp.level.updatedAt')">Updated At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'updatedAt'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('dependsOn.title')">
              <span v-text="$t('teamDojoApp.level.dependsOn')">Depends On</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'dependsOn.title'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('image.title')">
              <span v-text="$t('teamDojoApp.level.image')">Image</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'image.title'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('dimension.title')">
              <span v-text="$t('teamDojoApp.level.dimension')">Dimension</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'dimension.title'"></jhi-sort-indicator>
            </th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="level in levels" :key="level.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'LevelView', params: { levelId: level.id } }">{{ level.id }}</router-link>
            </td>
            <td>{{ level.title }}</td>
            <td>{{ level.description }}</td>
            <td>{{ level.requiredScore }}</td>
            <td>{{ level.instantMultiplier }}</td>
            <td>{{ level.completionBonus }}</td>
            <td>{{ level.createdAt ? $d(Date.parse(level.createdAt), 'short') : '' }}</td>
            <td>{{ level.updatedAt ? $d(Date.parse(level.updatedAt), 'short') : '' }}</td>
            <td>
              <div v-if="level.dependsOn">
                <router-link :to="{ name: 'LevelView', params: { levelId: level.dependsOn.id } }">{{ level.dependsOn.title }}</router-link>
              </div>
            </td>
            <td>
              <div v-if="level.image">
                <router-link :to="{ name: 'ImageView', params: { imageId: level.image.id } }">{{ level.image.title }}</router-link>
              </div>
            </td>
            <td>
              <div v-if="level.dimension">
                <router-link :to="{ name: 'DimensionView', params: { dimensionId: level.dimension.id } }">{{
                  level.dimension.title
                }}</router-link>
              </div>
            </td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'LevelView', params: { levelId: level.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'LevelEdit', params: { levelId: level.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(level)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
        <infinite-loading
          ref="infiniteLoading"
          v-if="totalItems > itemsPerPage"
          :identifier="infiniteId"
          slot="append"
          @infinite="loadMore"
          force-use-infinite-wrapper=".el-table__body-wrapper"
          :distance="20"
        >
        </infinite-loading>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="teamDojoApp.level.delete.question" data-cy="levelDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-level-heading" v-text="$t('teamDojoApp.level.delete.question', { id: removeId })">
          Are you sure you want to delete this Level?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-level"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeLevel()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./level.component.ts"></script>
