// src/main/webapp/app/entities/report/update/report-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { ReportFormService, ReportFormGroup } from './report-form.service';
import { IReport } from '../report.model';
import { ReportService } from '../service/report.service';
import { ReportType } from 'app/entities/enumerations/report-type.model';

@Component({
  selector: 'jhi-report-update',
  templateUrl: './report-update.component.html',
})
export class ReportUpdateComponent implements OnInit {
  isSaving = false;
  report: IReport | null = null;
  reportTypeValues = Object.keys(ReportType);

  editForm: ReportFormGroup = this.reportFormService.createReportFormGroup();

  constructor(
    protected reportService: ReportService,
    protected reportFormService: ReportFormService,
    protected activatedRoute: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ report }) => {
      this.report = report;
      if (report) {
        this.updateForm(report);
      }
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const report = this.reportFormService.getReport(this.editForm);
    if (report.id !== null) {
      this.subscribeToSaveResponse(this.reportService.update(report));
    } else {
      this.subscribeToSaveResponse(this.reportService.create(report));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IReport>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(report: IReport): void {
    this.report = report;
    this.reportFormService.resetForm(this.editForm, report);
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-report-heading" data-cy="ReportCreateUpdateHeading" jhiTranslate="teamDojoApp.report.home.createOrEditLabel">
        Create or edit a Report
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.report.title" for="field_title">Title</label>
          <input type="text" class="form-control" name="title" id="field_title" data-cy="title" formControlName="title" />
          <div *ngIf="editForm.get('title')!.invalid && (editForm.get('title')!.dirty || editForm.get('title')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('title')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 1 }"
            >
              This field is required to be at least 1 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 50 }"
            >
              This field cannot be longer than 50 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.report.description" for="field_description">Description</label>
          <input
            type="text"
            class="form-control"
            name="description"
            id="field_description"
            data-cy="description"
            formControlName="description"
          />
          <div *ngIf="editForm.get('description')!.invalid && (editForm.get('description')!.dirty || editForm.get('description')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('description')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('description')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 1 }"
            >
              This field is required to be at least 1 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('description')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 4096 }"
            >
              This field cannot be longer than 4096 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.report.type" for="field_type">Type</label>
          <select class="form-control" name="type" formControlName="type" id="field_type" data-cy="type">
            <option [ngValue]="null">{{ 'teamDojoApp.ReportType.null' | translate }}</option>
            <option value="BUG">{{ 'teamDojoApp.ReportType.BUG' | translate }}</option>
            <option value="WISH">{{ 'teamDojoApp.ReportType.WISH' | translate }}</option>
            <option value="REVIEW">{{ 'teamDojoApp.ReportType.REVIEW' | translate }}</option>
            <option value="COMPLIMENT">{{ 'teamDojoApp.ReportType.COMPLIMENT' | translate }}</option>
          </select>
          <div *ngIf="editForm.get('type')!.invalid && (editForm.get('type')!.dirty || editForm.get('type')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('type')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.report.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('createdAt')!.invalid && (editForm.get('createdAt')!.dirty || editForm.get('createdAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('createdAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('createdAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.report.updatedAt" for="field_updatedAt">Updated At</label>
          <div class="d-flex">
            <input
              id="field_updatedAt"
              data-cy="updatedAt"
              type="datetime-local"
              class="form-control"
              name="updatedAt"
              formControlName="updatedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('updatedAt')!.invalid && (editForm.get('updatedAt')!.dirty || editForm.get('updatedAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('updatedAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('updatedAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/report/report-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.report.home.createOrEditLabel"
          data-cy="ReportCreateUpdateHeading"
          v-text="$t('teamDojoApp.report.home.createOrEditLabel')"
        >
          Create or edit a Report
        </h2>
        <div>
          <div class="form-group" v-if="report.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="report.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.report.title')" for="report-title">Title</label>
            <input
              type="text"
              class="form-control"
              name="title"
              id="report-title"
              data-cy="title"
              :class="{ valid: !$v.report.title.$invalid, invalid: $v.report.title.$invalid }"
              v-model="$v.report.title.$model"
              required
            />
            <div v-if="$v.report.title.$anyDirty && $v.report.title.$invalid">
              <small class="form-text text-danger" v-if="!$v.report.title.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.report.title.minLength" v-text="$t('entity.validation.minlength', { min: 1 })">
                This field is required to be at least 1 characters.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.report.title.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 50 })"
              >
                This field cannot be longer than 50 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.report.description')" for="report-description">Description</label>
            <input
              type="text"
              class="form-control"
              name="description"
              id="report-description"
              data-cy="description"
              :class="{ valid: !$v.report.description.$invalid, invalid: $v.report.description.$invalid }"
              v-model="$v.report.description.$model"
              required
            />
            <div v-if="$v.report.description.$anyDirty && $v.report.description.$invalid">
              <small class="form-text text-danger" v-if="!$v.report.description.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.report.description.minLength"
                v-text="$t('entity.validation.minlength', { min: 1 })"
              >
                This field is required to be at least 1 characters.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.report.description.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 4096 })"
              >
                This field cannot be longer than 4096 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.report.type')" for="report-type">Type</label>
            <select
              class="form-control"
              name="type"
              :class="{ valid: !$v.report.type.$invalid, invalid: $v.report.type.$invalid }"
              v-model="$v.report.type.$model"
              id="report-type"
              data-cy="type"
              required
            >
              <option value="BUG" v-bind:label="$t('teamDojoApp.ReportType.BUG')">BUG</option>
              <option value="WISH" v-bind:label="$t('teamDojoApp.ReportType.WISH')">WISH</option>
              <option value="REVIEW" v-bind:label="$t('teamDojoApp.ReportType.REVIEW')">REVIEW</option>
              <option value="COMPLIMENT" v-bind:label="$t('teamDojoApp.ReportType.COMPLIMENT')">COMPLIMENT</option>
            </select>
            <div v-if="$v.report.type.$anyDirty && $v.report.type.$invalid">
              <small class="form-text text-danger" v-if="!$v.report.type.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.report.createdAt')" for="report-createdAt">Created At</label>
            <div class="d-flex">
              <input
                id="report-createdAt"
                data-cy="createdAt"
                type="datetime-local"
                class="form-control"
                name="createdAt"
                :class="{ valid: !$v.report.createdAt.$invalid, invalid: $v.report.createdAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.report.createdAt.$model)"
                @change="updateInstantField('createdAt', $event)"
              />
            </div>
            <div v-if="$v.report.createdAt.$anyDirty && $v.report.createdAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.report.createdAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.report.createdAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.report.updatedAt')" for="report-updatedAt">Updated At</label>
            <div class="d-flex">
              <input
                id="report-updatedAt"
                data-cy="updatedAt"
                type="datetime-local"
                class="form-control"
                name="updatedAt"
                :class="{ valid: !$v.report.updatedAt.$invalid, invalid: $v.report.updatedAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.report.updatedAt.$model)"
                @change="updateInstantField('updatedAt', $event)"
              />
            </div>
            <div v-if="$v.report.updatedAt.$anyDirty && $v.report.updatedAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.report.updatedAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.report.updatedAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.report.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./report-update.component.ts"></script>
