// src/main/webapp/app/entities/report/list/report.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IReport } from '../report.model';
import { ReportService } from '../service/report.service';
import { ReportDeleteDialogComponent } from '../delete/report-delete-dialog.component';

@Component({
  selector: 'jhi-report',
  templateUrl: './report.component.html',
})
export class ReportComponent implements OnInit {
  reports?: IReport[];
  isLoading = false;

  constructor(protected reportService: ReportService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.reportService.query().subscribe({
      next: (res: HttpResponse<IReport[]>) => {
        this.isLoading = false;
        this.reports = res.body ?? [];
      },
      error: () => {
        this.isLoading = false;
      },
    });
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(_index: number, item: IReport): number {
    return item.id!;
  }

  delete(report: IReport): void {
    const modalRef = this.modalService.open(ReportDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.report = report;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="ReportHeading">
    <span jhiTranslate="teamDojoApp.report.home.title">Reports</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="teamDojoApp.report.home.refreshListLabel">Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-report"
        [routerLink]="['/report/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="teamDojoApp.report.home.createLabel">Create a new Report</span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="reports?.length === 0">
    <span jhiTranslate="teamDojoApp.report.home.notFound">No Reports found</span>
  </div>

  <div class="table-responsive table-entities" id="entities" *ngIf="reports && reports.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="navigateToWithComponentValues()">
          <th scope="col" jhiSortBy="id">
            <div class="d-flex">
              <span jhiTranslate="global.field.id">ID</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="title">
            <div class="d-flex">
              <span jhiTranslate="teamDojoApp.report.title">Title</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="description">
            <div class="d-flex">
              <span jhiTranslate="teamDojoApp.report.description">Description</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="type">
            <div class="d-flex">
              <span jhiTranslate="teamDojoApp.report.type">Type</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="createdAt">
            <div class="d-flex">
              <span jhiTranslate="teamDojoApp.report.createdAt">Created At</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="updatedAt">
            <div class="d-flex">
              <span jhiTranslate="teamDojoApp.report.updatedAt">Updated At</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let report of reports; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/report', report.id, 'view']">{{ report.id }}</a>
          </td>
          <td>{{ report.title }}</td>
          <td>{{ report.description }}</td>
          <td jhiTranslate="{{ 'teamDojoApp.ReportType.' + report.type }}">{{ report.type }}</td>
          <td>{{ report.createdAt | formatMediumDatetime }}</td>
          <td>{{ report.updatedAt | formatMediumDatetime }}</td>
          <td class="text-end">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/report', report.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/report', report.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(report)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/report/report.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="ReportHeading">
      <span v-text="$t('teamDojoApp.report.home.title')" id="report-heading">Reports</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('teamDojoApp.report.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'ReportCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-report"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('teamDojoApp.report.home.createLabel')"> Create a new Report </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && reports && reports.length === 0">
      <span v-text="$t('teamDojoApp.report.home.notFound')">No reports found</span>
    </div>
    <div class="table-responsive" v-if="reports && reports.length > 0">
      <table class="table table-striped" aria-describedby="reports">
        <thead>
          <tr>
            <th scope="row"><span v-text="$t('global.field.id')">ID</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.report.title')">Title</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.report.description')">Description</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.report.type')">Type</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.report.createdAt')">Created At</span></th>
            <th scope="row"><span v-text="$t('teamDojoApp.report.updatedAt')">Updated At</span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="report in reports" :key="report.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'ReportView', params: { reportId: report.id } }">{{ report.id }}</router-link>
            </td>
            <td>{{ report.title }}</td>
            <td>{{ report.description }}</td>
            <td v-text="$t('teamDojoApp.ReportType.' + report.type)">{{ report.type }}</td>
            <td>{{ report.createdAt ? $d(Date.parse(report.createdAt), 'short') : '' }}</td>
            <td>{{ report.updatedAt ? $d(Date.parse(report.updatedAt), 'short') : '' }}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'ReportView', params: { reportId: report.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'ReportEdit', params: { reportId: report.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(report)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="teamDojoApp.report.delete.question" data-cy="reportDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-report-heading" v-text="$t('teamDojoApp.report.delete.question', { id: removeId })">
          Are you sure you want to delete this Report?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-report"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeReport()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./report.component.ts"></script>
