// src/main/webapp/app/entities/level/level-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.level.home.createOrEditLabel"
          data-cy="LevelCreateUpdateHeading"
          v-text="$t('teamDojoApp.level.home.createOrEditLabel')"
        >
          Create or edit a Level
        </h2>
        <div>
          <div class="form-group" v-if="level.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="level.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.level.title')" for="level-title">Title</label>
            <input
              type="text"
              class="form-control"
              name="title"
              id="level-title"
              data-cy="title"
              :class="{ valid: !$v.level.title.$invalid, invalid: $v.level.title.$invalid }"
              v-model="$v.level.title.$model"
              required
            />
            <div v-if="$v.level.title.$anyDirty && $v.level.title.$invalid">
              <small class="form-text text-danger" v-if="!$v.level.title.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.level.title.minLength" v-text="$t('entity.validation.minlength', { min: 3 })">
                This field is required to be at least 3 characters.
              </small>
              <small class="form-text text-danger" v-if="!$v.level.title.maxLength" v-text="$t('entity.validation.maxlength', { max: 50 })">
                This field cannot be longer than 50 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.level.description')" for="level-description">Description</label>
            <input
              type="text"
              class="form-control"
              name="description"
              id="level-description"
              data-cy="description"
              :class="{ valid: !$v.level.description.$invalid, invalid: $v.level.description.$invalid }"
              v-model="$v.level.description.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.level.requiredScore')" for="level-requiredScore"
              >Required Score</label
            >
            <input
              type="number"
              class="form-control"
              name="requiredScore"
              id="level-requiredScore"
              data-cy="requiredScore"
              :class="{ valid: !$v.level.requiredScore.$invalid, invalid: $v.level.requiredScore.$invalid }"
              v-model.number="$v.level.requiredScore.$model"
              required
            />
            <div v-if="$v.level.requiredScore.$anyDirty && $v.level.requiredScore.$invalid">
              <small class="form-text text-danger" v-if="!$v.level.requiredScore.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.level.requiredScore.min" v-text="$t('entity.validation.min', { min: 0 })">
                This field should be at least 0.
              </small>
              <small class="form-text text-danger" v-if="!$v.level.requiredScore.max" v-text="$t('entity.validation.max', { max: 1 })">
                This field cannot be longer than 1 characters.
              </small>
              <small class="form-text text-danger" v-if="!$v.level.requiredScore.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.level.instantMultiplier')" for="level-instantMultiplier"
              >Instant Multiplier</label
            >
            <input
              type="number"
              class="form-control"
              name="instantMultiplier"
              id="level-instantMultiplier"
              data-cy="instantMultiplier"
              :class="{ valid: !$v.level.instantMultiplier.$invalid, invalid: $v.level.instantMultiplier.$invalid }"
              v-model.number="$v.level.instantMultiplier.$model"
              required
            />
            <div v-if="$v.level.instantMultiplier.$anyDirty && $v.level.instantMultiplier.$invalid">
              <small class="form-text text-danger" v-if="!$v.level.instantMultiplier.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.level.instantMultiplier.min" v-text="$t('entity.validation.min', { min: 0 })">
                This field should be at least 0.
              </small>
              <small class="form-text text-danger" v-if="!$v.level.instantMultiplier.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.level.completionBonus')" for="level-completionBonus"
              >Completion Bonus</label
            >
            <input
              type="number"
              class="form-control"
              name="completionBonus"
              id="level-completionBonus"
              data-cy="completionBonus"
              :class="{ valid: !$v.level.completionBonus.$invalid, invalid: $v.level.completionBonus.$invalid }"
              v-model.number="$v.level.completionBonus.$model"
            />
            <div v-if="$v.level.completionBonus.$anyDirty && $v.level.completionBonus.$invalid">
              <small class="form-text text-danger" v-if="!$v.level.completionBonus.min" v-text="$t('entity.validation.min', { min: 0 })">
                This field should be at least 0.
              </small>
              <small class="form-text text-danger" v-if="!$v.level.completionBonus.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.level.createdAt')" for="level-createdAt">Created At</label>
            <div class="d-flex">
              <input
                id="level-createdAt"
                data-cy="createdAt"
                type="datetime-local"
                class="form-control"
                name="createdAt"
                :class="{ valid: !$v.level.createdAt.$invalid, invalid: $v.level.createdAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.level.createdAt.$model)"
                @change="updateInstantField('createdAt', $event)"
              />
            </div>
            <div v-if="$v.level.createdAt.$anyDirty && $v.level.createdAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.level.createdAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.level.createdAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.level.updatedAt')" for="level-updatedAt">Updated At</label>
            <div class="d-flex">
              <input
                id="level-updatedAt"
                data-cy="updatedAt"
                type="datetime-local"
                class="form-control"
                name="updatedAt"
                :class="{ valid: !$v.level.updatedAt.$invalid, invalid: $v.level.updatedAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.level.updatedAt.$model)"
                @change="updateInstantField('updatedAt', $event)"
              />
            </div>
            <div v-if="$v.level.updatedAt.$anyDirty && $v.level.updatedAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.level.updatedAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.level.updatedAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.level.dependsOn')" for="level-dependsOn">Depends On</label>
            <select class="form-control" id="level-dependsOn" data-cy="dependsOn" name="dependsOn" v-model="level.dependsOn">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="level.dependsOn && levelOption.id === level.dependsOn.id ? level.dependsOn : levelOption"
                v-for="levelOption in dependsOns"
                :key="levelOption.id"
              >
                {{ levelOption.title }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.level.image')" for="level-image">Image</label>
            <select class="form-control" id="level-image" data-cy="image" name="image" v-model="level.image">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="level.image && imageOption.id === level.image.id ? level.image : imageOption"
                v-for="imageOption in images"
                :key="imageOption.id"
              >
                {{ imageOption.title }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.level.dimension')" for="level-dimension">Dimension</label>
            <select class="form-control" id="level-dimension" data-cy="dimension" name="dimension" v-model="level.dimension" required>
              <option v-if="!level.dimension" v-bind:value="null" selected></option>
              <option
                v-bind:value="level.dimension && dimensionOption.id === level.dimension.id ? level.dimension : dimensionOption"
                v-for="dimensionOption in dimensions"
                :key="dimensionOption.id"
              >
                {{ dimensionOption.title }}
              </option>
            </select>
          </div>
          <div v-if="$v.level.dimension.$anyDirty && $v.level.dimension.$invalid">
            <small class="form-text text-danger" v-if="!$v.level.dimension.required" v-text="$t('entity.validation.required')">
              This field is required.
            </small>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.level.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./level-update.component.ts"></script>

// src/main/webapp/app/entities/level/update/level-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import * as dayjs from 'dayjs';
import { DATE_TIME_FORMAT } from 'app/config/input.constants';

import { ILevel, Level } from '../level.model';
import { LevelService } from '../service/level.service';
import { IImage } from 'app/entities/image/image.model';
import { ImageService } from 'app/entities/image/service/image.service';
import { IDimension } from 'app/entities/dimension/dimension.model';
import { DimensionService } from 'app/entities/dimension/service/dimension.service';

@Component({
  selector: 'jhi-level-update',
  templateUrl: './level-update.component.html',
})
export class LevelUpdateComponent implements OnInit {
  isSaving = false;

  dependsOnsCollection: ILevel[] = [];
  imagesSharedCollection: IImage[] = [];
  dimensionsSharedCollection: IDimension[] = [];

  editForm = this.fb.group({
    id: [],
    title: [null, [Validators.required, Validators.minLength(3), Validators.maxLength(50)]],
    description: [null, [Validators.maxLength(4096)]],
    requiredScore: [null, [Validators.required, Validators.min(0), Validators.max(1)]],
    instantMultiplier: [null, [Validators.required, Validators.min(0)]],
    completionBonus: [null, [Validators.min(0)]],
    createdAt: [null, [Validators.required]],
    updatedAt: [null, [Validators.required]],
    dependsOn: [],
    image: [],
    dimension: [null, Validators.required],
  });

  constructor(
    protected levelService: LevelService,
    protected imageService: ImageService,
    protected dimensionService: DimensionService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ level }) => {
      if (level.id === undefined) {
        const today = dayjs().startOf('day');
        level.createdAt = today;
        level.updatedAt = today;
      }

      this.updateForm(level);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const level = this.createFromForm();
    if (level.id !== undefined) {
      this.subscribeToSaveResponse(this.levelService.update(level));
    } else {
      this.subscribeToSaveResponse(this.levelService.create(level));
    }
  }

  trackLevelById(index: number, item: ILevel): number {
    return item.id!;
  }

  trackImageById(index: number, item: IImage): number {
    return item.id!;
  }

  trackDimensionById(index: number, item: IDimension): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ILevel>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(level: ILevel): void {
    this.editForm.patchValue({
      id: level.id,
      title: level.title,
      description: level.description,
      requiredScore: level.requiredScore,
      instantMultiplier: level.instantMultiplier,
      completionBonus: level.completionBonus,
      createdAt: level.createdAt ? level.createdAt.format(DATE_TIME_FORMAT) : null,
      updatedAt: level.updatedAt ? level.updatedAt.format(DATE_TIME_FORMAT) : null,
      dependsOn: level.dependsOn,
      image: level.image,
      dimension: level.dimension,
    });

    this.dependsOnsCollection = this.levelService.addLevelToCollectionIfMissing(this.dependsOnsCollection, level.dependsOn);
    this.imagesSharedCollection = this.imageService.addImageToCollectionIfMissing(this.imagesSharedCollection, level.image);
    this.dimensionsSharedCollection = this.dimensionService.addDimensionToCollectionIfMissing(
      this.dimensionsSharedCollection,
      level.dimension
    );
  }

  protected loadRelationshipsOptions(): void {
    this.levelService
      .query({ 'levelId.specified': 'false' })
      .pipe(map((res: HttpResponse<ILevel[]>) => res.body ?? []))
      .pipe(map((levels: ILevel[]) => this.levelService.addLevelToCollectionIfMissing(levels, this.editForm.get('dependsOn')!.value)))
      .subscribe((levels: ILevel[]) => (this.dependsOnsCollection = levels));

    this.imageService
      .query()
      .pipe(map((res: HttpResponse<IImage[]>) => res.body ?? []))
      .pipe(map((images: IImage[]) => this.imageService.addImageToCollectionIfMissing(images, this.editForm.get('image')!.value)))
      .subscribe((images: IImage[]) => (this.imagesSharedCollection = images));

    this.dimensionService
      .query()
      .pipe(map((res: HttpResponse<IDimension[]>) => res.body ?? []))
      .pipe(
        map((dimensions: IDimension[]) =>
          this.dimensionService.addDimensionToCollectionIfMissing(dimensions, this.editForm.get('dimension')!.value)
        )
      )
      .subscribe((dimensions: IDimension[]) => (this.dimensionsSharedCollection = dimensions));
  }

  protected createFromForm(): ILevel {
    return {
      ...new Level(),
      id: this.editForm.get(['id'])!.value,
      title: this.editForm.get(['title'])!.value,
      description: this.editForm.get(['description'])!.value,
      requiredScore: this.editForm.get(['requiredScore'])!.value,
      instantMultiplier: this.editForm.get(['instantMultiplier'])!.value,
      completionBonus: this.editForm.get(['completionBonus'])!.value,
      createdAt: this.editForm.get(['createdAt'])!.value ? dayjs(this.editForm.get(['createdAt'])!.value, DATE_TIME_FORMAT) : undefined,
      updatedAt: this.editForm.get(['updatedAt'])!.value ? dayjs(this.editForm.get(['updatedAt'])!.value, DATE_TIME_FORMAT) : undefined,
      dependsOn: this.editForm.get(['dependsOn'])!.value,
      image: this.editForm.get(['image'])!.value,
      dimension: this.editForm.get(['dimension'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-level-heading" data-cy="LevelCreateUpdateHeading" jhiTranslate="teamDojoApp.level.home.createOrEditLabel">
        Create or edit a Level
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.level.title" for="field_title">Title</label>
          <input type="text" class="form-control" name="title" id="field_title" data-cy="title" formControlName="title" />
          <div *ngIf="editForm.get('title')!.invalid && (editForm.get('title')!.dirty || editForm.get('title')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('title')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 3 }"
            >
              This field is required to be at least 3 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 50 }"
            >
              This field cannot be longer than 50 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.level.description" for="field_description">Description</label>
          <input
            type="text"
            class="form-control"
            name="description"
            id="field_description"
            data-cy="description"
            formControlName="description"
          />
          <div *ngIf="editForm.get('description')!.invalid && (editForm.get('description')!.dirty || editForm.get('description')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('description')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 4096 }"
            >
              This field cannot be longer than 4096 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.level.requiredScore" for="field_requiredScore">Required Score</label>
          <input
            type="number"
            class="form-control"
            name="requiredScore"
            id="field_requiredScore"
            data-cy="requiredScore"
            formControlName="requiredScore"
          />
          <div
            *ngIf="
              editForm.get('requiredScore')!.invalid && (editForm.get('requiredScore')!.dirty || editForm.get('requiredScore')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('requiredScore')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('requiredScore')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 0 }"
            >
              This field should be at least 0.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('requiredScore')?.errors?.max"
              jhiTranslate="entity.validation.max"
              [translateValues]="{ max: 1 }"
            >
              This field cannot be more than 1.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('requiredScore')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.level.instantMultiplier" for="field_instantMultiplier"
            >Instant Multiplier</label
          >
          <input
            type="number"
            class="form-control"
            name="instantMultiplier"
            id="field_instantMultiplier"
            data-cy="instantMultiplier"
            formControlName="instantMultiplier"
          />
          <div
            *ngIf="
              editForm.get('instantMultiplier')!.invalid &&
              (editForm.get('instantMultiplier')!.dirty || editForm.get('instantMultiplier')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('instantMultiplier')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('instantMultiplier')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 0 }"
            >
              This field should be at least 0.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('instantMultiplier')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.level.completionBonus" for="field_completionBonus"
            >Completion Bonus</label
          >
          <input
            type="number"
            class="form-control"
            name="completionBonus"
            id="field_completionBonus"
            data-cy="completionBonus"
            formControlName="completionBonus"
          />
          <div
            *ngIf="
              editForm.get('completionBonus')!.invalid &&
              (editForm.get('completionBonus')!.dirty || editForm.get('completionBonus')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('completionBonus')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 0 }"
            >
              This field should be at least 0.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('completionBonus')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.level.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('createdAt')!.invalid && (editForm.get('createdAt')!.dirty || editForm.get('createdAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('createdAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('createdAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.level.updatedAt" for="field_updatedAt">Updated At</label>
          <div class="d-flex">
            <input
              id="field_updatedAt"
              data-cy="updatedAt"
              type="datetime-local"
              class="form-control"
              name="updatedAt"
              formControlName="updatedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('updatedAt')!.invalid && (editForm.get('updatedAt')!.dirty || editForm.get('updatedAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('updatedAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('updatedAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.level.dependsOn" for="field_dependsOn">Depends On</label>
          <select class="form-control" id="field_dependsOn" data-cy="dependsOn" name="dependsOn" formControlName="dependsOn">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="levelOption.id === editForm.get('dependsOn')!.value?.id ? editForm.get('dependsOn')!.value : levelOption"
              *ngFor="let levelOption of dependsOnsCollection; trackBy: trackLevelById"
            >
              {{ levelOption.title }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.level.image" for="field_image">Image</label>
          <select class="form-control" id="field_image" data-cy="image" name="image" formControlName="image">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="imageOption.id === editForm.get('image')!.value?.id ? editForm.get('image')!.value : imageOption"
              *ngFor="let imageOption of imagesSharedCollection; trackBy: trackImageById"
            >
              {{ imageOption.title }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.level.dimension" for="field_dimension">Dimension</label>
          <select class="form-control" id="field_dimension" data-cy="dimension" name="dimension" formControlName="dimension">
            <option *ngIf="!editForm.get('dimension')!.value" [ngValue]="null" selected></option>
            <option
              [ngValue]="dimensionOption.id === editForm.get('dimension')!.value?.id ? editForm.get('dimension')!.value : dimensionOption"
              *ngFor="let dimensionOption of dimensionsSharedCollection; trackBy: trackDimensionById"
            >
              {{ dimensionOption.title }}
            </option>
          </select>
        </div>
        <div *ngIf="editForm.get(['dimension'])!.invalid && (editForm.get(['dimension'])!.dirty || editForm.get(['dimension'])!.touched)">
          <small
            class="form-text text-danger"
            *ngIf="editForm.get(['dimension'])?.errors?.required"
            jhiTranslate="entity.validation.required"
          >
            This field is required.
          </small>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
