// src/main/webapp/app/entities/team/team.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="TeamHeading">
      <span v-text="$t('teamDojoApp.team.home.title')" id="team-heading">Teams</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('teamDojoApp.team.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'TeamCreate' }" custom v-slot="{ navigate }">
          <button @click="navigate" id="jh-create-entity" data-cy="entityCreateButton" class="btn btn-primary jh-create-entity create-team">
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('teamDojoApp.team.home.createLabel')"> Create a new Team </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && teams && teams.length === 0">
      <span v-text="$t('teamDojoApp.team.home.notFound')">No teams found</span>
    </div>
    <div class="table-responsive" v-if="teams && teams.length > 0">
      <table class="table table-striped" aria-describedby="teams">
        <thead>
          <tr>
            <th scope="row" v-on:click="changeOrder('id')">
              <span v-text="$t('global.field.id')">ID</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('title')">
              <span v-text="$t('teamDojoApp.team.title')">Title</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'title'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('shortTitle')">
              <span v-text="$t('teamDojoApp.team.shortTitle')">Short Title</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'shortTitle'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('slogan')">
              <span v-text="$t('teamDojoApp.team.slogan')">Slogan</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'slogan'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('contact')">
              <span v-text="$t('teamDojoApp.team.contact')">Contact</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'contact'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('validUntil')">
              <span v-text="$t('teamDojoApp.team.validUntil')">Valid Until</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'validUntil'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('pureTrainingTeam')">
              <span v-text="$t('teamDojoApp.team.pureTrainingTeam')">Pure Training Team</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'pureTrainingTeam'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('official')">
              <span v-text="$t('teamDojoApp.team.official')">Official</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'official'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('createdAt')">
              <span v-text="$t('teamDojoApp.team.createdAt')">Created At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'createdAt'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('updatedAt')">
              <span v-text="$t('teamDojoApp.team.updatedAt')">Updated At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'updatedAt'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('image.title')">
              <span v-text="$t('teamDojoApp.team.image')">Image</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'image.title'"></jhi-sort-indicator>
            </th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="team in teams" :key="team.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'TeamView', params: { teamId: team.id } }">{{ team.id }}</router-link>
            </td>
            <td>{{ team.title }}</td>
            <td>{{ team.shortTitle }}</td>
            <td>{{ team.slogan }}</td>
            <td>{{ team.contact }}</td>
            <td>{{ team.validUntil ? $d(Date.parse(team.validUntil), 'short') : '' }}</td>
            <td>{{ team.pureTrainingTeam }}</td>
            <td>{{ team.official }}</td>
            <td>{{ team.createdAt ? $d(Date.parse(team.createdAt), 'short') : '' }}</td>
            <td>{{ team.updatedAt ? $d(Date.parse(team.updatedAt), 'short') : '' }}</td>
            <td>
              <div v-if="team.image">
                <router-link :to="{ name: 'ImageView', params: { imageId: team.image.id } }">{{ team.image.title }}</router-link>
              </div>
            </td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'TeamView', params: { teamId: team.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'TeamEdit', params: { teamId: team.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(team)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
        <infinite-loading
          ref="infiniteLoading"
          v-if="totalItems > itemsPerPage"
          :identifier="infiniteId"
          slot="append"
          @infinite="loadMore"
          force-use-infinite-wrapper=".el-table__body-wrapper"
          :distance="20"
        >
        </infinite-loading>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="teamDojoApp.team.delete.question" data-cy="teamDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-team-heading" v-text="$t('teamDojoApp.team.delete.question', { id: removeId })">
          Are you sure you want to delete this Team?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-team"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeTeam()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./team.component.ts"></script>

// src/main/webapp/app/entities/team/list/team.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ITeam } from '../team.model';

import { ITEMS_PER_PAGE } from 'app/config/pagination.constants';
import { TeamService } from '../service/team.service';
import { TeamDeleteDialogComponent } from '../delete/team-delete-dialog.component';
import { ParseLinks } from 'app/core/util/parse-links.service';

@Component({
  selector: 'jhi-team',
  templateUrl: './team.component.html',
})
export class TeamComponent implements OnInit {
  teams: ITeam[];
  isLoading = false;
  itemsPerPage: number;
  links: { [key: string]: number };
  page: number;
  predicate: string;
  ascending: boolean;

  constructor(protected teamService: TeamService, protected modalService: NgbModal, protected parseLinks: ParseLinks) {
    this.teams = [];
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.page = 0;
    this.links = {
      last: 0,
    };
    this.predicate = 'id';
    this.ascending = true;
  }

  loadAll(): void {
    this.isLoading = true;

    this.teamService
      .query({
        page: this.page,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<ITeam[]>) => {
          this.isLoading = false;
          this.paginateTeams(res.body, res.headers);
        },
        () => {
          this.isLoading = false;
        }
      );
  }

  reset(): void {
    this.page = 0;
    this.teams = [];
    this.loadAll();
  }

  loadPage(page: number): void {
    this.page = page;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: ITeam): number {
    return item.id!;
  }

  delete(team: ITeam): void {
    const modalRef = this.modalService.open(TeamDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.team = team;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.reset();
      }
    });
  }

  protected sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateTeams(data: ITeam[] | null, headers: HttpHeaders): void {
    this.links = this.parseLinks.parse(headers.get('link') ?? '');
    if (data) {
      for (const d of data) {
        this.teams.push(d);
      }
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="TeamHeading">
    <span jhiTranslate="teamDojoApp.team.home.title">Teams</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="reset()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="teamDojoApp.team.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-team"
        [routerLink]="['/team/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="teamDojoApp.team.home.createLabel"> Create a new Team </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="teams?.length === 0">
    <span jhiTranslate="teamDojoApp.team.home.notFound">No teams found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="teams && teams.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="reset.bind(this)">
          <th scope="col" jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="title"><span jhiTranslate="teamDojoApp.team.title">Title</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="shortTitle">
            <span jhiTranslate="teamDojoApp.team.shortTitle">Short Title</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="slogan"><span jhiTranslate="teamDojoApp.team.slogan">Slogan</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="contact">
            <span jhiTranslate="teamDojoApp.team.contact">Contact</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="validUntil">
            <span jhiTranslate="teamDojoApp.team.validUntil">Valid Until</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="pureTrainingTeam">
            <span jhiTranslate="teamDojoApp.team.pureTrainingTeam">Pure Training Team</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="official">
            <span jhiTranslate="teamDojoApp.team.official">Official</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="createdAt">
            <span jhiTranslate="teamDojoApp.team.createdAt">Created At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="updatedAt">
            <span jhiTranslate="teamDojoApp.team.updatedAt">Updated At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="image.title">
            <span jhiTranslate="teamDojoApp.team.image">Image</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
        <tr *ngFor="let team of teams; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/team', team.id, 'view']">{{ team.id }}</a>
          </td>
          <td>{{ team.title }}</td>
          <td>{{ team.shortTitle }}</td>
          <td>{{ team.slogan }}</td>
          <td>{{ team.contact }}</td>
          <td>{{ team.validUntil | formatMediumDatetime }}</td>
          <td>{{ team.pureTrainingTeam }}</td>
          <td>{{ team.official }}</td>
          <td>{{ team.createdAt | formatMediumDatetime }}</td>
          <td>{{ team.updatedAt | formatMediumDatetime }}</td>
          <td>
            <div *ngIf="team.image">
              <a [routerLink]="['/image', team.image?.id, 'view']">{{ team.image?.title }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/team', team.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/team', team.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(team)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
