// src/main/webapp/app/entities/training/training-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.training.home.createOrEditLabel"
          data-cy="TrainingCreateUpdateHeading"
          v-text="$t('teamDojoApp.training.home.createOrEditLabel')"
        >
          Create or edit a Training
        </h2>
        <div>
          <div class="form-group" v-if="training.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="training.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.training.title')" for="training-title">Title</label>
            <input
              type="text"
              class="form-control"
              name="title"
              id="training-title"
              data-cy="title"
              :class="{ valid: !$v.training.title.$invalid, invalid: $v.training.title.$invalid }"
              v-model="$v.training.title.$model"
              required
            />
            <div v-if="$v.training.title.$anyDirty && $v.training.title.$invalid">
              <small class="form-text text-danger" v-if="!$v.training.title.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.training.title.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 80 })"
              >
                This field cannot be longer than 80 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.training.description')" for="training-description">Description</label>
            <input
              type="text"
              class="form-control"
              name="description"
              id="training-description"
              data-cy="description"
              :class="{ valid: !$v.training.description.$invalid, invalid: $v.training.description.$invalid }"
              v-model="$v.training.description.$model"
            />
            <div v-if="$v.training.description.$anyDirty && $v.training.description.$invalid">
              <small
                class="form-text text-danger"
                v-if="!$v.training.description.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 100 })"
              >
                This field cannot be longer than 100 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.training.contact')" for="training-contact">Contact</label>
            <input
              type="text"
              class="form-control"
              name="contact"
              id="training-contact"
              data-cy="contact"
              :class="{ valid: !$v.training.contact.$invalid, invalid: $v.training.contact.$invalid }"
              v-model="$v.training.contact.$model"
            />
            <div v-if="$v.training.contact.$anyDirty && $v.training.contact.$invalid">
              <small
                class="form-text text-danger"
                v-if="!$v.training.contact.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 255 })"
              >
                This field cannot be longer than 255 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.training.link')" for="training-link">Link</label>
            <input
              type="text"
              class="form-control"
              name="link"
              id="training-link"
              data-cy="link"
              :class="{ valid: !$v.training.link.$invalid, invalid: $v.training.link.$invalid }"
              v-model="$v.training.link.$model"
            />
            <div v-if="$v.training.link.$anyDirty && $v.training.link.$invalid">
              <small
                class="form-text text-danger"
                v-if="!$v.training.link.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 255 })"
              >
                This field cannot be longer than 255 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.training.validUntil')" for="training-validUntil">Valid Until</label>
            <div class="d-flex">
              <input
                id="training-validUntil"
                data-cy="validUntil"
                type="datetime-local"
                class="form-control"
                name="validUntil"
                :class="{ valid: !$v.training.validUntil.$invalid, invalid: $v.training.validUntil.$invalid }"
                :value="convertDateTimeFromServer($v.training.validUntil.$model)"
                @change="updateInstantField('validUntil', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.training.isOfficial')" for="training-isOfficial">Is Official</label>
            <input
              type="checkbox"
              class="form-check"
              name="isOfficial"
              id="training-isOfficial"
              data-cy="isOfficial"
              :class="{ valid: !$v.training.isOfficial.$invalid, invalid: $v.training.isOfficial.$invalid }"
              v-model="$v.training.isOfficial.$model"
              required
            />
            <div v-if="$v.training.isOfficial.$anyDirty && $v.training.isOfficial.$invalid">
              <small class="form-text text-danger" v-if="!$v.training.isOfficial.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.training.suggestedBy')" for="training-suggestedBy"
              >Suggested By</label
            >
            <input
              type="text"
              class="form-control"
              name="suggestedBy"
              id="training-suggestedBy"
              data-cy="suggestedBy"
              :class="{ valid: !$v.training.suggestedBy.$invalid, invalid: $v.training.suggestedBy.$invalid }"
              v-model="$v.training.suggestedBy.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.training.createdAt')" for="training-createdAt">Created At</label>
            <div class="d-flex">
              <input
                id="training-createdAt"
                data-cy="createdAt"
                type="datetime-local"
                class="form-control"
                name="createdAt"
                :class="{ valid: !$v.training.createdAt.$invalid, invalid: $v.training.createdAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.training.createdAt.$model)"
                @change="updateInstantField('createdAt', $event)"
              />
            </div>
            <div v-if="$v.training.createdAt.$anyDirty && $v.training.createdAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.training.createdAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.training.createdAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.training.updatedAt')" for="training-updatedAt">Updated At</label>
            <div class="d-flex">
              <input
                id="training-updatedAt"
                data-cy="updatedAt"
                type="datetime-local"
                class="form-control"
                name="updatedAt"
                :class="{ valid: !$v.training.updatedAt.$invalid, invalid: $v.training.updatedAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.training.updatedAt.$model)"
                @change="updateInstantField('updatedAt', $event)"
              />
            </div>
            <div v-if="$v.training.updatedAt.$anyDirty && $v.training.updatedAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.training.updatedAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.training.updatedAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label v-text="$t('teamDojoApp.training.skill')" for="training-skill">Skill</label>
            <select
              class="form-control"
              id="training-skill"
              data-cy="skill"
              multiple
              name="skill"
              v-if="training.skills !== undefined"
              v-model="training.skills"
            >
              <option v-bind:value="getSelected(training.skills, skillOption)" v-for="skillOption in skills" :key="skillOption.id">
                {{ skillOption.title }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.training.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./training-update.component.ts"></script>

// src/main/webapp/app/entities/training/update/training-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import * as dayjs from 'dayjs';
import { DATE_TIME_FORMAT } from 'app/config/input.constants';

import { ITraining, Training } from '../training.model';
import { TrainingService } from '../service/training.service';
import { ISkill } from 'app/entities/skill/skill.model';
import { SkillService } from 'app/entities/skill/service/skill.service';

@Component({
  selector: 'jhi-training-update',
  templateUrl: './training-update.component.html',
})
export class TrainingUpdateComponent implements OnInit {
  isSaving = false;

  skillsSharedCollection: ISkill[] = [];

  editForm = this.fb.group({
    id: [],
    title: [null, [Validators.required, Validators.maxLength(80)]],
    description: [null, [Validators.maxLength(100)]],
    contact: [null, [Validators.maxLength(255)]],
    link: [null, [Validators.maxLength(255)]],
    validUntil: [],
    isOfficial: [null, [Validators.required]],
    suggestedBy: [],
    createdAt: [null, [Validators.required]],
    updatedAt: [null, [Validators.required]],
    skills: [],
  });

  constructor(
    protected trainingService: TrainingService,
    protected skillService: SkillService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ training }) => {
      if (training.id === undefined) {
        const today = dayjs().startOf('day');
        training.validUntil = today;
        training.createdAt = today;
        training.updatedAt = today;
      }

      this.updateForm(training);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const training = this.createFromForm();
    if (training.id !== undefined) {
      this.subscribeToSaveResponse(this.trainingService.update(training));
    } else {
      this.subscribeToSaveResponse(this.trainingService.create(training));
    }
  }

  trackSkillById(index: number, item: ISkill): number {
    return item.id!;
  }

  getSelectedSkill(option: ISkill, selectedVals?: ISkill[]): ISkill {
    if (selectedVals) {
      for (const selectedVal of selectedVals) {
        if (option.id === selectedVal.id) {
          return selectedVal;
        }
      }
    }
    return option;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ITraining>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(training: ITraining): void {
    this.editForm.patchValue({
      id: training.id,
      title: training.title,
      description: training.description,
      contact: training.contact,
      link: training.link,
      validUntil: training.validUntil ? training.validUntil.format(DATE_TIME_FORMAT) : null,
      isOfficial: training.isOfficial,
      suggestedBy: training.suggestedBy,
      createdAt: training.createdAt ? training.createdAt.format(DATE_TIME_FORMAT) : null,
      updatedAt: training.updatedAt ? training.updatedAt.format(DATE_TIME_FORMAT) : null,
      skills: training.skills,
    });

    this.skillsSharedCollection = this.skillService.addSkillToCollectionIfMissing(this.skillsSharedCollection, ...(training.skills ?? []));
  }

  protected loadRelationshipsOptions(): void {
    this.skillService
      .query()
      .pipe(map((res: HttpResponse<ISkill[]>) => res.body ?? []))
      .pipe(
        map((skills: ISkill[]) => this.skillService.addSkillToCollectionIfMissing(skills, ...(this.editForm.get('skills')!.value ?? [])))
      )
      .subscribe((skills: ISkill[]) => (this.skillsSharedCollection = skills));
  }

  protected createFromForm(): ITraining {
    return {
      ...new Training(),
      id: this.editForm.get(['id'])!.value,
      title: this.editForm.get(['title'])!.value,
      description: this.editForm.get(['description'])!.value,
      contact: this.editForm.get(['contact'])!.value,
      link: this.editForm.get(['link'])!.value,
      validUntil: this.editForm.get(['validUntil'])!.value ? dayjs(this.editForm.get(['validUntil'])!.value, DATE_TIME_FORMAT) : undefined,
      isOfficial: this.editForm.get(['isOfficial'])!.value,
      suggestedBy: this.editForm.get(['suggestedBy'])!.value,
      createdAt: this.editForm.get(['createdAt'])!.value ? dayjs(this.editForm.get(['createdAt'])!.value, DATE_TIME_FORMAT) : undefined,
      updatedAt: this.editForm.get(['updatedAt'])!.value ? dayjs(this.editForm.get(['updatedAt'])!.value, DATE_TIME_FORMAT) : undefined,
      skills: this.editForm.get(['skills'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-training-heading" data-cy="TrainingCreateUpdateHeading" jhiTranslate="teamDojoApp.training.home.createOrEditLabel">
        Create or edit a Training
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.training.title" for="field_title">Title</label>
          <input type="text" class="form-control" name="title" id="field_title" data-cy="title" formControlName="title" />
          <div *ngIf="editForm.get('title')!.invalid && (editForm.get('title')!.dirty || editForm.get('title')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('title')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 80 }"
            >
              This field cannot be longer than 80 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.training.description" for="field_description">Description</label>
          <input
            type="text"
            class="form-control"
            name="description"
            id="field_description"
            data-cy="description"
            formControlName="description"
          />
          <div *ngIf="editForm.get('description')!.invalid && (editForm.get('description')!.dirty || editForm.get('description')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('description')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 100 }"
            >
              This field cannot be longer than 100 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.training.contact" for="field_contact">Contact</label>
          <input type="text" class="form-control" name="contact" id="field_contact" data-cy="contact" formControlName="contact" />
          <div *ngIf="editForm.get('contact')!.invalid && (editForm.get('contact')!.dirty || editForm.get('contact')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('contact')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 255 }"
            >
              This field cannot be longer than 255 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.training.link" for="field_link">Link</label>
          <input type="text" class="form-control" name="link" id="field_link" data-cy="link" formControlName="link" />
          <div *ngIf="editForm.get('link')!.invalid && (editForm.get('link')!.dirty || editForm.get('link')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('link')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 255 }"
            >
              This field cannot be longer than 255 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.training.validUntil" for="field_validUntil">Valid Until</label>
          <div class="d-flex">
            <input
              id="field_validUntil"
              data-cy="validUntil"
              type="datetime-local"
              class="form-control"
              name="validUntil"
              formControlName="validUntil"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.training.isOfficial" for="field_isOfficial">Is Official</label>
          <input
            type="checkbox"
            class="form-check"
            name="isOfficial"
            id="field_isOfficial"
            data-cy="isOfficial"
            formControlName="isOfficial"
          />
          <div *ngIf="editForm.get('isOfficial')!.invalid && (editForm.get('isOfficial')!.dirty || editForm.get('isOfficial')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('isOfficial')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.training.suggestedBy" for="field_suggestedBy">Suggested By</label>
          <input
            type="text"
            class="form-control"
            name="suggestedBy"
            id="field_suggestedBy"
            data-cy="suggestedBy"
            formControlName="suggestedBy"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.training.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('createdAt')!.invalid && (editForm.get('createdAt')!.dirty || editForm.get('createdAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('createdAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('createdAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.training.updatedAt" for="field_updatedAt">Updated At</label>
          <div class="d-flex">
            <input
              id="field_updatedAt"
              data-cy="updatedAt"
              type="datetime-local"
              class="form-control"
              name="updatedAt"
              formControlName="updatedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('updatedAt')!.invalid && (editForm.get('updatedAt')!.dirty || editForm.get('updatedAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('updatedAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('updatedAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label jhiTranslate="teamDojoApp.training.skill" for="field_skills">Skill</label>
          <select class="form-control" id="field_skills" data-cy="skill" multiple name="skills" formControlName="skills">
            <option
              [ngValue]="getSelectedSkill(skillOption, editForm.get('skills')!.value)"
              *ngFor="let skillOption of skillsSharedCollection; trackBy: trackSkillById"
            >
              {{ skillOption.title }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
