// src/main/webapp/app/entities/team-skill/team-skill.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="TeamSkillHeading">
      <span v-text="$t('teamDojoApp.teamSkill.home.title')" id="team-skill-heading">Team Skills</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="$t('teamDojoApp.teamSkill.home.refreshListLabel')">Refresh List</span>
        </button>
        <router-link :to="{ name: 'TeamSkillCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-team-skill"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="$t('teamDojoApp.teamSkill.home.createLabel')"> Create a new Team Skill </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && teamSkills && teamSkills.length === 0">
      <span v-text="$t('teamDojoApp.teamSkill.home.notFound')">No teamSkills found</span>
    </div>
    <div class="table-responsive" v-if="teamSkills && teamSkills.length > 0">
      <table class="table table-striped" aria-describedby="teamSkills">
        <thead>
          <tr>
            <th scope="row" v-on:click="changeOrder('id')">
              <span v-text="$t('global.field.id')">ID</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('completedAt')">
              <span v-text="$t('teamDojoApp.teamSkill.completedAt')">Completed At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'completedAt'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('verifiedAt')">
              <span v-text="$t('teamDojoApp.teamSkill.verifiedAt')">Verified At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'verifiedAt'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('irrelevant')">
              <span v-text="$t('teamDojoApp.teamSkill.irrelevant')">Irrelevant</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'irrelevant'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('note')">
              <span v-text="$t('teamDojoApp.teamSkill.note')">Note</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'note'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('vote')">
              <span v-text="$t('teamDojoApp.teamSkill.vote')">Vote</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'vote'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('voters')">
              <span v-text="$t('teamDojoApp.teamSkill.voters')">Voters</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'voters'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('createdAt')">
              <span v-text="$t('teamDojoApp.teamSkill.createdAt')">Created At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'createdAt'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('updatedAt')">
              <span v-text="$t('teamDojoApp.teamSkill.updatedAt')">Updated At</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'updatedAt'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('skill.title')">
              <span v-text="$t('teamDojoApp.teamSkill.skill')">Skill</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'skill.title'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('team.title')">
              <span v-text="$t('teamDojoApp.teamSkill.team')">Team</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'team.title'"></jhi-sort-indicator>
            </th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="teamSkill in teamSkills" :key="teamSkill.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'TeamSkillView', params: { teamSkillId: teamSkill.id } }">{{ teamSkill.id }}</router-link>
            </td>
            <td>{{ teamSkill.completedAt ? $d(Date.parse(teamSkill.completedAt), 'short') : '' }}</td>
            <td>{{ teamSkill.verifiedAt ? $d(Date.parse(teamSkill.verifiedAt), 'short') : '' }}</td>
            <td>{{ teamSkill.irrelevant }}</td>
            <td>{{ teamSkill.note }}</td>
            <td>{{ teamSkill.vote }}</td>
            <td>{{ teamSkill.voters }}</td>
            <td>{{ teamSkill.createdAt ? $d(Date.parse(teamSkill.createdAt), 'short') : '' }}</td>
            <td>{{ teamSkill.updatedAt ? $d(Date.parse(teamSkill.updatedAt), 'short') : '' }}</td>
            <td>
              <div v-if="teamSkill.skill">
                <router-link :to="{ name: 'SkillView', params: { skillId: teamSkill.skill.id } }">{{ teamSkill.skill.title }}</router-link>
              </div>
            </td>
            <td>
              <div v-if="teamSkill.team">
                <router-link :to="{ name: 'TeamView', params: { teamId: teamSkill.team.id } }">{{ teamSkill.team.title }}</router-link>
              </div>
            </td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'TeamSkillView', params: { teamSkillId: teamSkill.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'TeamSkillEdit', params: { teamSkillId: teamSkill.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(teamSkill)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
        <infinite-loading
          ref="infiniteLoading"
          v-if="totalItems > itemsPerPage"
          :identifier="infiniteId"
          slot="append"
          @infinite="loadMore"
          force-use-infinite-wrapper=".el-table__body-wrapper"
          :distance="20"
        >
        </infinite-loading>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="teamDojoApp.teamSkill.delete.question" data-cy="teamSkillDeleteDialogHeading" v-text="$t('entity.delete.title')"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-teamSkill-heading" v-text="$t('teamDojoApp.teamSkill.delete.question', { id: removeId })">
          Are you sure you want to delete this Team Skill?
        </p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-teamSkill"
          data-cy="entityConfirmDeleteButton"
          v-text="$t('entity.action.delete')"
          v-on:click="removeTeamSkill()"
        >
          Delete
        </button>
      </div>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./team-skill.component.ts"></script>

// src/main/webapp/app/entities/team-skill/list/team-skill.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ITeamSkill } from '../team-skill.model';

import { ITEMS_PER_PAGE } from 'app/config/pagination.constants';
import { TeamSkillService } from '../service/team-skill.service';
import { TeamSkillDeleteDialogComponent } from '../delete/team-skill-delete-dialog.component';
import { ParseLinks } from 'app/core/util/parse-links.service';

@Component({
  selector: 'jhi-team-skill',
  templateUrl: './team-skill.component.html',
})
export class TeamSkillComponent implements OnInit {
  teamSkills: ITeamSkill[];
  isLoading = false;
  itemsPerPage: number;
  links: { [key: string]: number };
  page: number;
  predicate: string;
  ascending: boolean;

  constructor(protected teamSkillService: TeamSkillService, protected modalService: NgbModal, protected parseLinks: ParseLinks) {
    this.teamSkills = [];
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.page = 0;
    this.links = {
      last: 0,
    };
    this.predicate = 'id';
    this.ascending = true;
  }

  loadAll(): void {
    this.isLoading = true;

    this.teamSkillService
      .query({
        page: this.page,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<ITeamSkill[]>) => {
          this.isLoading = false;
          this.paginateTeamSkills(res.body, res.headers);
        },
        () => {
          this.isLoading = false;
        }
      );
  }

  reset(): void {
    this.page = 0;
    this.teamSkills = [];
    this.loadAll();
  }

  loadPage(page: number): void {
    this.page = page;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: ITeamSkill): number {
    return item.id!;
  }

  delete(teamSkill: ITeamSkill): void {
    const modalRef = this.modalService.open(TeamSkillDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.teamSkill = teamSkill;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.reset();
      }
    });
  }

  protected sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateTeamSkills(data: ITeamSkill[] | null, headers: HttpHeaders): void {
    this.links = this.parseLinks.parse(headers.get('link') ?? '');
    if (data) {
      for (const d of data) {
        this.teamSkills.push(d);
      }
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="TeamSkillHeading">
    <span jhiTranslate="teamDojoApp.teamSkill.home.title">Team Skills</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="reset()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="teamDojoApp.teamSkill.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-team-skill"
        [routerLink]="['/team-skill/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="teamDojoApp.teamSkill.home.createLabel"> Create a new Team Skill </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="teamSkills?.length === 0">
    <span jhiTranslate="teamDojoApp.teamSkill.home.notFound">No teamSkills found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="teamSkills && teamSkills.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="reset.bind(this)">
          <th scope="col" jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="completedAt">
            <span jhiTranslate="teamDojoApp.teamSkill.completedAt">Completed At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="verifiedAt">
            <span jhiTranslate="teamDojoApp.teamSkill.verifiedAt">Verified At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="irrelevant">
            <span jhiTranslate="teamDojoApp.teamSkill.irrelevant">Irrelevant</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="note"><span jhiTranslate="teamDojoApp.teamSkill.note">Note</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="vote"><span jhiTranslate="teamDojoApp.teamSkill.vote">Vote</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="voters">
            <span jhiTranslate="teamDojoApp.teamSkill.voters">Voters</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="createdAt">
            <span jhiTranslate="teamDojoApp.teamSkill.createdAt">Created At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="updatedAt">
            <span jhiTranslate="teamDojoApp.teamSkill.updatedAt">Updated At</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="skill.title">
            <span jhiTranslate="teamDojoApp.teamSkill.skill">Skill</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="team.title">
            <span jhiTranslate="teamDojoApp.teamSkill.team">Team</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
        <tr *ngFor="let teamSkill of teamSkills; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/team-skill', teamSkill.id, 'view']">{{ teamSkill.id }}</a>
          </td>
          <td>{{ teamSkill.completedAt | formatMediumDatetime }}</td>
          <td>{{ teamSkill.verifiedAt | formatMediumDatetime }}</td>
          <td>{{ teamSkill.irrelevant }}</td>
          <td>{{ teamSkill.note }}</td>
          <td>{{ teamSkill.vote }}</td>
          <td>{{ teamSkill.voters }}</td>
          <td>{{ teamSkill.createdAt | formatMediumDatetime }}</td>
          <td>{{ teamSkill.updatedAt | formatMediumDatetime }}</td>
          <td>
            <div *ngIf="teamSkill.skill">
              <a [routerLink]="['/skill', teamSkill.skill?.id, 'view']">{{ teamSkill.skill?.title }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="teamSkill.team">
              <a [routerLink]="['/team', teamSkill.team?.id, 'view']">{{ teamSkill.team?.title }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/team-skill', teamSkill.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/team-skill', teamSkill.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(teamSkill)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
