// src/main/webapp/app/entities/team/team-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.team.home.createOrEditLabel"
          data-cy="TeamCreateUpdateHeading"
          v-text="$t('teamDojoApp.team.home.createOrEditLabel')"
        >
          Create or edit a Team
        </h2>
        <div>
          <div class="form-group" v-if="team.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="team.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.team.title')" for="team-title">Title</label>
            <input
              type="text"
              class="form-control"
              name="title"
              id="team-title"
              data-cy="title"
              :class="{ valid: !$v.team.title.$invalid, invalid: $v.team.title.$invalid }"
              v-model="$v.team.title.$model"
              required
            />
            <div v-if="$v.team.title.$anyDirty && $v.team.title.$invalid">
              <small class="form-text text-danger" v-if="!$v.team.title.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.team.title.minLength" v-text="$t('entity.validation.minlength', { min: 2 })">
                This field is required to be at least 2 characters.
              </small>
              <small class="form-text text-danger" v-if="!$v.team.title.maxLength" v-text="$t('entity.validation.maxlength', { max: 50 })">
                This field cannot be longer than 50 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.team.shortTitle')" for="team-shortTitle">Short Title</label>
            <input
              type="text"
              class="form-control"
              name="shortTitle"
              id="team-shortTitle"
              data-cy="shortTitle"
              :class="{ valid: !$v.team.shortTitle.$invalid, invalid: $v.team.shortTitle.$invalid }"
              v-model="$v.team.shortTitle.$model"
              required
            />
            <div v-if="$v.team.shortTitle.$anyDirty && $v.team.shortTitle.$invalid">
              <small class="form-text text-danger" v-if="!$v.team.shortTitle.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.team.shortTitle.minLength"
                v-text="$t('entity.validation.minlength', { min: 2 })"
              >
                This field is required to be at least 2 characters.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.team.shortTitle.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 20 })"
              >
                This field cannot be longer than 20 characters.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.team.shortTitle.pattern"
                v-text="$t('entity.validation.pattern', { pattern: 'Short Title' })"
              >
                This field should follow pattern for "Short Title".
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.team.slogan')" for="team-slogan">Slogan</label>
            <input
              type="text"
              class="form-control"
              name="slogan"
              id="team-slogan"
              data-cy="slogan"
              :class="{ valid: !$v.team.slogan.$invalid, invalid: $v.team.slogan.$invalid }"
              v-model="$v.team.slogan.$model"
            />
            <div v-if="$v.team.slogan.$anyDirty && $v.team.slogan.$invalid">
              <small
                class="form-text text-danger"
                v-if="!$v.team.slogan.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 255 })"
              >
                This field cannot be longer than 255 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.team.contact')" for="team-contact">Contact</label>
            <input
              type="text"
              class="form-control"
              name="contact"
              id="team-contact"
              data-cy="contact"
              :class="{ valid: !$v.team.contact.$invalid, invalid: $v.team.contact.$invalid }"
              v-model="$v.team.contact.$model"
            />
            <div v-if="$v.team.contact.$anyDirty && $v.team.contact.$invalid">
              <small
                class="form-text text-danger"
                v-if="!$v.team.contact.maxLength"
                v-text="$t('entity.validation.maxlength', { max: 255 })"
              >
                This field cannot be longer than 255 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.team.validUntil')" for="team-validUntil">Valid Until</label>
            <div class="d-flex">
              <input
                id="team-validUntil"
                data-cy="validUntil"
                type="datetime-local"
                class="form-control"
                name="validUntil"
                :class="{ valid: !$v.team.validUntil.$invalid, invalid: $v.team.validUntil.$invalid }"
                :value="convertDateTimeFromServer($v.team.validUntil.$model)"
                @change="updateInstantField('validUntil', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.team.pureTrainingTeam')" for="team-pureTrainingTeam"
              >Pure Training Team</label
            >
            <input
              type="checkbox"
              class="form-check"
              name="pureTrainingTeam"
              id="team-pureTrainingTeam"
              data-cy="pureTrainingTeam"
              :class="{ valid: !$v.team.pureTrainingTeam.$invalid, invalid: $v.team.pureTrainingTeam.$invalid }"
              v-model="$v.team.pureTrainingTeam.$model"
              required
            />
            <div v-if="$v.team.pureTrainingTeam.$anyDirty && $v.team.pureTrainingTeam.$invalid">
              <small class="form-text text-danger" v-if="!$v.team.pureTrainingTeam.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.team.official')" for="team-official">Official</label>
            <input
              type="checkbox"
              class="form-check"
              name="official"
              id="team-official"
              data-cy="official"
              :class="{ valid: !$v.team.official.$invalid, invalid: $v.team.official.$invalid }"
              v-model="$v.team.official.$model"
              required
            />
            <div v-if="$v.team.official.$anyDirty && $v.team.official.$invalid">
              <small class="form-text text-danger" v-if="!$v.team.official.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.team.createdAt')" for="team-createdAt">Created At</label>
            <div class="d-flex">
              <input
                id="team-createdAt"
                data-cy="createdAt"
                type="datetime-local"
                class="form-control"
                name="createdAt"
                :class="{ valid: !$v.team.createdAt.$invalid, invalid: $v.team.createdAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.team.createdAt.$model)"
                @change="updateInstantField('createdAt', $event)"
              />
            </div>
            <div v-if="$v.team.createdAt.$anyDirty && $v.team.createdAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.team.createdAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.team.createdAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.team.updatedAt')" for="team-updatedAt">Updated At</label>
            <div class="d-flex">
              <input
                id="team-updatedAt"
                data-cy="updatedAt"
                type="datetime-local"
                class="form-control"
                name="updatedAt"
                :class="{ valid: !$v.team.updatedAt.$invalid, invalid: $v.team.updatedAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.team.updatedAt.$model)"
                @change="updateInstantField('updatedAt', $event)"
              />
            </div>
            <div v-if="$v.team.updatedAt.$anyDirty && $v.team.updatedAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.team.updatedAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.team.updatedAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.team.image')" for="team-image">Image</label>
            <select class="form-control" id="team-image" data-cy="image" name="image" v-model="team.image">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="team.image && imageOption.id === team.image.id ? team.image : imageOption"
                v-for="imageOption in images"
                :key="imageOption.id"
              >
                {{ imageOption.title }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label v-text="$t('teamDojoApp.team.participations')" for="team-participations">Participations</label>
            <select
              class="form-control"
              id="team-participations"
              data-cy="participations"
              multiple
              name="participations"
              v-if="team.participations !== undefined"
              v-model="team.participations"
            >
              <option
                v-bind:value="getSelected(team.participations, dimensionOption)"
                v-for="dimensionOption in dimensions"
                :key="dimensionOption.id"
              >
                {{ dimensionOption.title }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.team.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./team-update.component.ts"></script>

// src/main/webapp/app/entities/team/update/team-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import dayjs from 'dayjs/esm';
import { DATE_TIME_FORMAT } from 'app/config/input.constants';

import { ITeam, Team } from '../team.model';
import { TeamService } from '../service/team.service';
import { IImage } from 'app/entities/image/image.model';
import { ImageService } from 'app/entities/image/service/image.service';
import { IDimension } from 'app/entities/dimension/dimension.model';
import { DimensionService } from 'app/entities/dimension/service/dimension.service';

@Component({
  selector: 'jhi-team-update',
  templateUrl: './team-update.component.html',
})
export class TeamUpdateComponent implements OnInit {
  isSaving = false;

  imagesSharedCollection: IImage[] = [];
  dimensionsSharedCollection: IDimension[] = [];

  editForm = this.fb.group({
    id: [],
    title: [null, [Validators.required, Validators.minLength(2), Validators.maxLength(50)]],
    shortTitle: [null, [Validators.required, Validators.minLength(2), Validators.maxLength(20), Validators.pattern('^[a-zA-Z0-9_-]*$')]],
    slogan: [null, [Validators.maxLength(255)]],
    contact: [null, [Validators.maxLength(255)]],
    expirationDate: [],
    pureTrainingTeam: [null, [Validators.required]],
    official: [null, [Validators.required]],
    createdAt: [null, [Validators.required]],
    updatedAt: [null, [Validators.required]],
    image: [],
    participations: [],
  });

  constructor(
    protected teamService: TeamService,
    protected imageService: ImageService,
    protected dimensionService: DimensionService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ team }) => {
      if (team.id === undefined) {
        const today = dayjs().startOf('day');
        team.expirationDate = today;
        team.createdAt = today;
        team.updatedAt = today;
      }

      this.updateForm(team);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const team = this.createFromForm();
    if (team.id !== undefined) {
      this.subscribeToSaveResponse(this.teamService.update(team));
    } else {
      this.subscribeToSaveResponse(this.teamService.create(team));
    }
  }

  trackImageById(index: number, item: IImage): number {
    return item.id!;
  }

  trackDimensionById(index: number, item: IDimension): number {
    return item.id!;
  }

  getSelectedDimension(option: IDimension, selectedVals?: IDimension[]): IDimension {
    if (selectedVals) {
      for (const selectedVal of selectedVals) {
        if (option.id === selectedVal.id) {
          return selectedVal;
        }
      }
    }
    return option;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ITeam>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(team: ITeam): void {
    this.editForm.patchValue({
      id: team.id,
      title: team.title,
      shortTitle: team.shortTitle,
      slogan: team.slogan,
      contact: team.contact,
      expirationDate: team.expirationDate ? team.expirationDate.format(DATE_TIME_FORMAT) : null,
      pureTrainingTeam: team.pureTrainingTeam,
      official: team.official,
      createdAt: team.createdAt ? team.createdAt.format(DATE_TIME_FORMAT) : null,
      updatedAt: team.updatedAt ? team.updatedAt.format(DATE_TIME_FORMAT) : null,
      image: team.image,
      participations: team.participations,
    });

    this.imagesSharedCollection = this.imageService.addImageToCollectionIfMissing(this.imagesSharedCollection, team.image);
    this.dimensionsSharedCollection = this.dimensionService.addDimensionToCollectionIfMissing(
      this.dimensionsSharedCollection,
      ...(team.participations ?? [])
    );
  }

  protected loadRelationshipsOptions(): void {
    this.imageService
      .query()
      .pipe(map((res: HttpResponse<IImage[]>) => res.body ?? []))
      .pipe(map((images: IImage[]) => this.imageService.addImageToCollectionIfMissing(images, this.editForm.get('image')!.value)))
      .subscribe((images: IImage[]) => (this.imagesSharedCollection = images));

    this.dimensionService
      .query()
      .pipe(map((res: HttpResponse<IDimension[]>) => res.body ?? []))
      .pipe(
        map((dimensions: IDimension[]) =>
          this.dimensionService.addDimensionToCollectionIfMissing(dimensions, ...(this.editForm.get('participations')!.value ?? []))
        )
      )
      .subscribe((dimensions: IDimension[]) => (this.dimensionsSharedCollection = dimensions));
  }

  protected createFromForm(): ITeam {
    return {
      ...new Team(),
      id: this.editForm.get(['id'])!.value,
      title: this.editForm.get(['title'])!.value,
      shortTitle: this.editForm.get(['shortTitle'])!.value,
      slogan: this.editForm.get(['slogan'])!.value,
      contact: this.editForm.get(['contact'])!.value,
      expirationDate: this.editForm.get(['expirationDate'])!.value
        ? dayjs(this.editForm.get(['expirationDate'])!.value, DATE_TIME_FORMAT)
        : undefined,
      pureTrainingTeam: this.editForm.get(['pureTrainingTeam'])!.value,
      official: this.editForm.get(['official'])!.value,
      createdAt: this.editForm.get(['createdAt'])!.value ? dayjs(this.editForm.get(['createdAt'])!.value, DATE_TIME_FORMAT) : undefined,
      updatedAt: this.editForm.get(['updatedAt'])!.value ? dayjs(this.editForm.get(['updatedAt'])!.value, DATE_TIME_FORMAT) : undefined,
      image: this.editForm.get(['image'])!.value,
      participations: this.editForm.get(['participations'])!.value,
    };
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-team-heading" data-cy="TeamCreateUpdateHeading" jhiTranslate="teamDojoApp.team.home.createOrEditLabel">
        Create or edit a Team
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="row mb-3" [hidden]="editForm.get('id')!.value == null">
          <label class="form-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.team.title" for="field_title">Title</label>
          <input type="text" class="form-control" name="title" id="field_title" data-cy="title" formControlName="title" />
          <div *ngIf="editForm.get('title')!.invalid && (editForm.get('title')!.dirty || editForm.get('title')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('title')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 2 }"
            >
              This field is required to be at least 2 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 50 }"
            >
              This field cannot be longer than 50 characters.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.team.shortTitle" for="field_shortTitle">Short Title</label>
          <input
            type="text"
            class="form-control"
            name="shortTitle"
            id="field_shortTitle"
            data-cy="shortTitle"
            formControlName="shortTitle"
          />
          <div *ngIf="editForm.get('shortTitle')!.invalid && (editForm.get('shortTitle')!.dirty || editForm.get('shortTitle')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('shortTitle')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('shortTitle')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 2 }"
            >
              This field is required to be at least 2 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('shortTitle')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 20 }"
            >
              This field cannot be longer than 20 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('shortTitle')?.errors?.pattern"
              jhiTranslate="entity.validation.pattern"
              [translateValues]="{ pattern: 'Short Title' }"
            >
              This field should follow pattern for "Short Title".
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.team.slogan" for="field_slogan">Slogan</label>
          <input type="text" class="form-control" name="slogan" id="field_slogan" data-cy="slogan" formControlName="slogan" />
          <div *ngIf="editForm.get('slogan')!.invalid && (editForm.get('slogan')!.dirty || editForm.get('slogan')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('slogan')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 255 }"
            >
              This field cannot be longer than 255 characters.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.team.contact" for="field_contact">Contact</label>
          <input type="text" class="form-control" name="contact" id="field_contact" data-cy="contact" formControlName="contact" />
          <div *ngIf="editForm.get('contact')!.invalid && (editForm.get('contact')!.dirty || editForm.get('contact')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('contact')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 255 }"
            >
              This field cannot be longer than 255 characters.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.team.expirationDate" for="field_expirationDate">Expiration Date</label>
          <div class="d-flex">
            <input
              id="field_expirationDate"
              data-cy="expirationDate"
              type="datetime-local"
              class="form-control"
              name="expirationDate"
              formControlName="expirationDate"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.team.pureTrainingTeam" for="field_pureTrainingTeam">Pure Training Team</label>
          <input
            type="checkbox"
            class="form-check"
            name="pureTrainingTeam"
            id="field_pureTrainingTeam"
            data-cy="pureTrainingTeam"
            formControlName="pureTrainingTeam"
          />
          <div
            *ngIf="
              editForm.get('pureTrainingTeam')!.invalid &&
              (editForm.get('pureTrainingTeam')!.dirty || editForm.get('pureTrainingTeam')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('pureTrainingTeam')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.team.official" for="field_official">Official</label>
          <input type="checkbox" class="form-check" name="official" id="field_official" data-cy="official" formControlName="official" />
          <div *ngIf="editForm.get('official')!.invalid && (editForm.get('official')!.dirty || editForm.get('official')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('official')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.team.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('createdAt')!.invalid && (editForm.get('createdAt')!.dirty || editForm.get('createdAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('createdAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('createdAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.team.updatedAt" for="field_updatedAt">Updated At</label>
          <div class="d-flex">
            <input
              id="field_updatedAt"
              data-cy="updatedAt"
              type="datetime-local"
              class="form-control"
              name="updatedAt"
              formControlName="updatedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('updatedAt')!.invalid && (editForm.get('updatedAt')!.dirty || editForm.get('updatedAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('updatedAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('updatedAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="teamDojoApp.team.image" for="field_image">Image</label>
          <select class="form-control" id="field_image" data-cy="image" name="image" formControlName="image">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="imageOption.id === editForm.get('image')!.value?.id ? editForm.get('image')!.value : imageOption"
              *ngFor="let imageOption of imagesSharedCollection; trackBy: trackImageById"
            >
              {{ imageOption.title }}
            </option>
          </select>
        </div>

        <div class="row mb-3">
          <label jhiTranslate="teamDojoApp.team.participations" for="field_participations">Participations</label>
          <select
            class="form-control"
            id="field_participations"
            data-cy="participations"
            multiple
            name="participations"
            formControlName="participations"
          >
            <option
              [ngValue]="getSelectedDimension(dimensionOption, editForm.get('participations')!.value)"
              *ngFor="let dimensionOption of dimensionsSharedCollection; trackBy: trackDimensionById"
            >
              {{ dimensionOption.title }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
