// src/main/webapp/app/entities/badge/badge-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.badge.home.createOrEditLabel"
          data-cy="BadgeCreateUpdateHeading"
          v-text="$t('teamDojoApp.badge.home.createOrEditLabel')"
        >
          Create or edit a Badge
        </h2>
        <div>
          <div class="form-group" v-if="badge.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="badge.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badge.title')" for="badge-title">Title</label>
            <input
              type="text"
              class="form-control"
              name="title"
              id="badge-title"
              data-cy="title"
              :class="{ valid: !$v.badge.title.$invalid, invalid: $v.badge.title.$invalid }"
              v-model="$v.badge.title.$model"
              required
            />
            <div v-if="$v.badge.title.$anyDirty && $v.badge.title.$invalid">
              <small class="form-text text-danger" v-if="!$v.badge.title.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.badge.title.minLength" v-text="$t('entity.validation.minlength', { min: 2 })">
                This field is required to be at least 2 characters.
              </small>
              <small class="form-text text-danger" v-if="!$v.badge.title.maxLength" v-text="$t('entity.validation.maxlength', { max: 20 })">
                This field cannot be longer than 20 characters.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badge.description')" for="badge-description">Description</label>
            <input
              type="text"
              class="form-control"
              name="description"
              id="badge-description"
              data-cy="description"
              :class="{ valid: !$v.badge.description.$invalid, invalid: $v.badge.description.$invalid }"
              v-model="$v.badge.description.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badge.availableUntil')" for="badge-availableUntil"
              >Available Until</label
            >
            <div class="d-flex">
              <input
                id="badge-availableUntil"
                data-cy="availableUntil"
                type="datetime-local"
                class="form-control"
                name="availableUntil"
                :class="{ valid: !$v.badge.availableUntil.$invalid, invalid: $v.badge.availableUntil.$invalid }"
                :value="convertDateTimeFromServer($v.badge.availableUntil.$model)"
                @change="updateInstantField('availableUntil', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badge.availableAmount')" for="badge-availableAmount"
              >Available Amount</label
            >
            <input
              type="number"
              class="form-control"
              name="availableAmount"
              id="badge-availableAmount"
              data-cy="availableAmount"
              :class="{ valid: !$v.badge.availableAmount.$invalid, invalid: $v.badge.availableAmount.$invalid }"
              v-model.number="$v.badge.availableAmount.$model"
            />
            <div v-if="$v.badge.availableAmount.$anyDirty && $v.badge.availableAmount.$invalid">
              <small class="form-text text-danger" v-if="!$v.badge.availableAmount.min" v-text="$t('entity.validation.min', { min: 1 })">
                This field should be at least 1.
              </small>
              <small class="form-text text-danger" v-if="!$v.badge.availableAmount.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badge.requiredScore')" for="badge-requiredScore"
              >Required Score</label
            >
            <input
              type="number"
              class="form-control"
              name="requiredScore"
              id="badge-requiredScore"
              data-cy="requiredScore"
              :class="{ valid: !$v.badge.requiredScore.$invalid, invalid: $v.badge.requiredScore.$invalid }"
              v-model.number="$v.badge.requiredScore.$model"
              required
            />
            <div v-if="$v.badge.requiredScore.$anyDirty && $v.badge.requiredScore.$invalid">
              <small class="form-text text-danger" v-if="!$v.badge.requiredScore.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.badge.requiredScore.min" v-text="$t('entity.validation.min', { min: 0 })">
                This field should be at least 0.
              </small>
              <small class="form-text text-danger" v-if="!$v.badge.requiredScore.max" v-text="$t('entity.validation.max', { max: 1 })">
                This field cannot be longer than 1 characters.
              </small>
              <small class="form-text text-danger" v-if="!$v.badge.requiredScore.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badge.instantMultiplier')" for="badge-instantMultiplier"
              >Instant Multiplier</label
            >
            <input
              type="number"
              class="form-control"
              name="instantMultiplier"
              id="badge-instantMultiplier"
              data-cy="instantMultiplier"
              :class="{ valid: !$v.badge.instantMultiplier.$invalid, invalid: $v.badge.instantMultiplier.$invalid }"
              v-model.number="$v.badge.instantMultiplier.$model"
              required
            />
            <div v-if="$v.badge.instantMultiplier.$anyDirty && $v.badge.instantMultiplier.$invalid">
              <small class="form-text text-danger" v-if="!$v.badge.instantMultiplier.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small class="form-text text-danger" v-if="!$v.badge.instantMultiplier.min" v-text="$t('entity.validation.min', { min: 0 })">
                This field should be at least 0.
              </small>
              <small class="form-text text-danger" v-if="!$v.badge.instantMultiplier.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badge.completionBonus')" for="badge-completionBonus"
              >Completion Bonus</label
            >
            <input
              type="number"
              class="form-control"
              name="completionBonus"
              id="badge-completionBonus"
              data-cy="completionBonus"
              :class="{ valid: !$v.badge.completionBonus.$invalid, invalid: $v.badge.completionBonus.$invalid }"
              v-model.number="$v.badge.completionBonus.$model"
            />
            <div v-if="$v.badge.completionBonus.$anyDirty && $v.badge.completionBonus.$invalid">
              <small class="form-text text-danger" v-if="!$v.badge.completionBonus.min" v-text="$t('entity.validation.min', { min: 0 })">
                This field should be at least 0.
              </small>
              <small class="form-text text-danger" v-if="!$v.badge.completionBonus.numeric" v-text="$t('entity.validation.number')">
                This field should be a number.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badge.createdAt')" for="badge-createdAt">Created At</label>
            <div class="d-flex">
              <input
                id="badge-createdAt"
                data-cy="createdAt"
                type="datetime-local"
                class="form-control"
                name="createdAt"
                :class="{ valid: !$v.badge.createdAt.$invalid, invalid: $v.badge.createdAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.badge.createdAt.$model)"
                @change="updateInstantField('createdAt', $event)"
              />
            </div>
            <div v-if="$v.badge.createdAt.$anyDirty && $v.badge.createdAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.badge.createdAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.badge.createdAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badge.updatedAt')" for="badge-updatedAt">Updated At</label>
            <div class="d-flex">
              <input
                id="badge-updatedAt"
                data-cy="updatedAt"
                type="datetime-local"
                class="form-control"
                name="updatedAt"
                :class="{ valid: !$v.badge.updatedAt.$invalid, invalid: $v.badge.updatedAt.$invalid }"
                required
                :value="convertDateTimeFromServer($v.badge.updatedAt.$model)"
                @change="updateInstantField('updatedAt', $event)"
              />
            </div>
            <div v-if="$v.badge.updatedAt.$anyDirty && $v.badge.updatedAt.$invalid">
              <small class="form-text text-danger" v-if="!$v.badge.updatedAt.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
              <small
                class="form-text text-danger"
                v-if="!$v.badge.updatedAt.ZonedDateTimelocal"
                v-text="$t('entity.validation.ZonedDateTimelocal')"
              >
                This field should be a date and time.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badge.image')" for="badge-image">Image</label>
            <select class="form-control" id="badge-image" data-cy="image" name="image" v-model="badge.image">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="badge.image && imageOption.id === badge.image.id ? badge.image : imageOption"
                v-for="imageOption in images"
                :key="imageOption.id"
              >
                {{ imageOption.title }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label v-text="$t('teamDojoApp.badge.dimensions')" for="badge-dimensions">Dimensions</label>
            <select
              class="form-control"
              id="badge-dimensions"
              data-cy="dimensions"
              multiple
              name="dimensions"
              v-if="badge.dimensions !== undefined"
              v-model="badge.dimensions"
            >
              <option
                v-bind:value="getSelected(badge.dimensions, dimensionOption)"
                v-for="dimensionOption in dimensions"
                :key="dimensionOption.id"
              >
                {{ dimensionOption.title }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.badge.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./badge-update.component.ts"></script>

// src/main/webapp/app/entities/badge/update/badge-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import dayjs from 'dayjs/esm';
import { DATE_TIME_FORMAT } from 'app/config/input.constants';

import { IBadge, Badge } from '../badge.model';
import { BadgeService } from '../service/badge.service';
import { IImage } from 'app/entities/image/image.model';
import { ImageService } from 'app/entities/image/service/image.service';
import { IDimension } from 'app/entities/dimension/dimension.model';
import { DimensionService } from 'app/entities/dimension/service/dimension.service';

@Component({
  selector: 'jhi-badge-update',
  templateUrl: './badge-update.component.html',
})
export class BadgeUpdateComponent implements OnInit {
  isSaving = false;

  imagesSharedCollection: IImage[] = [];
  dimensionsSharedCollection: IDimension[] = [];

  editForm = this.fb.group({
    id: [],
    title: [null, [Validators.required, Validators.minLength(2), Validators.maxLength(20)]],
    description: [null, [Validators.maxLength(4096)]],
    availableUntil: [],
    availableAmount: [null, [Validators.min(1)]],
    requiredScore: [null, [Validators.required, Validators.min(0), Validators.max(1)]],
    instantMultiplier: [null, [Validators.required, Validators.min(0)]],
    completionBonus: [null, [Validators.min(0)]],
    createdAt: [null, [Validators.required]],
    updatedAt: [null, [Validators.required]],
    image: [],
    dimensions: [],
  });

  constructor(
    protected badgeService: BadgeService,
    protected imageService: ImageService,
    protected dimensionService: DimensionService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ badge }) => {
      if (badge.id === undefined) {
        const today = dayjs().startOf('day');
        badge.availableUntil = today;
        badge.createdAt = today;
        badge.updatedAt = today;
      }

      this.updateForm(badge);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const badge = this.createFromForm();
    if (badge.id !== undefined) {
      this.subscribeToSaveResponse(this.badgeService.update(badge));
    } else {
      this.subscribeToSaveResponse(this.badgeService.create(badge));
    }
  }

  trackImageById(index: number, item: IImage): number {
    return item.id!;
  }

  trackDimensionById(index: number, item: IDimension): number {
    return item.id!;
  }

  getSelectedDimension(option: IDimension, selectedVals?: IDimension[]): IDimension {
    if (selectedVals) {
      for (const selectedVal of selectedVals) {
        if (option.id === selectedVal.id) {
          return selectedVal;
        }
      }
    }
    return option;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IBadge>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(badge: IBadge): void {
    this.editForm.patchValue({
      id: badge.id,
      title: badge.title,
      description: badge.description,
      availableUntil: badge.availableUntil ? badge.availableUntil.format(DATE_TIME_FORMAT) : null,
      availableAmount: badge.availableAmount,
      requiredScore: badge.requiredScore,
      instantMultiplier: badge.instantMultiplier,
      completionBonus: badge.completionBonus,
      createdAt: badge.createdAt ? badge.createdAt.format(DATE_TIME_FORMAT) : null,
      updatedAt: badge.updatedAt ? badge.updatedAt.format(DATE_TIME_FORMAT) : null,
      image: badge.image,
      dimensions: badge.dimensions,
    });

    this.imagesSharedCollection = this.imageService.addImageToCollectionIfMissing(this.imagesSharedCollection, badge.image);
    this.dimensionsSharedCollection = this.dimensionService.addDimensionToCollectionIfMissing(
      this.dimensionsSharedCollection,
      ...(badge.dimensions ?? [])
    );
  }

  protected loadRelationshipsOptions(): void {
    this.imageService
      .query()
      .pipe(map((res: HttpResponse<IImage[]>) => res.body ?? []))
      .pipe(map((images: IImage[]) => this.imageService.addImageToCollectionIfMissing(images, this.editForm.get('image')!.value)))
      .subscribe((images: IImage[]) => (this.imagesSharedCollection = images));

    this.dimensionService
      .query()
      .pipe(map((res: HttpResponse<IDimension[]>) => res.body ?? []))
      .pipe(
        map((dimensions: IDimension[]) =>
          this.dimensionService.addDimensionToCollectionIfMissing(dimensions, ...(this.editForm.get('dimensions')!.value ?? []))
        )
      )
      .subscribe((dimensions: IDimension[]) => (this.dimensionsSharedCollection = dimensions));
  }

  protected createFromForm(): IBadge {
    return {
      ...new Badge(),
      id: this.editForm.get(['id'])!.value,
      title: this.editForm.get(['title'])!.value,
      description: this.editForm.get(['description'])!.value,
      availableUntil: this.editForm.get(['availableUntil'])!.value
        ? dayjs(this.editForm.get(['availableUntil'])!.value, DATE_TIME_FORMAT)
        : undefined,
      availableAmount: this.editForm.get(['availableAmount'])!.value,
      requiredScore: this.editForm.get(['requiredScore'])!.value,
      instantMultiplier: this.editForm.get(['instantMultiplier'])!.value,
      completionBonus: this.editForm.get(['completionBonus'])!.value,
      createdAt: this.editForm.get(['createdAt'])!.value ? dayjs(this.editForm.get(['createdAt'])!.value, DATE_TIME_FORMAT) : undefined,
      updatedAt: this.editForm.get(['updatedAt'])!.value ? dayjs(this.editForm.get(['updatedAt'])!.value, DATE_TIME_FORMAT) : undefined,
      image: this.editForm.get(['image'])!.value,
      dimensions: this.editForm.get(['dimensions'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-badge-heading" data-cy="BadgeCreateUpdateHeading" jhiTranslate="teamDojoApp.badge.home.createOrEditLabel">
        Create or edit a Badge
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badge.title" for="field_title">Title</label>
          <input type="text" class="form-control" name="title" id="field_title" data-cy="title" formControlName="title" />
          <div *ngIf="editForm.get('title')!.invalid && (editForm.get('title')!.dirty || editForm.get('title')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('title')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.minlength"
              jhiTranslate="entity.validation.minlength"
              [translateValues]="{ min: 2 }"
            >
              This field is required to be at least 2 characters.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('title')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 20 }"
            >
              This field cannot be longer than 20 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badge.description" for="field_description">Description</label>
          <input
            type="text"
            class="form-control"
            name="description"
            id="field_description"
            data-cy="description"
            formControlName="description"
          />
          <div *ngIf="editForm.get('description')!.invalid && (editForm.get('description')!.dirty || editForm.get('description')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('description')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 4096 }"
            >
              This field cannot be longer than 4096 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badge.availableUntil" for="field_availableUntil"
            >Available Until</label
          >
          <div class="d-flex">
            <input
              id="field_availableUntil"
              data-cy="availableUntil"
              type="datetime-local"
              class="form-control"
              name="availableUntil"
              formControlName="availableUntil"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badge.availableAmount" for="field_availableAmount"
            >Available Amount</label
          >
          <input
            type="number"
            class="form-control"
            name="availableAmount"
            id="field_availableAmount"
            data-cy="availableAmount"
            formControlName="availableAmount"
          />
          <div
            *ngIf="
              editForm.get('availableAmount')!.invalid &&
              (editForm.get('availableAmount')!.dirty || editForm.get('availableAmount')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('availableAmount')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 1 }"
            >
              This field should be at least 1.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('availableAmount')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badge.requiredScore" for="field_requiredScore">Required Score</label>
          <input
            type="number"
            class="form-control"
            name="requiredScore"
            id="field_requiredScore"
            data-cy="requiredScore"
            formControlName="requiredScore"
          />
          <div
            *ngIf="
              editForm.get('requiredScore')!.invalid && (editForm.get('requiredScore')!.dirty || editForm.get('requiredScore')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('requiredScore')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('requiredScore')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 0 }"
            >
              This field should be at least 0.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('requiredScore')?.errors?.max"
              jhiTranslate="entity.validation.max"
              [translateValues]="{ max: 1 }"
            >
              This field cannot be more than 1.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('requiredScore')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badge.instantMultiplier" for="field_instantMultiplier"
            >Instant Multiplier</label
          >
          <input
            type="number"
            class="form-control"
            name="instantMultiplier"
            id="field_instantMultiplier"
            data-cy="instantMultiplier"
            formControlName="instantMultiplier"
          />
          <div
            *ngIf="
              editForm.get('instantMultiplier')!.invalid &&
              (editForm.get('instantMultiplier')!.dirty || editForm.get('instantMultiplier')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('instantMultiplier')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('instantMultiplier')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 0 }"
            >
              This field should be at least 0.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('instantMultiplier')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badge.completionBonus" for="field_completionBonus"
            >Completion Bonus</label
          >
          <input
            type="number"
            class="form-control"
            name="completionBonus"
            id="field_completionBonus"
            data-cy="completionBonus"
            formControlName="completionBonus"
          />
          <div
            *ngIf="
              editForm.get('completionBonus')!.invalid &&
              (editForm.get('completionBonus')!.dirty || editForm.get('completionBonus')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('completionBonus')?.errors?.min"
              jhiTranslate="entity.validation.min"
              [translateValues]="{ min: 0 }"
            >
              This field should be at least 0.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('completionBonus')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badge.createdAt" for="field_createdAt">Created At</label>
          <div class="d-flex">
            <input
              id="field_createdAt"
              data-cy="createdAt"
              type="datetime-local"
              class="form-control"
              name="createdAt"
              formControlName="createdAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('createdAt')!.invalid && (editForm.get('createdAt')!.dirty || editForm.get('createdAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('createdAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('createdAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badge.updatedAt" for="field_updatedAt">Updated At</label>
          <div class="d-flex">
            <input
              id="field_updatedAt"
              data-cy="updatedAt"
              type="datetime-local"
              class="form-control"
              name="updatedAt"
              formControlName="updatedAt"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('updatedAt')!.invalid && (editForm.get('updatedAt')!.dirty || editForm.get('updatedAt')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('updatedAt')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('updatedAt')?.errors?.ZonedDateTimelocal"
              jhiTranslate="entity.validation.ZonedDateTimelocal"
            >
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badge.image" for="field_image">Image</label>
          <select class="form-control" id="field_image" data-cy="image" name="image" formControlName="image">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="imageOption.id === editForm.get('image')!.value?.id ? editForm.get('image')!.value : imageOption"
              *ngFor="let imageOption of imagesSharedCollection; trackBy: trackImageById"
            >
              {{ imageOption.title }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label jhiTranslate="teamDojoApp.badge.dimensions" for="field_dimensions">Dimensions</label>
          <select class="form-control" id="field_dimensions" data-cy="dimensions" multiple name="dimensions" formControlName="dimensions">
            <option
              [ngValue]="getSelectedDimension(dimensionOption, editForm.get('dimensions')!.value)"
              *ngFor="let dimensionOption of dimensionsSharedCollection; trackBy: trackDimensionById"
            >
              {{ dimensionOption.title }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
