// src/main/webapp/app/entities/badge-skill/badge-skill-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="teamDojoApp.badgeSkill.home.createOrEditLabel"
          data-cy="BadgeSkillCreateUpdateHeading"
          v-text="$t('teamDojoApp.badgeSkill.home.createOrEditLabel')"
        >
          Create or edit a BadgeSkill
        </h2>
        <div>
          <div class="form-group" v-if="badgeSkill.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="badgeSkill.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badgeSkill.badge')" for="badge-skill-badge">Badge</label>
            <select class="form-control" id="badge-skill-badge" data-cy="badge" name="badge" v-model="badgeSkill.badge" required>
              <option v-if="!badgeSkill.badge" v-bind:value="null" selected></option>
              <option
                v-bind:value="badgeSkill.badge && badgeOption.id === badgeSkill.badge.id ? badgeSkill.badge : badgeOption"
                v-for="badgeOption in badges"
                :key="badgeOption.id"
              >
                {{ badgeOption.title }}
              </option>
            </select>
          </div>
          <div v-if="$v.badgeSkill.badge.$anyDirty && $v.badgeSkill.badge.$invalid">
            <small class="form-text text-danger" v-if="!$v.badgeSkill.badge.required" v-text="$t('entity.validation.required')">
              This field is required.
            </small>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('teamDojoApp.badgeSkill.skill')" for="badge-skill-skill">Skill</label>
            <select class="form-control" id="badge-skill-skill" data-cy="skill" name="skill" v-model="badgeSkill.skill" required>
              <option v-if="!badgeSkill.skill" v-bind:value="null" selected></option>
              <option
                v-bind:value="badgeSkill.skill && skillOption.id === badgeSkill.skill.id ? badgeSkill.skill : skillOption"
                v-for="skillOption in skills"
                :key="skillOption.id"
              >
                {{ skillOption.title }}
              </option>
            </select>
          </div>
          <div v-if="$v.badgeSkill.skill.$anyDirty && $v.badgeSkill.skill.$invalid">
            <small class="form-text text-danger" v-if="!$v.badgeSkill.skill.required" v-text="$t('entity.validation.required')">
              This field is required.
            </small>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.badgeSkill.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./badge-skill-update.component.ts"></script>

// src/main/webapp/app/entities/badge-skill/update/badge-skill-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IBadgeSkill, BadgeSkill } from '../badge-skill.model';
import { BadgeSkillService } from '../service/badge-skill.service';
import { IBadge } from 'app/entities/badge/badge.model';
import { BadgeService } from 'app/entities/badge/service/badge.service';
import { ISkill } from 'app/entities/skill/skill.model';
import { SkillService } from 'app/entities/skill/service/skill.service';

@Component({
  selector: 'jhi-badge-skill-update',
  templateUrl: './badge-skill-update.component.html',
})
export class BadgeSkillUpdateComponent implements OnInit {
  isSaving = false;

  badgesSharedCollection: IBadge[] = [];
  skillsSharedCollection: ISkill[] = [];

  editForm = this.fb.group({
    id: [],
    badge: [null, Validators.required],
    skill: [null, Validators.required],
  });

  constructor(
    protected badgeSkillService: BadgeSkillService,
    protected badgeService: BadgeService,
    protected skillService: SkillService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ badgeSkill }) => {
      this.updateForm(badgeSkill);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const badgeSkill = this.createFromForm();
    if (badgeSkill.id !== undefined) {
      this.subscribeToSaveResponse(this.badgeSkillService.update(badgeSkill));
    } else {
      this.subscribeToSaveResponse(this.badgeSkillService.create(badgeSkill));
    }
  }

  trackBadgeById(index: number, item: IBadge): number {
    return item.id!;
  }

  trackSkillById(index: number, item: ISkill): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IBadgeSkill>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(badgeSkill: IBadgeSkill): void {
    this.editForm.patchValue({
      id: badgeSkill.id,
      badge: badgeSkill.badge,
      skill: badgeSkill.skill,
    });

    this.badgesSharedCollection = this.badgeService.addBadgeToCollectionIfMissing(this.badgesSharedCollection, badgeSkill.badge);
    this.skillsSharedCollection = this.skillService.addSkillToCollectionIfMissing(this.skillsSharedCollection, badgeSkill.skill);
  }

  protected loadRelationshipsOptions(): void {
    this.badgeService
      .query()
      .pipe(map((res: HttpResponse<IBadge[]>) => res.body ?? []))
      .pipe(map((badges: IBadge[]) => this.badgeService.addBadgeToCollectionIfMissing(badges, this.editForm.get('badge')!.value)))
      .subscribe((badges: IBadge[]) => (this.badgesSharedCollection = badges));

    this.skillService
      .query()
      .pipe(map((res: HttpResponse<ISkill[]>) => res.body ?? []))
      .pipe(map((skills: ISkill[]) => this.skillService.addSkillToCollectionIfMissing(skills, this.editForm.get('skill')!.value)))
      .subscribe((skills: ISkill[]) => (this.skillsSharedCollection = skills));
  }

  protected createFromForm(): IBadgeSkill {
    return {
      ...new BadgeSkill(),
      id: this.editForm.get(['id'])!.value,
      badge: this.editForm.get(['badge'])!.value,
      skill: this.editForm.get(['skill'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-badge-skill-heading" data-cy="BadgeSkillCreateUpdateHeading" jhiTranslate="teamDojoApp.badgeSkill.home.createOrEditLabel">
        Create or edit a Badge Skill
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badgeSkill.badge" for="field_badge">Badge</label>
          <select class="form-control" id="field_badge" data-cy="badge" name="badge" formControlName="badge">
            <option *ngIf="!editForm.get('badge')!.value" [ngValue]="null" selected></option>
            <option
              [ngValue]="badgeOption.id === editForm.get('badge')!.value?.id ? editForm.get('badge')!.value : badgeOption"
              *ngFor="let badgeOption of badgesSharedCollection; trackBy: trackBadgeById"
            >
              {{ badgeOption.title }}
            </option>
          </select>
        </div>
        <div *ngIf="editForm.get(['badge'])!.invalid && (editForm.get(['badge'])!.dirty || editForm.get(['badge'])!.touched)">
          <small class="form-text text-danger" *ngIf="editForm.get(['badge'])?.errors?.required" jhiTranslate="entity.validation.required">
            This field is required.
          </small>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="teamDojoApp.badgeSkill.skill" for="field_skill">Skill</label>
          <select class="form-control" id="field_skill" data-cy="skill" name="skill" formControlName="skill">
            <option *ngIf="!editForm.get('skill')!.value" [ngValue]="null" selected></option>
            <option
              [ngValue]="skillOption.id === editForm.get('skill')!.value?.id ? editForm.get('skill')!.value : skillOption"
              *ngFor="let skillOption of skillsSharedCollection; trackBy: trackSkillById"
            >
              {{ skillOption.title }}
            </option>
          </select>
        </div>
        <div *ngIf="editForm.get(['skill'])!.invalid && (editForm.get(['skill'])!.dirty || editForm.get(['skill'])!.touched)">
          <small class="form-text text-danger" *ngIf="editForm.get(['skill'])?.errors?.required" jhiTranslate="entity.validation.required">
            This field is required.
          </small>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
